### ISSUE TITLE
Rewrite search control and add support for OpenSearch

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#10]
Allow search to be activated from the URL.

For example, `http://osm.org.il/IsraelHiking/?q=Haifa ` will open the map site and search for "Haifa"

**Comment by HarelM** [comment]
I'm not sure we can support it in other places beside initial search result since the address bar is used for storing the current route data - meaning you can use it only when first navigation to this address ```www.../?q=bla```.
Also, I must ask how this is useful? since you can share the location with a relevant marker with info, and since (I think) people wont be able to share a search query (since the address bar is occupied with route data), I'm beginning think this won't be possible...
Just a side note: The search control is an external plug-in I use (there aren't many of them but still), and so it might be a little harder to add this functionality.

**Comment by zstadler** [comment]
The goal is enable such a search from the browser.
Ideally, the browser will be able to suggest adding the Israel Hiking search as one of its installed search engines, as is with sites like eBay, GitHub, and more.

It is also possible in Firefox to define a bookmark like `http://amudanan.co.il/?search=%s`, assign it a keyword like "עע". When "עע עין גדי" is entered in the address bar, Firefox then goes to http://amudanan.co.il/?search=עין+גדי

**Comment by HarelM** [comment]
This is very "gadgety", I don't see a big benefit for all users, not sure it's worth our time...
Also the above example probably saves only 1-2 clicks...

**Comment by zstadler** [comment]
This allows <select text> -> <right-click> -> "Search in Israel Hiking Map"
regardless if the Israel Hiking Map page is open.

It's much more convenient than "saves only 1-2 clicks"

**Comment by zstadler** [comment]
OpenSearch is an interface supported by Firefox and Chrome that allows sites to offer themselves as a search engines that the user can add to his/her broswer.

See [how-to-add-google-chrome-omnibox-search-support-for-your-site on Stackoverflow](stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site) and [OpenSearch](http://www.opensearch.org/Home)

**Comment by HarelM** [comment]
I can't do it without rewriting the search control, it is also not styled with bootstrap and looks bad in mobile devices. This plug-in should be rewritten so that it looks like it belongs to the site...

**Comment by HarelM** [comment]
In order to follow current architecture I have set the search to:
```
http://osm.org.il/IsraelHiking/#/?q=Haifa
```
Please let me now if this works for you (I'll let you know when the prerelease site is up).
This requires a note in the documentation, not sure if I should put it in the help or in the readme here since this is a very advanced feature...

**Comment by zstadler** [comment]
This is just fine. The "elegance" of the URL is not an issue.
