### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1001]
## What really happened
The link to the image of [מעלה ראס אל חממה](https://israelhiking.osm.org.il/poi/OSM/node_6054062189) is broken.

#### Facts:
- The POI was created by the site in [changeset 64393955](https://www.openstreetmap.org/changeset/64393955), and there was no other edit afterwards. 
- The link is to an image named `מעלה ראס אל חממה.jpeg`
- [Searching for "מעלה ראס אל חממה" on Wikimedia Commons](https://commons.wikimedia.org/w/index.php?search="ראס+אל+חממה") shows that it is redirected to an image named "עליה מאתגרת - יש קצת בורות בעליה ודרדרת.jpeg".

   ![image](https://user-images.githubusercontent.com/1304610/56015215-e5e6c480-5d00-11e9-82a0-973cbc072a27.png)

- "עליה מאתגרת - יש קצת בורות בעליה ודרדרת" is the description of the POI
- The image was uploaded in 12-October, and was used in a POI created in 12-November:
   - OSM changeset: `created_at="2018-11-12T06:27:57Z" closed_at="2018-11-12T06:27:58Z" `
   - Wikimedia history: ` 11:40, 12 October 2018
- The user has an [empty changeset](https://www.openstreetmap.org/api/0.6/changeset/63452607) created on 12-October using the site
   - OSM changeset: `Created_at="2018-10-12T11:40:41Z" closed_at="2018-10-12T12:40:41Z"`
   - The [OSM change file](https://www.openstreetmap.org/api/0.6/changeset/63452607/download) of this changeset is an invalid XML file.

#### Thoughts:
- We need to understand better the causes for image redirects on Wikimedia Commons as a first step to avoid and overcome them.

**Comment by HarelM** [comment]
I can't imagine what could've caused this - it is weird to see that the image upload date and the POI creation data are different since the IHM changeset comment is "Added..." which means the POI did not exist before this commit.
What might have happened is the following:
1. The user added a POI with the name עליה מאתגרת ... with the above image
2. Found out he made a mistake
3. Delete the POI
4. Added another POI with the same image with the right name

I'm not sure how to make sure this is what really happened but every missing image I've seen so far was due to a previously uploaded image that was exactly the same and wikimedia removed the second uploaded image and added a redirect, which the site and OSM are not notified about.

**Comment by zstadler** [comment]
I've [asked for help](https://commons.wikimedia.org/wiki/Commons:Help_desk#Re-directions_break_the_%22Use_this_file_on_the_web%22_links) on the Wikimedia Commons Help Desk.

**Comment by zstadler** [comment]
According the the responses, there is an API that could be used to find the redirect

1. Extract the image filename from the broken url, removing the `https://upload.wikimedia.org/wikipedia/commons/?/??/` prefix.

    In this case, it would be `Israel_Hiking_Map_%D7%9E%D7%A2%D7%9C%D7%94_%D7%A8%D7%90%D7%A1_%D7%90%D7%9C_%D7%97%D7%9E%D7%9E%D7%94.jpeg`
2. Use the image filename instead of `<filename.jpeg>` in this API URL `https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&titles=File%3A<filename.jpeg>&iiprop=url`

   In this case, it would be [this URL](https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&titles=File%3AIsrael_Hiking_Map_%D7%9E%D7%A2%D7%9C%D7%94_%D7%A8%D7%90%D7%A1_%D7%90%D7%9C_%D7%97%D7%9E%D7%9E%D7%94.jpeg&iiprop=url)
3. The API response is the a JSON file containing the new URL in `pages.imageinfo.url`.

   In this case:   
   ```
   {
     "batchcomplete": "",
     "query": {
       "normalized": [
	 {
	   "from": "File:Israel_Hiking_Map_מעלה_ראס_אל_חממה.jpeg",
	   "to": "File:Israel Hiking Map מעלה ראס אל חממה.jpeg"
	 }
       ],
       "pages": {
	 "74379765": {
	   "pageid": 74379765,
	   "ns": 6,
	   "title": "File:Israel Hiking Map מעלה ראס אל חממה.jpeg",
	   "imagerepository": "local",
	   "imageinfo": [
	     {
	       "url": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Israel_Hiking_Map_%D7%A2%D7%9C%D7%99%D7%94_%D7%9E%D7%90%D7%AA%D7%92%D7%A8%D7%AA_-_%D7%99%D7%A9_%D7%A7%D7%A6%D7%AA_%D7%91%D7%95%D7%A8%D7%95%D7%AA_%D7%91%D7%A2%D7%9C%D7%99%D7%94_%D7%95%D7%93%D7%A8%D7%93%D7%A8%D7%AA.jpeg",
	       "descriptionurl": "https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_%D7%A2%D7%9C%D7%99%D7%94_%D7%9E%D7%90%D7%AA%D7%92%D7%A8%D7%AA_-_%D7%99%D7%A9_%D7%A7%D7%A6%D7%AA_%D7%91%D7%95%D7%A8%D7%95%D7%AA_%D7%91%D7%A2%D7%9C%D7%99%D7%94_%D7%95%D7%93%D7%A8%D7%93%D7%A8%D7%AA.jpeg",
	       "descriptionshorturl": "https://commons.wikimedia.org/w/index.php?curid=73564740"
	     }
	   ]
	 }
       }
     }
   }
   ```
4. The URL-decoded text of `pages.imageinfo.url`, can be used in the OSM `image*` tag.

   In this case, `https://upload.wikimedia.org/wikipedia/commons/7/7e/Israel_Hiking_Map_עליה_מאתגרת_-_יש_קצת_בורות_בעליה_ודרדרת.jpeg`.

#### Note
The URL for the original uploaded image is 269 character-long, however OSM limits the length of tag values to 255 characters. This is probably the result the OSM update failed. However, OSM allows Unicode characters in tags.

**Comment by zstadler** [comment]
Once #1002 is implemented, I will use the above procedure to fix existing broken links and close this issue.

**Comment by HarelM** [comment]
Who should check that the link is broken and when?
The image tag is taken straight from OSM and used inside a `img` HTML tag so there's no explicit check that the image exists (not returning 404).
Checking to verify that each image exists is not so network efficient.
Since we should support offline usage that should allow seeing an image for public POIs maybe the mechanism of creating this database should also fix OSM issues such as the above.
I'm not sure, I don't have a good idea how to properly solve this...

**Comment by zstadler** [comment]
At this stage, I'm not suggesting any automatic fixing of broken image links.

I have created some semi-automatic scripts and used them to identify and resolve issues in 27 OSM elements in Israel.
