### ISSUE TITLE
found ways appear as polygons

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1008]
## What I expect to happen
In the MapBpx-based beta version I expect searched linear features to appear as lines

## What really happened
They appear shaded like a polygon

## What I did that caused the issue - step by step
Went to the beta version.
Searched for a route (שביל הפסגה)
observed the result

## My environment
Chrome on web

## Thing I think the developers should know, images, links etc.
https://israelhiking.osm.org.il/beta/poi/OSM/relation_3640190?language=he
![image](https://user-images.githubusercontent.com/689201/56861210-7a128600-69a7-11e9-9465-580bbe4cce6b.png)

**Comment by HarelM** [comment]
Thanks for reporting!
This is probably due to the following code which adds a fill to the shape - I was under the impression that mapbox will only add fill to closed polygons.
@valleyofdawn are you familiar with the mapbox syntax that will do it only for closed shapes? something like `filter: ['any', ['==', '$type', 'Polygone'], ['==', '$type', 'MultiPolygon']]`?

**Comment by valleyofdawn** [comment]
> @valleyofdawn are you familiar with the mapbox syntax that will do it only for closed shapes? something like filter: ['any', ['==', '$type', 'Polygone'], ['==', '$type', 'MultiPolygon']]?

I'm not

**Comment by zstadler** [comment]
[The spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/#combining-filters) says that `$type` can have one of 3 values: `"Point"`, `"LineString"`, and `"Polygon"`.

Therefore, the filter is probably `["all", ["==", "$type", "Polygon"]]`
