### ISSUE TITLE
slow upload time of shared routes with images over mobile data

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1019]
## What I expect to happen
The track should load within a few seconds, or a message should explain what's happening

## What really happened
When sharing a track with several HD images over mobile data this typically takes many minutes.
Meanwhile the user is left baffled with what looks like a frozen app.

## What I did that caused the issue - step by step
Recorded a track.
Added a few pictures as POIs
Tried to share the track with no Wi-Fi
It took several minutes; there was no indication why the screen is nor tesponsive.
## My environment
* Operating System and version:
Latests Android app

## Thing I think the developers should know, images, links etc.
I suggest, at a minimum to add a message "Please wait, uploading images" after a few seconds.
Better yet, suggest sharing the track only and updating it with images when Wi-Fi is connected (much like Google Images does).

**Comment by HarelM** [comment]
I don't think wifi will help, upload rate in israel is horrible. Not this is not related to the fact that the images are HD since they are scaled, as I explained earlier.
Can you please check how much time it takes for the images to be attached to a mail in gmail? I assume it will be even worse.
I don't think adding a message after a few second will help as you say that it takes a long time.
We can just dismiss the dialog and continue the upload in the background which is probably the fastest solution, but it might introduce other problems of closing the app while uploading etc...

**Comment by valleyofdawn** [comment]
It took around 15 secs (instead of 60) over Wi Fi. Results may differ.
In Gmail it was a long process too but it happened in the background (once the mail was sent it spent a minute in the outbox before going to the sent mail.
The frustration is getting stuck with this image, with no progress bar and not knowing if the app is active or not. 
![image](https://user-images.githubusercontent.com/689201/57103686-2dc0a080-6d2f-11e9-8e9f-fd9c1180b83e.png)

**Comment by zstadler** [comment]
I suggest that uploading in the background/on Wi-Fi/etc. will be excluded from this issue and considered as part of a robust offline solution.

**Comment by valleyofdawn** [comment]
In that case, a progress indicator, or a warning: "this may take a while, consider using wi-fi", will help.

**Comment by HarelM** [comment]
When talking about background I'm referring to the fact that the dialog will close and the request will be sent in parallel - I don't think this is related to an offline solution.
In any case, this is not a high priority issue as the only problem here is the user's patience... reducing severity.

**Comment by HarelM** [comment]
After our discussion the suggested solution is as follows:
Set a timeout, say 20 seconds, after that the dialog will close automatically with the following message (using the bottom "snackbar"):
"This is taking longer than expected, continuing the upload in the background...".
And a message when the operation was completed successfully, something like:
"A share was created, you can open 'my shares' menu to see it"
Since this menu is not available for unregistered users, the behavior will not change and there won't be a timeout.

**Comment by zstadler** [comment]
As noted above, I agree with the proposed solution. The following questions are for a future UX discussion, when the time to implement this comes:

- Can there be an indication that a share upload has not completed yet?
   It can be under "My Shares" or elsewhere.
- Can we extend the initial message to something that will guide the user's expectations?
   The following phrase is a bit too long also IMO:
   > The share continues to upload in the background and will be added to "My Shares" when done.
