### ISSUE TITLE
Wrong height measurement

### ISSUE THREAD

**Issue by ErezNahoum** [IsraelHikingMap/Site#1044]
[trailBug.zip](https://github.com/IsraelHikingMap/Site/files/3271207/trailBug.zip)

## Bug/Feature
(Delete the non-relevant)

## What really happened
I planed rout and view the gain height and for part of the rout it show more gain height then in the full rout.

Please see attached jpg and gpx

## What I did that caused the issue - step by step

1. Plan route using the Person icon.

## My environment
* Operating System and version:
Window 7
* Web Browser and version:
Chrome

**Comment by HarelM** [comment]
Thanks for reporting this issue, it is truly strange.
We'll take a look at it.

**Comment by HarelM** [comment]
Seems like this bug is very old.
The gain and loss calculation is done on a simplified line in order to reduce noise.
Seems like the line was over simplified in this case, and probably in other cases.
The above partial line has about 220 points which are simplified to 9 (!).
The full line has about 260 points which are simplified to 7 (!!).
The fix will be available in next release.
Thanks for reporting this issue!
