### ISSUE TITLE
Wrong elevation gain calculation

### ISSUE THREAD

**Issue by ErezNahoum** [IsraelHikingMap/Site#1049]
## Bug/Feature
(Delete the non-relevant)

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by ErezNahoum** [comment]
He Harel,

I tried yesterday the new elevation gain and it seems too "pessimistic".

I'm riding with Garmin watch and my friend also.

Bath watch shows at the end of the ride: 670m elevation gain.
Runkeeper show: 777m elevation gain.

The IHM show: 1000m elevation gain.

Best regards,
Erez
0522350240

[RK_gpx _2019-07-03_2006.zip](https://github.com/IsraelHikingMap/Site/files/3357814/RK_gpx._2019-07-03_2006.zip)

**Comment by HarelM** [comment]
I'm sorry, but I can't help I'm this case.
The elevation calculated in the site is based on elevation model, so it probably a lot more accurate than anything else you have.
I can only revert the last fix which I don't think it's the right solution.

**Comment by ErezNahoum** [comment]
Hi,

Can you check what is the elevation gain for the gpx with the privious
version?

BR,
Erez

בתאריך יום ה׳, 4 ביולי 2019, 8:48, מאת Harel M ‏<notifications@github.com>:

**Comment by HarelM** [comment]
Well, you can probably fine tune this to the end of days...
The problem here is that I'm using the wrong tool for the job,
I'm trying to take a noisy distance to altitude coordinates and smooth them using (Ramer–Douglas–Peucker)[https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm].
This algorithm is good for lines that have the same x-y units.
In any case, I'm calibrated the x to be Km/100 and y to be altitude in meters and set the tolerance to 5 (50 meters in distance and 5 meters in altitude).
It gives good results for both this issue and #1044.
