### ISSUE TITLE
Allow modifying layer definitions

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#105]
Such as the name, URL, zoom boundaries

**Comment by HarelM** [comment]
I thought about it, but I think it's easier to just delete the layer and re-add it with relevant data.

**Comment by zstadler** [comment]
I believe you were assuming the layer definition information is (still)
available. This is also not the case when the layer was received through
sharing.

**Comment by HarelM** [comment]
It should work theoretically as the shared layer is parsed and added to the layers control.
Can you send me an example and I'll see if it work or not?

**Comment by zstadler** [comment]
http://osm.org.il/IsraelHiking/#/17/31.0095/35.2893?baselayer=http:%2F%2Fa.tile.openstreetmap.org%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png&markers=&Route_1=

**Comment by HarelM** [comment]
Please use the new site, I'm no longer maintaining the old one since I'll be doing a redirect once I finish the short URL feature.
http://IsraelHiking.osm.org.il/#/17/31.0095/35.2893?baselayer=http:%2F%2Fa.tile.openstreetmap.org%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png&markers=&Route_1=
This is totally working! :-)

**Comment by zstadler** [comment]
Works great!
