### ISSUE TITLE
The map would not zoom-out below zoom level 7

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1052]
## What I expect to happen
Min zoom to be determined by the layer definition.

## What really happened
The map would not zoom-out below zoom level 7

## What I did that caused the issue - step by step
Try to zoom out below level 7 using the ESRI builtin map and with the following custom base layer:
   - Name: Wikimedia
   - URL: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}@1.5x.png?lang=he
   - Min Zoom: 0
   - Max Zoom: 19

## My environment
* Operating System and version: Win 10 Home
* Web Browser and version: Firefox 68.0.1 (64-bit)

## Thing I think the developers should know, images, links etc.
This used to work.

min-zoom for ESRI is 0:

https://github.com/IsraelHikingMap/Site/blob/e67a2c89f321bde10d09f91d697178246173b3be/IsraelHiking.Web/sources/application/reducres/initial-state.ts#L63-L67

**Comment by HarelM** [comment]
In order to convert from leaflet/openlayers to mapbox there's a need to do "-1" in the code:
https://github.com/IsraelHikingMap/Site/blob/86103c4b514ed9dc465c05c95da286d16e693941/IsraelHiking.Web/sources/application/components/map/automatic-layer-presentation.component.ts#L93
So setting to 0 will result in an invalid minimal zoom which probably defaults to 7 for some reason (previous layer that was loaded I guess).
I don't see a good reason to add more logic to this hack. you can simply set the minimal zoom level to 1, which probably makes more sense...
Feel free to close this.

**Comment by zstadler** [comment]
From a user's perspective Mapbox's distorted zoom levels are invisible, and that is great! Zero is a valid "[slippy map](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Zoom_levels)" zoom level that the site supported until the switch to Mapbox.

IMO, this minor change would resolve this issue 
```
minzoom: max(this.minZoom - 1,0)
```
Do you want a PR?

**Comment by zstadler** [comment]
Thanks!
