### ISSUE TITLE
Restore attribution text

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1059]
## What I expect to happen
Attribution to appear in the bottom right corner of the map

## What really happened
Currently, there are no atttributions to OSM and ESRI

## My environment
* Operating System and version: Android
* Web Browser and version: Firefox, Chrome

## Thing I think the developers should know, images, links etc.

According to the [recently updated request](https://docs.google.com/document/d/1e_IQYHtqVivGRw4O4EOn6__-LGMuzPlWz6XKEdAkwW0)  from OSM, for cases such as this site, the "Map data © OpenStreetMap contributors" attribution would be appropriate while making the text “© OpenStreetMap contributors” a link which links to www.openstreetmap.org/copyright.

**Comment by valleyofdawn** [comment]
I think this is important. We've asked other parties to follow this rule and it looks bad if we don't.

**Comment by HarelM** [comment]
We have the following wiki page that list all the attribution instead of cluttering the map:
https://github.com/IsraelHikingMap/Site/wiki/Attribution
But this page is not linked directly from the site, here's my proposal to solve this - use mapbox's attribution control: before hover or click:
![image](https://user-images.githubusercontent.com/3269297/64368336-bf645580-d022-11e9-9888-01a4d2d1cf9e.png)
After hover or click:
![image](https://user-images.githubusercontent.com/3269297/64368157-64326300-d022-11e9-9326-a2877bb2c2e5.png)
If this is not acceptable please propose another solution.
