### ISSUE TITLE
Thumbnails for "My Recordings"

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1064]
## What I expect to happen
Show thumbnails for "My Recordings"

## What really happened
![image](https://user-images.githubusercontent.com/1304610/64987081-1db9ef80-d8d1-11e9-8a30-6eddf250ccb6.png)

**Comment by HarelM** [comment]
This used to work until OSM changed their behavior. Private recordings require some headers to be sent in order to be shown and this is only possible if the recording image is sent though the server, i think. 
I thought about generating the image on the server but it's problematic too as it requires the recording itself.
Public recordings do not have this issue. 
I couldn't find a good solution to this issue yet...

**Comment by HarelM** [comment]
As part of the OSM client migration in #1074 I have added the code to generate images for OSM traces, it is not cached and needs to be improved in terms of offline and performance, but I think it'll do for now.

**Comment by HarelM** [comment]
Seems like I have broke this functionality somewhere along the way when adding the offline support.
