### ISSUE TITLE
Update location of an OSM POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1068]
## What I expect to happen
Be able to update the location of an OSM POI

## What really happened
It is possible to update many features of an OSM POI, but not its location

## Thing I think the developers should know, images, links etc.
The primary objective is to be able to use the current GPS position to update the location of an existing OSM POI.

An example use case:
The user visits an existing OSM POI and finds that its location is inaccurate. He can create a private POI at the correct place and decide to publish it. When the "do you want to update _Public POI_" question is shown, he responds "yes", but currently the POI position is not changed (*). I suggest that in the above scenario, the position of the existing OSM POI will also be changed.

The above scenario can also work if there is no network at the POI: the private POI can be created at the location even if there is no network, and the update to the public POI can be done when network connection is restored.

(*) Actually, IHM does make small changes in the location of the public POI. For example in [changeset 75089528](https://www.openstreetmap.org/changeset/75089528) [Node: Mezad Hatrurim](https://www.openstreetmap.org/node/278476354/history) was changed from 
```
Version #5 · Changeset #49412690
Location: 31.2218308, 35.3038795 
```
to
```
Version #6 · Changeset #75089528
Location: 31.2218304, 35.3038788 
```

**Comment by HarelM** [comment]
This still need a proposed UX definition...

**Comment by zstadler** [comment]
If the POI was created **and then** the user wanted to update an existing POI, the location of the original POI will be updated.
If the user opens the POI by clicking on it and then wants to update it, there is no alternative location and the location need not change.
Further discussion can be done verbally.

**Comment by HarelM** [comment]
As requested before, I need a UX definition as I can't think of a good one. This is still missing.
Looking at the user poll and the fact that deleting a POI is also not supported I'm leaning towards keeping this in the external editors and not using our site.
Providing a simple UX might change my mind, but currently this is what I'm leaning towards...

**Comment by HarelM** [comment]
A few observations after looking into implementing this:
1. Changing the location of  POI should only be available for POIs that their geometry is point - i.e. I shouldn't be able to change by mistake the location of a way or settlement.
2. It seems that the location is currently sent to the server but the server ignores it - i.e. the changes in location described above is due to precision accuracy somewhere in the OSM API, C# code, or something in memory, not related to what the client had sent in this case.
3. If I change the server code to change the location without changing the upload OSM POI API interface it will change the location for old clients by default, which I'm OK with until a version will be fully distributed. i.e. I need to develop this in a branch and only merge the server side code when releasing a new version of the app.

**Comment by HarelM** [comment]
Implementation completed on the relevant branch, will be merged to stable just before next mobile releases.
