### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1075]
## What I expect to happen
Application to run

## What really happened
Error during initialization: `TypeError: e.level.padStar is not a function`

## What I did that caused the issue - step by step
Run the latest app build

## My environment
* Operating System and version: Android 7 tablet
* App version: 8.0.433

## Thing I think the developers should know, images, links etc.

* The site works well through the browser
* The following error message is shown:
   ![image](https://user-images.githubusercontent.com/1304610/66759964-dad84100-eea9-11e9-8530-ffea05c9c744.png)

**Comment by HarelM** [comment]
The place in the code which corresponds to the following error might be the following line:
https://github.com/IsraelHikingMap/Site/blob/d7c4cd2789cc1e6d24d476579b573817f2f98cb2/IsraelHiking.Web/sources/application/services/logging.service.ts#L121
But I have no clue why this line can cause issues... maybe it needs to be polyfilled on some devices.
@zstadler I'll commit a change in a few minutes to show more info on why this function is missing, can you have your friend install the app when the build completes?

**Comment by HarelM** [comment]
Possible solution: adding a polyfill as described here:
https://stackoverflow.com/questions/46989913/angular-4-use-es2017-e-g-string-prototype-padstart
Or the below if the above doesn't work:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart
The problem is that I don't know what else will be missing...

**Comment by HarelM** [comment]
Reported to be resolved after the polyfills were added.
