### ISSUE TITLE
Layer definitions are duplicated in Local Storage on every page load

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#109]
For osm.org.il, for example, I currently have 159 overlay entries - all are duplicates of the default overlay layer.

User-defined layers are also duplicated.

Also, for Base Layers, some duplication omits the maxZoom entries.

To examine local storage, you may use Firefox with [FireBug](https://addons.mozilla.org/en-us/firefox/addon/firebug/?src=dp-dl-dependencies) and [FireStorage Plus!](https://addons.mozilla.org/en-us/firefox/addon/firestorage-plus/)

**Comment by HarelM** [comment]
I can't reproduce on my PC.
Did you try deleting all the layers and overlays and see if it is still adding all of them back?

**Comment by zstadler** [comment]
Yes I did.
Did you look at the raw JSON values of the entire array in the local storage?
Did you try on Firefox?

**Comment by HarelM** [comment]
I haven't looked in the local storage since I can just debug the code and see what it returns in the javascript code.
I'm using only Firefox, does it reproduce for you on all browsers or just Firefox?
I can instruct you how to debug it and undestand why it happens if you have some time for it.
The main class that is doing the job is called LayerService.
It has a method called addLayerFromLocalStorage which add layers according to the name presented in the layers control - meaning you can't add two layers with the same name.

**Comment by HarelM** [comment]
Still an issue? Can I help?

**Comment by zstadler** [comment]
I've left the browser open on the Israel Hiking server with the Storage inspector showing the duplication after 1 reload.
I cannot seem to locate the sources in order to debug it myself.

**Comment by HarelM** [comment]
Ok, now I think we are on the same page.
It's not that you see it in the UI it's just in the local storage - which might impact performance.
How did you find it?

**Comment by zstadler** [comment]
I was looking for ways to export the layer definitions so I can import to other PCs or between the old and the new Israel Hiking sites. - Issue #106.
I was able to do the export through FireStorage Plus!, but the import is only partial.

**Comment by HarelM** [comment]
I'm a bit stuck with the short URL (it doesn't feel right and I don't have a good idea how to improve it) - which should, IMO, allow sharing of everything including maps.
You can use the FireStorage to export all your layers and then just add them one by one, although this might take a while it's probably a one time thing...
