### ISSUE TITLE
Separate the UX of the "GPS" and "Record" buttons

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1096]
## What I expect to happen
1. The GPS button controls the auto-follow of the GPS position when recording is inactive or not.
2. Recording is stopped only by the Record button.

## What really happened
Currently, 

- There is no way to stop auto-following of the GPS if recording is active. For example, a user would like to keep the map focused on the destination while driving there or trying to find a way to it.
- There are two ways to stop track recording: pressing the "record" button or pressing the "GPS" button.

#### Note 1
The requested UX is that from a user's perspective:
1. The "GPS" button is the "Follow-GPS" button
2. The "GPS" button does not have a side-effect of stopping a recording

No. 1 above is currently applicable as long as recording is inactive, which is the more common state.

#### Note 2
The app may maintain the current behavior where the Record button is hidden until after the GPS button is activated and GPS location is acquired. Alternatively, the record button can be always visible and fully independent from the state of the Follow-GPS button. In the alternative UX, recording would start or stop regardless of the state of the auto-follow.

**Comment by HarelM** [comment]
I would like to avoid adding more buttons to the main screen.
Another solution to this issue is to remove the ability to disable GPS tracking.
A lot of navigation apps do not have this ability.
For the site this might have been useful, but now most users are using the site from mobile device or the app it and might be time to leave behind this old behavior.
I favor this approach instead of complicating the behavior of the buttons.
