### ISSUE TITLE
Map-view flight to search result is canceled if POI pane is closed

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1127]
## What I expect to happen
Map-view flight to a selected search result to complete even if the POI pane is closed

## What really happened
If the POI pane is closed, using its `x` button, during the map-view flight to the result location, the map-view flight is aborted and the map-view flies back to the originating view.

Form a User perspective, the closure of the POI pane is intended allow a full view of the map. This is especially true for a mobile screen where the user cannot even know if the map-view flight has completed.

## What I did that caused the issue - step by step
1. Search for "יהל" and click on the "יהל, מועצה אזורית חבל אילות" result
2. Wait for the map-view flight to complete
3. Close the POI pane using its `x` icon
4. Search for "בצת" and click on the "בצת, מחוז הצפון" result
5. Before the map-view flight to the new position is completed, close the POI pane using its `x` icon

The map-view flight is aborted and the map-view flies back to יהל.

## Thing I think the developers should know, images, links etc.
This issue may or may not have a common root-cause with #828.
Nevertheless, the design required for #828 should also handle this issue.

**Comment by HarelM** [comment]
The problem here is somewhat similar to what happened with the GPS tracking - when selecting a POI the map moves to that POI. when closing the address bar the address changes to reflect the current position - thus triggering a move to this location (since changing the address bar allows moving to the address bar position) and so the flight is stopped to due a new move action.
A possible easy fix would be not to trigger a map move when the map is already moving, much like the fix we did for the GPS. The problem in this case is that the address bar would not reflect the current position.
Another option is to remove the code that moves the map when changing the address bar since the website already does a full refresh, so this is only needed when the app starts, I think...
The second option is more complex and more correct, but I'm not sure what other side effect it will cause.

**Comment by HarelM** [comment]
After phone discussion, the fix should probably be like with the GPS - `hash.service` should not update addressbar while map is moving - when the map ends its movement another event will fire and update the addressbar.
