### ISSUE TITLE
"Route-to" navigation from current position

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1132]
## Feature
This is a place-holder for discussion.

In a nutshell, it is about the value and the UX for the ability to create a route from the current GPS location to a target such as a public POI, a search result, or a location on the map.

**Comment by HarelM** [comment]
The only gap I currently see in this issue is the definition of a UX without the need for long/right click.
We can easily add a "navigate to" button for public POIs (assuming the GPS is on), but I'm not sure this will cover this issue. 
Assuming a user can plan a route relatively easily using the regular pencil it might be good enough...
If not, please suggest a UX for this, maybe using private POIs?

**Comment by HarelM** [comment]
There's an issue with using this when recording, I haven't tested it, but I though about it after closing this issue and looking at the code.
Also the implementation I did is not ideal for existing routes - it adds a segment to the end which can be cumbersome.
So here's the new definition:
Always create a new route, only if there's no selected route then select it.
In case the user would like to add it to a planned route he can merge routes as usual.
