### ISSUE TITLE
IHM edit changed waterway=stream to route=hiking

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1172]
## What I expect to happen
IHM edit should only change or add `name`, `description`, `website` and `image*` tags of existing OSM ways.

## What really happened
In [changeset 77751389](https://www.openstreetmap.org/changeset/77751389), the `waterway=stream` tag was deleted and a `route=hiking` was added.

![image](https://user-images.githubusercontent.com/1304610/75621590-0466e000-5b9f-11ea-8f63-ef3d3a65fe80.png)

## What I did that caused the issue - step by step
The exact scenario is not known. It is **probably** along these lines:
- Show the POI/hiking trails layer
- Add inature's נחל דוד to the map
- Upload to OSM

## My environment
* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.
- The added info was taken from iNature.
- This edit was done before https://github.com/IsraelHikingMap/Site/issues/1116 was resolved. It is not clear if this issue still exists
- The iNature's info was copied to OSM as-is. Related to https://github.com/IsraelHikingMap/Site/issues/1143

**Comment by HarelM** [comment]
Initial investigation (very rough one):
Both OSM stream and iNature have the same title (נחל דוד)
They are from different sources and are close enough and thus can be merged (bug?):
https://github.com/IsraelHikingMap/Site/blob/0dd7401d5632eed30198645bb56ef75eb1a2c77c/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L395
Icon is none (equivalent to search icon) and thus the icon was changed and probably also the category:
https://github.com/IsraelHikingMap/Site/blob/0dd7401d5632eed30198645bb56ef75eb1a2c77c/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L339
When the user saved this information the code uses the icon to determine the right tagging.

I'm not sure if the bug is in the `CanMerge` or `MergeFeatures` method, but I think it wasn't solved by #1116. #1143 would solve some aspect of it, but the original merge is also part of the problem.

The problem with iNature source is that in most cases we do not know the category of the POI, but this is not the case.
I'll think about a solution after the next release.

**Comment by HarelM** [comment]
I have implemented a simple fix in `CanMerge` method to avoid these kind of merges. This is a very ad-hoc solution. There are probably other merges which are incorrect. I'll fix them as we see them...
