### ISSUE TITLE
Refresh map after updating offline map

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1175]
## What I expect to happen
An up-to-date offline map will be shown automatically after an update

## What really happened
An updated style was downloaded while the offline map was shown, and the map style did not update. The style was updated after switching to another map and returning.

## What I did that caused the issue - step by step
- Update the map style
- Use the offline map for the above style
- Download the update for the offline maps

## My environment
* Operating System and version: Android 10
* Web Browser and version: App 9.0.13

## Thing I think the developers should know, images, links etc.
This may also be relevant for updates of the offline tiles.

**Comment by HarelM** [comment]
This scenario doesn't make much sense to me - if you're using offline maps you are probably in a low reception or without reception in theory. Clicking update at this time doesn't make sense to me as might either take a long time in a best scenario or not work at all in the worst.
The workaround to this issue is double pressing the offline button which I hope should work for both offline style and tiles.
I don't see a good justification to fix/implement this.

**Comment by zstadler** [comment]
> if you're using offline maps you are ***probably*** in a low reception or without reception in theory.

I disagree with your assumption. My default map is the offline Hiking map. With this choice, I do not have to switch back and forth between the offline and online maps.

Note that if the user has downloaded the offline maps and is using the online map, the app does not switch to the offline map when the internet connection is low or non-existent.

**Comment by HarelM** [comment]
The fix is not bullet proof - What it does is the following:
1. Switch base map (only) to online in case it is offline
2. Download each file
3. When download of each file completes it closes the database and overrides the file
4. Switches the base map to offline if it was like that before starting.

This might not addresses overlays well, not sure. and the user can change the basemap offline state while downloading and at the end of the process it will ignore this change.

My main concern for fixing this issue is the fact that we override a file while a database connection is open - which was changed to sqlite as part of #1186.

I would like to avoid disabling button while the download process is being made, but if we'll encounter issues in the process I don't think I'll have an alternative.
I do believe the current solution should cover most if not all use cases.

@zstadler I would greatly appreciate it if you could test this as well, I have made several basic tests but they might not have covered your use case/s.
