### ISSUE TITLE
Add the version number to the issue reporting email

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1192]
## Feature
The app/site version number is absent from the issue reporting email. It makes understanding the issue and communicating with the user more complex. Please add it.

**Comment by HarelM** [comment]
I've found this plugin:
https://ionicframework.com/docs/native/app-version
Which seems like an overkill for this feature request.
Since most of the time we know which version is in the stores I'd like to avoid adding another plugin and risk future build complications (every plugin can be abandoned and thus cause compilation issues when not maintained).
As a results of the above, I believe this should not be implemented. I did not find an easier solution.

**Comment by zstadler** [comment]
In what sense is it an overkill? If it will cause problems, we could remove it. 

We may know what was published, but with user support we need to know what is the version the user is using or was using when an issue is encountered, and the two are not necessarily the same.
