### ISSUE TITLE
Database corruption after server restart while indexing

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1223]
## Bug/Feature
(Delete the non-relevant)
החיפוש לא עובד במפה
## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Thanks for reporting!
POIs doesn't either, probably an issue with the POIs database.
I've seen this this afternoon and was planning to take a look at it later tonight, sorry...
I hope this will an easy fix and will be fixed by tomorrow morning.

**Comment by HarelM** [comment]
Issue has been resolved.
Technical notes for myself:
I have fixed the issue manually by running the rebuild POIs process again and manually adding alias.
The problem occurred since the server was restarted while updating the database, after restart the server took the wrong database.
I'll add the relevant code to prevent this from happening again and reduce the severity of this issue.

**Comment by HarelM** [comment]
Looking at the code, there seems to be an issue with the database itself as there was not alias mapping. I'm not sure there's much to do in this case in the code.
I'm closing this and I'll be monitoring if this happens again.

**Comment by HarelM** [comment]
Nope, Needed another look at it to find out the problem...
