### ISSUE TITLE
private treks are not saved

### ISSUE THREAD

**Issue by ZemerM** [IsraelHikingMap/Site#1232]
## What I expect to happen
When I add a private trek, I expect it to be saved on the app. It should also sync with the app installed on my mobile.

## What really happened
Every time I close the browser tab or refresh it, the private treks are not saved. so when i open it again, the only way to see these treks is to upload the file saved locally.
Obviously, the private treks do not appear on the mobile app

## What I did that caused the issue - step by step
1. Open https://israelhiking.osm.org.il/map and login
2. Create a private trek
3. Save it
4. refresh browser (chrome)
5. private trek is gone.
6. Repeat steps 1-3
7. close the tab
8. open Open https://israelhiking.osm.org.il/map and login
9. Private trek is no where to be found.
10. When adding a private trek, it doesn't appear on the mobile app

## My environment
* Operating System and version: windows 10 pro v. 1909
* Web Browser and version: chrome 81.0.4044.138

**Comment by HarelM** [comment]
Save button saves the track to file, it doesn't store it in the cloud.
Using the share button will allow you to do what you want, I believe.
After login and creating a share (on the right panel), this share is available in the mobile app as well under your user profile.
I agree this is confusing, we have yet to find a way to make it intuitive due to how people are used to work with files in other apps...
I believe people should stop using files, but I'm in the minority...
Regarding the fact that refresh clear the planned track on the website, we have tried to change this behavior and keep the current state between refreshes and the community did not find this feature helpful and there were a lot of voices to remove it, and so we did...
This is not the behavior when using the app...
Hope this answers your question.
Feel free to join our Facebook group where our community can help answering these kind of questions :-)

**Comment by ZemerM** [comment]
Hi,
Thanks. Using the 'share' I was able sync between desktop and mobile app. It also enabled me to save my work on the cloud.
But if I may add, this is not the user experience one would expect. And definitely not the proper way to work on the cloud. For users who want to keep their treks on the cloud it is not comfortable.
I hope you reconsider the design, cause other than that I realy enjoy working with it.
Regards,
Zemer
