### ISSUE TITLE
Improve location on/off visibility

### ISSUE THREAD

**Issue by roiros** [IsraelHikingMap/Site#1233]
## What I expect to happen
I should easily understand if the gps is running or not, when hiking and even in bright sunlight.
I mainly use IHM to hike (single/multi day) and open it only sporadically so I want to save on battery.

I would also appreciate having an option to only pinpoint my location to reorientate and not continually track it.

## What really happened
I couldn't easily notice the black/green background of the GPS icon.

## My environment
* Operating System and version:
Android 9.0, Samsung S9
* Web Browser and version:

**Comment by HarelM** [comment]
There were a lot of discussions related to GPS position/cursor.
See here for example:
#826
#1093
The black/green icon color only indicates if the GPS is centered and followed or not.
The green frame around the button indicated that the GPS is currently active.
If you don't do anything for 20 seconds the GPS will be centered and followed again if the frame is green.

Can you please better explain the problem and expected behavior?
Is the green frame not dominant enough?

**Comment by roiros** [comment]
I'm discovering functionality through this conversation, so I think it
implies that UX is a bit unclear..

maybe a beating(heart beat) icon animation for auto centering

the green frame isn't dominant enough maybe changing the background to
green and enlarging the icon to be the same size as the big record button
will make it more pronounced. the green foreground it doesn't imply clearly
enough that the gps is on. maybe background change will serve the purpose
be better.

[image: Screen Shot 2020-05-24 at 16.40.34.png]

**Comment by HarelM** [comment]
For how long are you using our app?

**Comment by roiros** [comment]
I've used it for 3-5 times as a hiking navigation app on my phone
I've used the site over 10-15 times, defining routes, sharing them, getting
routes from friends..

I've also subscribed to the app

**Comment by HarelM** [comment]
The UI concept in general follows the same rules, much like the GPS button - the sidebar buttons turn green when the are selected, the height chart etc.
I wouldn't like to change that right now.
While I agree this can probably be improved the UX is consistent across the app and once you learn the rules (which shouldn't take long) you should feel more at home.
In theory, I don't think this specific button should exist in app, the GPS should always be on, but since this code is used for both the site and the app and the maintaining resources are very limited (only me) this is the best I can do right now...
Thanks for taking the time to report this issue! :-)
