### ISSUE TITLE
Clear search results marker

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1284]
Steps:
- Search for a coordinate, such as "222000 666000"
- Click/touch on the result

The search result icon appears on the map and I don't know how this item can be removed.

I've tried:
- Click/touch the icon
- Exit the app

The issue is unique to coordinate search. When the search result is a POI, a click/touch on the result icon opens the poi info pane where the "hide" button is available.

One option to resolve this issue is to add a mini menu when clicking/touching a coordinate search result icon with two buttons:
- hide
- add

**Comment by HarelM** [comment]
Search for something else...

**Comment by HarelM** [comment]
The result of this issue is due to #1228.
I have no plans to add a small menu in this case due to complexity and usage popularity.
I'll use this issue to clear the search results when the app and site start as they cause issues when editing OSM.
i.e:
1. Open the site
2. Search for anything
3. Close the site's tab in the browser
4. Surf to israelhiking.osm.org.il
5. Click edit OSM - it should edit the current location in the map but instead edits the last selected POI.
