### ISSUE TITLE
App fails to load due to bad layer

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1332]
## What I expect to happen
We should avoid as much as possible to get to the situation where the app doesn't load due to bad map share.

## What really happened
The app might look like it's not loading when in fact it does load, but gets error when trying to present a layer and the entire map doesn't show

## What I did that caused the issue - step by step
1. Received a share with a bad layer
2. Open the share
3. I'm not sure - Maybe close and open the app again.

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Things I think the developers should know, images, links etc.
After a phone conversation on the issue there are a few options to solve this:
1. Ask on every share you get which part of the share you would like to use - only maps, only route or both. the problem with this is that the issue affect small amount of users while this change will affect most of the users and this experience is not optimal.
2. Ask on every share you create if you would like to share the maps as well and default it to false - this will not solve the issue but might make it less common.
3. Add a trouble shooting section to the FAQ page - not sure it's a valid option since a user can't really get to it when the app doesn't work.
4. Not do anything and continue to support users who has issues.

**Comment by zstadler** [comment]
Another option:
5. By default, the share does not include any **private** map sources. A checkbox will be added to allow inclusion of **visible** map sources in the share. Selection of public layers/base map should be preserved.

I prefer this option because it is the least disrupting: 
- All existing flows are supported
- There are far more share receivers than share creators. The share receivers are not impacted
- The vast majority of shares do not intended to distribute private sources and they too are not impacted
- Distributors of map sources are few and knowledgeable. The extra checkbox is not a significant impact compared to the effort in defining a new map source.

**Comment by HarelM** [comment]
This is option 2 basically, I might not have written it well...
