### ISSUE TITLE
Unable to add GPX to my private tracks

### ISSUE THREAD

**Issue by galdanny** [IsraelHikingMap/Site#1338]
## Bug/Feature
(Delete the non-relevant)
IsraelHikingMap has changed - not friendly 
No easy "Open GPX" on the left
I go to user - my recordings
"הקובץ הועלה בהצלחה, יקח עוד קצת זמן עד שהוא יתווסף למסד הנתונים"..
I don't see it in my tracks 
## My environment
* Operating System and version: Win10
* Web Browser and version: Chrome latest

## Things I think the developers should know, images, links etc.
The previous version was so much clearer.
How do I add tracks to "private tracks" ??

**Comment by HarelM** [comment]
> IsraelHikingMap has changed - not friendly

This is just pure unkindness. We have ran a poll in our Facebook group and it seems like most users do not agree with you, also this is a free country, if you don't like it you are welcome to use another site...

> How do I add tracks to "private tracks" ??
You add tracks in the same way you did earlier, this hasn't changed :-)
Please attach the relevant file that doesn't work and we'll try to understand what went wrong.

**Comment by galdanny** [comment]
Hi Harel,
Thanks for your reply.
First , it is not the same, On the left hand side there was a "file open"
icon that disappeared (see screenshot)
If I want to just open few GPX file to see them together, possibly modify
them, what should I do ?
Normally they should appear in מסלולים פרטיים
[image: image.png]


If I press [image: image.png] then  [image: image.png]I get this
[image: image.png]
Uploading the attached GPX does nothing - they disappears after a while
[image: image.png]
Please advise..
Thanks,
Danny 054-4236266

**Comment by HarelM** [comment]
Hi Danny and thanks for getting back to me.
Unfortunately, due to github limitations it seems that the images were not attached to the issue.
You can use the link at the end of this mail to get to the site and either edit your comment or upload the images as a new comment.
Regarding your question:
All the functionally of the site is still available, the change is only cosmetic in terms of where things are now.
To open a file you should click the right upper menu (hamburger button) and choose "שיתוף - קבצים" - this is where you'll have all the open file button to select a file from the file system.

I hope this answers your question. please close this issue if it does or provide more information if it doesn't.

**Comment by galdanny** [comment]
Hi Again
*Latrun_Etan.gpx*  for example and any other GPX I have was
uploaded correctly about a week ago in the previous version
As you can see the on this icon track exists but it still say אין תגיות -
there are no timestamp tags , nevertheless they are not needed .
[image: image.png]
It opens OK any other places (https://www.gpsvisualizer.com for example)
[image: image.png]
Thanks,
Danny

**Comment by galdanny** [comment]
Hi Harel,
OK - file open I looked for was indeed  at שיתוף קבצים as you advised it also opened my GPX without timestamp error 
Thanks a lot !
Danny

**Comment by HarelM** [comment]
No problem, enjoy! :-)
