### ISSUE TITLE
Remove references to Raster Overlay tiles

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1343]
## Infrastructure
The Raster Overlay tiles are no longer used by the site. There is also no need to continue and serve these tiles for backward compatibility. Therefore, the related code can be removed.

**Comment by HarelM** [comment]
While I have no objection in theory to remove them we need to make sure this doesn't break old shares.
I don't mind breaking shares that are using an custum layer that has an address of the overlays (although I believe this will be rare if exists at all).
If you have an old share (from before March) that has an overlay turned on we should test that it uses the new overlay now (I think it should since I kept the same keys of the overlays and base maps so they should be used).
Other than that the only reference I can think of is in the `appsettings.*` files which can be removed right now as far as I'm concerned. You are welcome to do it. :-)

**Comment by zstadler** [comment]
Yes, old shares that that used the built-in base maps and overlays are using their vector versions now.

**Comment by HarelM** [comment]
Cool, so I don't see a reason not to progress with this.
Feel free to remove the entries from the appsetting files and remove them from the server as well.
Or let me know if you would like me to do it.
