### ISSUE TITLE
Indentation in Route form 

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1360]
The indentation of the route title and description changes when the opacity is changed.

Before:
![Screenshot_20201108-082857.jpg](https://user-images.githubusercontent.com/1304610/98458806-33593b00-219d-11eb-99b8-4477295a5e7d.jpg)

After:
![Screenshot_20201108-082939.jpg](https://user-images.githubusercontent.com/1304610/98458810-3bb17600-219d-11eb-9834-c11b8df8893c.jpg)

App version 9.6.7
Android 10

**Comment by HarelM** [comment]
Are you sure this is new to 9.6.7?
I think the problem is that the opacity slider is causing the text to move.
I think you can see it on the desktop version as well.
I have opened an issue for angular material a long time ago about this:
https://github.com/angular/components/issues/6959
I think I can probably change the sliders to be vertical and thus avoid this issue but the design of the window will be worse...
Maybe you can add a comment in the above link and they will fix it...

**Comment by HarelM** [comment]
Changed sliders to be vertical.
