### ISSUE TITLE
F.R Real time voice navigation

### ISSUE THREAD

**Issue by Yaniv125** [IsraelHikingMap/Site#1390]
Voice navigation will make it more easy to navigate,
with this user can hike with both hands without looking on there smartphone.

Hebrew voice navigation will be great bonus.

**Comment by HarelM** [comment]
I agree this would be ideal, but we do not have the required resources to implement this.
If this is something you would like to pursue it would be great :-)

**Comment by Yaniv125** [comment]
Is this help ?
https://www.graphhopper.com/blog/2019/02/05/building-a-navigation-app-using-open-source-tools/

**Comment by HarelM** [comment]
We are currently using graphhopper in the server side to get the routing for route planning that can be seen in the site.
We are currently disabling turn-by-turn instructions to save bandwidth.
Integrating this properly probably requires offline navigation since when not driving a car, most of the time you don't have cellular reception and that's a big effort to start with (you need to support both iOS and Android, and graphhopper ports for these platforms are relatively abandoned).
Implementing the turn-by-turn instruction is also not simple, and narrating the text is also complex.
As I said, it can be done but it's a huge effort which will not allow progressing other tasks.
If you would like to try and implement this go ahead, by all means, I can help in terms of guidance but I don't have the time to fully implement this...
