### ISSUE TITLE
Editing an uploded file become troublesome

### ISSUE THREAD

**Issue by mk4th** [IsraelHikingMap/Site#1396]
## Bug
When I'm uploading a file, if I move the start point, then the whole track is gone.
I need to fixate the track start point before editing.

## What I did that caused the issue - step by step
1.Upload a file
2. Go edit mode
(3). Click somewhere in the middle, it becomes the start point.
4. Move the start point, then the whole track is gone and it will reroute to the end point.

## My environment
Win7,
FF 78.5

**Comment by zstadler** [comment]
Thanks @mk4th for this issue report!

It looks like the issue is related to opening a GPS recording and it could be related to #1340 - the ability to read a GPX file without network connectivity.

## Things I think the developers should know, images, links etc.

Here is my understanding:
- The route presentation and editing assume that every route has at least two segments where the first segment has only one point - the start point.
- The new GPX read mechanism creates only one segment. Nevertheless, the map shows a green dot at the first point of the first segment and a red dot at the last point of the last segment:
  ![image](https://user-images.githubusercontent.com/1304610/102007832-ee449d80-3d34-11eb-8b85-5b00caffda43.png)
- When entering edit mode, the last point of the first segment is shown in green on the map. The map does not show a point at the beginning of the recording:
![image](https://user-images.githubusercontent.com/1304610/102007847-061c2180-3d35-11eb-91fa-6940140ce1d2.png)
- After the user creates a new intermediate point the route now has two segments. The green "start point" is now shown at the intermediate point - the last point of the first segment.
![image](https://user-images.githubusercontent.com/1304610/102007864-251ab380-3d35-11eb-9921-8b365e762b72.png)
- When the intermediate point is moved, like this:
![image](https://user-images.githubusercontent.com/1304610/102007971-049f2900-3d36-11eb-87d9-e56710077ea5.png)
the second segment is replaced by a newly-calculated route and the first segment includes only the new location of intermediate point. In the process, the start point of the original GPS file is discarded:
![image](https://user-images.githubusercontent.com/1304610/102007959-f0f3c280-3d35-11eb-9c94-94b260560ac1.png)

Here is the [recording GPX](https://www.openstreetmap.org/trace/3383766/data) used in the example above.
