### ISSUE TITLE
Periodic public POI update

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1403]
## What I expect to happen
The public POI list to be updated periodically

## What really happened
When the app is active for a long time, the public POI list is not updated.

## Things I think the developers should know, images, links etc.
Since the update of the POI list is incremental, the overhead of refreshing the list would be small.

**Comment by HarelM** [comment]
As a side note, refreshing the list has an unwanted effect of freezing the UI for 2-3 seconds, which I have no way to solve as far as I understand.
This is currently a bit annoying since it happens right after you open the app.
It might be worth considering of an optimal time to refresh the list as part of this issue, or at least notify the user that this is what's currently holding him from using the app...

**Comment by zstadler** [comment]
Could this update be done when the app is not in focus or when returning from the background?

**Comment by HarelM** [comment]
I'm not sure, this needs to be tested.
Returning from background would not improve the UX as far as I understand as you would see the app and then it will freeze, I think...
On the other hand, if this is done when moving to background it might help but I'm not sure it's possible and there's no way to know if the user will ever put the app in the background so relaying on it is shaky, IMO...
For the periodic updates, doing it when the app moves to the background might improve the situation if this is possible, but this won't solve the initial load... :-(
Having said that, this issue is only about periodic updates so the attempt to do it when moving to the background might be a good enough solution for this issue while we'll still need to solve the initial load UX in another way...
