### ISSUE TITLE
Public POI upload in slow network conditions

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1407]
Public POI upload will be handled in a separate issue according to priority I don't want to do a partial work as part of this issue.
Currently tracked in the topics to discuss...

_Originally posted by @HarelM in https://github.com/IsraelHikingMap/Site/issues/1401#issuecomment-749466011_

**Comment by HarelM** [comment]
As part of the effort to migrate from POI object to GeoJson object I have seen that I need to change the API for POI.
Which led me to think that I should also look into this issue and see if there's an API change that is needed for this too.
After thorough investigation of this issue and a post in the offline first slack the following is what I've learned:
https://medium.com/to-err-is-aaron/detect-network-failures-when-using-fetch-40a53d56e36?_branch_match_id=706010676983829160
And this SO question:
https://stackoverflow.com/questions/15159274/avoid-duplicate-posts-with-rest
Since client side ID is not possible when it comes to OSM entities the following is the protocol I need to see that work in all cases:
1. POST to create a temporary token in the server database
2. A PUT request with this token to update the entity and really add it to OSM

I'll write shortly all the relevant scenarios and see that the above protocol covers all cases.

**Comment by HarelM** [comment]
After another discussion on the matter the following should be possible:
1. Send a request with GUID when crating a new point and use the OSM id when updating
2. The server will store the GUID and make sure that if another request is sent with the same GUID the server will simply return OK without updating OSM
There's a need to make a queue to store the request in the client side.
The queue should retry when moving from offline to online and when loading the app
I need to think if the queue should retry every defined period of time.
The number of items or the fact that the queue is not empty should hopefully be reflected in the UI (user profile somewhere, might be similar to google photos in that matter).
The queue should retire items after a defined period of time, much like the server.
My hunch is that this time should be around 3 month, client and server should be aligned about that time to prevent issues.
I need to write down all the use cases and make sure everything is covered.
This approach is simpler than the above and thus there should be fewer scenarios to think about and test.

**Comment by HarelM** [comment]
Possible scenarios and expected outcomes:
1. Add point -> good connection -> point added to queue, sent to server and added to DB and OSM, GUID is saved in server side for x days and is never checked.
2. Add point -> poor connection -> point added to queue -> point arrived to server but client timed out -> GUID is saved in the server and point is added to db and OSM -> client tries to send it again and server ignores the request and sends back the point
3. Add point -> poor connection -> point added to queue -> point did not arrived to server -> client retries and succeeds.
4. Update point -> good connection -> point is added to queue, sent to server, updated db and OSM
5. Update point -> poor connection -> point is added to queue, point arrived to server but client timed out -> updated db and OSM, when clients sends this again it will do the same changes over again
6. Update point -> poor connection -> point is added to queue, point did not arrive to server and client timed out -> when clients retries it will update the server DB and OSM.

Still to implement:
- [ ] Split add and update in server side controller
- [ ] Add the ability to store the GUID in the database and delete it after a period of time
- [ ] Test the above scenarios
- [ ] Add expiration time for upload retires
- [ ] Add monitoring for connection changes to start retries
- [ ] Add queue indication in UI and allow (maybe) to force upload retry
- [ ] Add retries when app starts
- [ ] Delete cached object after success upload
