### ISSUE TITLE
Sharing using other apps

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1415]
##  Feature
The sharing dialog on the app currently allows sharing with WhatsApp, Facebook and Nakeb.
I would like to share using Telegram; others may prefer Instagram or Twitter or whatever.
Please consider using the system dialog for sharing, like you do for file saving, so that users can choose their favorite installed app for sharing their activity or trip plan.

**Comment by HarelM** [comment]
Can you please be more specific - where are the place which you want to change and use the social sharing?
Also please change the title of the issue accordingly.

**Comment by valleyofdawn** [comment]
Yes. I would like this dialog box
![Screenshot_20201229-154750_Israel Hiking Map](https://user-images.githubusercontent.com/689201/103288529-b785ad00-49ed-11eb-99b4-542f434165a2.jpg)
To look like this one:
![Screenshot_20201229-154847_Android System](https://user-images.githubusercontent.com/689201/103288549-c66c5f80-49ed-11eb-997d-411c97c28381.jpg)

**Comment by HarelM** [comment]
Sometime you just want to upload to the cloud and not share with others.
I'll change the lower part of the dialog once the share has been uploaded to the cloud in order to facilitate for easier share options instead of only the given options.
Having said that, currently you can simply copy the url using the copy to clipboard button, I agree that this UX is better.

**Comment by HarelM** [comment]
I haven't tested this at all - this needs testing.
I have added better sharing in the following places:
1. public POI
2. Shares dialog where you can see all your shares
3. Create share dialog, after the share is created
