### ISSUE TITLE
Migrate core site to Linux server

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1416]
## Infra
In order to facilitate for lighter needs for the site and the fact that the entire ecosystem for the vector tiles is running on Linux we want to move the site to run on Linux as well.
Things that we should take into consideration:
1. Use docker for the server that will run on Linux
2. Raster tiles will still be created on the windows server - we need to facilitate their availability after the migration.
2. Hourly/Daily Updates that currently run from task manager on windows will not work due to site limitations - the solution was to run a docker command to run `curl` inside the docker - this should be added/updated in the installation instructions as well.
3. Private information need to be placed inside that docker and make sure it is configured for production
4. Https should be handled outside the docker I guess and not inside it as it is now...?
5. Make sure CORS work
6. Populate the `.well-known` directory, if needed, and check that all related services are working well

I hope this covers everything...

**Comment by HarelM** [comment]
I've created the relevant build definitions in dockerhub to support a build on every commit for `latest` and use tags for versioning. The first latest version is there:
https://hub.docker.com/repository/docker/israelhikingmap/website
@zstadler can you try and see which of the above parts needs extra care (i.e. doesn't work and needs to be addressed by code changes)

**Comment by HarelM** [comment]
The following describes how to setup the certificate for https kestrel:
https://devblogs.microsoft.com/aspnet/configuring-https-in-asp-net-core-across-different-platforms/
I'm not sure I fully understood it, but it seems possible...

**Comment by HarelM** [comment]
I think I found the right tutorial:
https://www.programmingwithwolfgang.com/set-up-docker-compose-for-asp-net-core-3-1-microservices/
This tutorial is basically saying that you can define an environment variable to be used by kestrel to locate a certificate that is mounted into the docker container.
Assuming the certificate is generated and updated by a third party applications and it generates the certificate file all that needs to be done is make sure it writes the certificate file to the right place, I think.
I checked the code in the linked github of the tutorial and haven't seen any special code to load a certificate like is written in the link I attached in my previous comment. This leads me to believe that setting the environment variable for the certificate - i.e. `Kestrel__Certificates__Default__Path` and the other one is enough to support HTTPS inside the docker container.
There's still a question of course of how to configure the machine to redirect outside communication to the relevant docker container port.

**Comment by zstadler** [comment]
#### Tentative plan for docker containers
Some of the site components require scripts to run on the host. These scripts create and periodically update the vector tiles and the routing information.

The plan is to have a main docker-compose file that will include the on-going services:
- The web site
- The Graphhopper routing service
- The Elastic DB service
- The vector tile server

The update process of the vector tiles will run in a different docker-compose setup, similar to the current. However, the refresh command for the vector tile server should be modified to work across docker-compose projects.

The update process for Graphhopper could be run from the main project directory.

**Comment by HarelM** [comment]
Also there's the osmpbfwebapi which is currently not using the docker image due to latency issue we've seen in the "old" linux server - we need to see if this issue still exists in the new server and if not, add it to the docker-compose file.
This container holds the pbf file for the site and running the update is done as part of the site's rebuild process (Item 3 in the original list).

**Comment by zstadler** [comment]
My bad. The OSM-PBF service should be the 5'th member of the on-going services list. 
I suggest its update, like the other updates, will be initiated by the host.

**Comment by zstadler** [comment]
Updating the above list to include both `osmpbfwebapi` and `israelhikingmap/gpsbabelwebapi`

**Comment by zstadler** [comment]
Next set of tasks for @zstadler :
- [ ] Verify that the Graphhopper container uses of the IHM DEM
- [ ] Create the Linux equivalents of the Windows' Task Scheduler tasks related to the website
- [ ] Connect the vector tile update  service with the site while keeping their docker-compose configurations separate
- [ ] Try to use SMB instead of NFS for providing raster tiles from the Windows server to the Linux server

Following the above, assess the system readiness to run the production site from the Linux server.

A tentative transition plan:
1. Use IIS rewrite rules to redirect external HTTPS requests to the Linux server as HTTP and redirect external HTTP requests to HTTPS
2. Install Let's Encrypt on the Linux server
3. Change IIS rewrite rules to redirect external HTTPS requests to the Linux server as HTTPS and redirect external HTTP requests to HTTP
4. Move the Elasticsearch to the Linux server: 
   - User cloud saves (shares)
   - User private layers
5. Move the site's external IP address to the Linux server
6. Stop Elasticsearch and IIS services on the Windows server
7. Clean unnecessary files and directories on the Windows server

**Comment by HarelM** [comment]
Closing this as this is tracked elsewhere and the migration had been completed in general beside small things that will be addressed separately.
