### ISSUE TITLE
טיפוס מצטבר שגוי למסלול

### ISSUE THREAD

**Issue by inonah** [IsraelHikingMap/Site#1463]
<div dir="rtl">

העליתי מסלול לאתר וערכתי אותו, אך נראה לי שהטיפוס / ירידה מצטבר גבוהים מידי ביחס לחישוב באתרים אחרים . 
האם יש אפשרות לבצע חישוב מחדש של הטיפוס / ירידה המצטברים, על סמך מדדי הגובה במפה (DEM) ? (לא מצאתי אפשרות כזאת)
כמו כן מציע לסמן את המסלול בצבעים בהתאם לשיפועים במסלול . זה מסייע מאד בתכנון המסלול 

https://israelhiking.osm.org.il/share/PGkn5hehNR
</div>

**Comment by HarelM** [comment]
תכנון מסלול באתר מסתמך על נתוני גובה מדוייקים, אותם נתוני הגובה בהם אנו משתמשים לציור קווי הגובה כמו שניתן לראות בדוגמא הבאה:
![image](https://user-images.githubusercontent.com/3269297/112880123-b3435b80-90d2-11eb-96d2-a47076fe6bc4.png)
נתוני הגובה האלו הם נתוני מדידות לווין שטוייבו לטובת הפרוייקט והם באיכות מאוד גבוהה.
אם אתה עורך הקלטה אז לכל קטע שאתה משתמש במקטע מתוכנן הגובה ילקח מנתוני הגובה בשרת ולא מנתוני הג׳יפיאס.
בקטעים אחרים הגובה ילקח מההקלטה עצמה שהיא מאוד לא מדוייקת.
כמו שכתבתי בפייסבוק, כל אתר מחשב אחרת את נתוני העליות והירידות בהאתם לכל מיני מיצועים וכו׳.

לגבי הנקודה השניה, יש קריאה פתוחה על נושא הגובה בקריאה הבאה:
https://github.com/IsraelHikingMap/Site/issues/1337
אתה מוזמן לתרום מזמנך לפרוייקט ולכתוב את הפיצר הזה :-)

**Comment by HarelM** [comment]
@inonah יצא לך לבדוק את הנושא? אשמח לדעת מה לעשות עם הקריאה הזו...

**Comment by HarelM** [comment]
את נושא הצבע למסלול אני מניח שאני אוסיף בגרסה הקרובה בתקווה שזה לא יהיה מסובך מידי, כמו שניתן לראות בקריאה כבר יש לי אב טיפוס שעובד.
הייתה פעם אפשרות לאלץ את המסלול להיות מנותב מחדש אבל האופציה הזו לא הייתה בשימוש ולכן הורדנו אותה.
מה שיותר מעניין אותי להבין זה מעבר לעובדה שיש שוני האם אתה יכול למצוא מסלול קצר שמתוכננן באתר (לא מוקלט כמו שאמרתי כי ההקלטה לא אמינה) שיש בו בעיה בחישוב הגובה המצתבר ולאפיין מה המספר שהיית מצפה לקבל במקרה כזה ואז אוכל לחשוב איך לשפר את החישוב הקיים...
על פניו, אני לא מוצא כרגע בעיה עקרונית בחישוב ולכן בלי נתונים אמיתיים לא אוכל לטפל בבעיה.

**Comment by inonah** [comment]
היי הראל

*לאחרונה*, אני משתמש ב IHM, לתכנון ולשיתוף מסלולים.
במקרה הנדון, הורדתי את מסלול שביל הגולן לאופניים מאתר שביל נט
<http://www.shvilnet.net/maslulim-inner.asp?mtype=74&maslul=178#.YGW65q8zbIU>והעליתי
אותו לאתרים : ihm ,   alltrails ולאפליקציית oruxmaps.
אתר alltrails ,ידוע בכך שערך הגובה המצטבר  גבוה ביחס לאתרים אחרים .

הערכים טיפוס / ירידה מצטברים עבור המסלול הם :
oruxmaps = 1686 , -2981
alltrails </> = 1959
ihm <https://israelhiking.osm.org.il/share/ayu7lxW888>=2240, - 3540
ב orux , ביצעתי חישוב מחדש של הגובה על בסיס DEM

בנוסף, ערכתי את המסלול  ב IHM וחילקתי אותו לשני מקטעים
<https://israelhiking.osm.org.il/share/PGkn5hehNR> . ערך הטיפוס המצטבר
במקטע השני שהינו  50 ק"מ (כמחצית מאורך המסלול כולו), 1720 מ,  יותר גדול
מהערך של הטיפוס המצטבר של כל המסלול באורוקס.

שוב, אין לי מושג מהם הערכים הנכונים המשקפים את המציאות. אני משקף את הערכים
שקיבלתי באתרים

בברכה
ינון אהרוני
0502969188

**Comment by HarelM** [comment]
כמו שאמרתי, מסלול של 50 ק"מ הוא ארוך מידי כדי לעשות בדיקה כזו.
אני ממליץ לתכנן מסלול קצר ולראות את התוצאות.
בהנחה שקווי הגובה באתר הם נכונים ככל שאנחנו יודעים ואפשר לעשות ניסויים ולקבל תחושת ביטחון באשר למספרים...

**Comment by zstadler** [comment]
_TL;DR - A different simplification algorithm is better at eliminating spikes_

### Potential causes
I see two potential reasons for the differences:
1. The DEM data
2. The simplification method

### DEM
By using detailed 30-meter DEM data, it is more likely that the raw height data used in IHM introduces higher level of "noise" where small differences in height over a long trail contribute to totals of both the incline and decline.

Since we want consistency between the map and the height graphs, we need to take the detailed DEM as given.

### Simplification
Given that any DEM data creates some level of "noise", all applications are using some simplification algorithm. These simplification algorithms are similar, in a way, to the simplification done on complex geometries when zooming-out in a map. Many algorithms simplify the 

IHM is currently using the popular [Ramer–Douglas–Peucker (RDP) algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm). While working with PostGIS I sumbles upon the [Visvalingam–Whyatt (VW) algorithm](https://en.wikipedia.org/wiki/Visvalingam%E2%80%93Whyatt_algorithm) that could be more suitible for the height graph simplification

#### Algorithm comparision
Both algorithms simplify curves by eliminating less important nodes. The difference is in the definition of a node's importance.  

![image](https://user-images.githubusercontent.com/1304610/113308002-65b33280-930e-11eb-8eab-0fba2c1c2c71.png)

Consider the gray node above as a candidate for removal from a longer curve. Its importance according to the RDP algorithm is defined by the distance of the node from the blue line. Its importance according to the VW algorithm is defined by the area of the triangle. As a result, the RDP algorithm tends to preserve "spikes" while the VW algorithm tends to eliminate them.

According to [this stackoverflow answer](https://stackoverflow.com/a/12027097/368683), Mike Bostock, the creator of d3.js, wrote a tight javascript implementation of this algorithm. The source code is avaiable [here](https://bost.ocks.org/mike/simplify/simplify.js) and so is a [demo](https://bost.ocks.org/mike/simplify).

**Comment by zstadler** [comment]
<div dir="rtl">

> כמו שאמרתי, מסלול של 50 ק"מ הוא ארוך מידי כדי לעשות בדיקה כזו.
> אני ממליץ לתכנן מסלול קצר ולראות את התוצאות.
> בהנחה שקווי הגובה באתר הם נכונים ככל שאנחנו יודעים ואפשר לעשות ניסויים ולקבל תחושת ביטחון באשר למספרים...

הכנתי דוגמה מתוך אחד הקטעים היחסית מישוריים של המסלול המקורי
https://israelhiking.osm.org.il/share/lo8kuvq4XO

הפרש הגבהים בין נקודת ההתחלה לנקודת הסיום הוא כ-50 מטר. על פי IHM יש כאן עליה מצטברת של 56 מטר וירידה מצטברת של 7 מטר. מדובר על תוספת של כ-14%. 

- מעניין מה המספרים שיתנו האפליקציות האחרות. 
- מעניין גם מה קורה אם בוחרים קטע תלול יותר.

**Comment by inonah** [comment]
היי
אתה בטוח ?  המסלול במגמת ירידה . המסלול הפוך לכיוון  של המסלול  שהעלתי ל
ihm.
באורוקס , ערכי הט"מ של המסלול שערכת הם 6 עלייה , 62- ירידה

**Comment by HarelM** [comment]
This is a duplicate of #1413.
I haven't seen anything that had changed from the time it was closed to now.
Closing...
