### ISSUE TITLE
Remove POI download dialog

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1464]
## What I expect to happen
The initial download of POIs to be performed in the background without any user interaction

## What really happened
The confirmation dialog is not always clear to users.

It is also not clear that the amount of data potentially downloaded over a celluylar connection justifies the user interaction - conformation + progress tracking

**Comment by HarelM** [comment]
While I agree on the approach I'm not sure what should be the right technical solution here:
Current implementation:
Since initial download (the user does not have any POIs stored on his device) is large and we do not want to stress the server's database there's a POI file created every day to allow downloading of this file (~100MB).
After the file is downloaded and get stored into the app's database the app performs incremental updates of 3 day at a time.

Problems:
If the file is not fully downloaded or the database storage is not performed the user will not have offline POIs capabilities and the download of the file will need to begin from scratch - this can happen if the user does not keep the app open for the entire process of download and DB storage - which I believe is a lot more likely to happen in the new UX.

Thoughts are welcome, probably better if we discuss this on the phone...

**Comment by HarelM** [comment]
Phone conversation summary:
1. Remove progress dialog and use regular progress
2. Try and reduce hang time when application starts
3. Download offline POIs file to cache to allow recovery if the file was downloaded but the app stoped afterwards
