### ISSUE TITLE
Add a tutorial for new users

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1467]
## Feature
As a user who just installed the app / came to the site for the first time, I would like to know what the site/app offers is a simple and summarized manor much like other app are presenting.
I would also like to be able to get back to this tutorial at any given time.

There's a need to define this landing-page-tutorial to achieve both the effect of explaining to the user what he can do and both let him know there are things he can buy I guess.
I don't have a good vision of what I want to do here yet...

**Comment by zstadler** [comment]
As part of the indroduction to new users, I would also like the user to take responsibility for using the map.

The following text, taken from the minefields announcement, can serve as a basis for a more general statement:

<div dir="rtl">
<blockquote>
חשוב לזכור ששום מפה אינה מדוייקת. גם אם המפה מראה אחרת, אסור בשום אופן להתעלם משלטים, גדרות או מוקשים שקיימים בשטח!!!
</blockquote>
</div>

Currently, users approve the term of use only if they register and login.

**Comment by HarelM** [comment]
@arielhasidim would you like to help out with this one?

**Comment by arielhasidim** [comment]
I can help creating the artwork and creating a dialog with multi pages at swipe. What is the 3-5 main features that we should introduce?

BTW - by my experience, user agreements should be asked to be approved by **every user** after instalment until he does (you can cache this). Otherwise you are being subjected to unwanted liability...

**Comment by HarelM** [comment]
From the top of my head
1. Route planning and sharing
2. Offline and online Maps, points of interest, public routes, custom base maps and overlays
3. Route statistics, height, slope, gain, loss, eta
4. Search (?)

Basically the main menu first few items.
Also there's probably a need to let the user know he should click the crosshair icon to activate GPS...?

Feel free to suggest, I'm guessing that basic most common functionality should be covered here... Maybe the last slide should list some advanced functionality, I don't know...

Whatever you think would help a new user on his first encounter :-)

**Comment by arielhasidim** [comment]
Okay, that's a good start. I'll try to think how it can be grouped properly because too much is also no good.

Also, animation can make a big difference with user understanding, maybe some one who knows "After-Effect" can help make [lottie](https://lottiefiles.com) animations that can be [integrated in angular](https://github.com/ngx-lottie/ngx-lottie).

**Comment by HarelM** [comment]
I'll post a message in our Facebook group to see if anyone is interested to help with animation, or join this discussion in general...

**Comment by hesher** [comment]
Just an opinion from a user with UX experience - The page is clean and looks great. 
I haven't used the site in a while (since I don't line in Israel) and was surprised to see that the button bar disappeared.

While it's nice that it cleans up the page, it actually requires the user several more clicks to edit tracks, share them, etc...

I would have surfaced the most common actions (do you have logging?) to be accessible without having to click the "hamburger" button.

**Comment by HarelM** [comment]
@hesher thanks for the input! 
This feature is more about the first entrance and impression to the app of a new user who is not familiar with the app or site - some way to convey the main functionalities.
Related to what you said are the following issues: #1358, #1324 but I would like to separate the discussion about them to their own threads.

**Comment by EdoGeron** [comment]
@HarelM  - what do you think about having some sort of in app video tutorial?
In case the features in question are simple enough to be "caught" in a less then 1 minute video embedding it on your welcome tutorial might be more efficient then written one. You can also brake down into several clips and have a wizard like welcome dialog so that the user can focus on the features he would like to understand.

**Comment by HarelM** [comment]
As can be read in the comments to the Facebook post I think it is great idea, but I believe this "in-app-few-swipes-tutorial" is still needed as for some people videos are less helpful.
Nevertheless, video tutorials are needed to better support our FAQ page which has limited videos in it...

**Comment by HarelM** [comment]
Here's how I see it:
Every "page" should be with a header, description and image.
Page 1:
Header: Language - שפה
Description: radio button of languages - Select language from a radio button style form to allow the next messages and the site/app to be language specific
Image: Need something related to language I guess...
Page 2:
### עקיבה
הצגת המיקום הנוכחי ע״י לחיצה על מקש הכוונת
crosshair and GPS icon image...?
Page 3: 
### מפות
מפת טיולים, מפת אופניים וצילומי לווין. ניתן לרכוש מפות לשימוש לא מקוון דרך התפריט של מסלולים - מפות - שכבות
Offline and map image/icons...?
Page 4:
### מסלולים ונקודות
ניתן לתכנן ולשתף מסלולים, לצפות ולסנן נקודות עניין ולראות סטטיסטיקה של עליות, ירידות ומה שביניהן
Route on map with private and public POIs image...?
Page 5:
### ועוד המון!
סרטוני הדרכה, תשובות לשאלות נפוצות, מקרא, קבוצת פייסבוק ועוד נמצאים תחת אודות
Some happy image of some sort...? Facebook/Youtube icons?

**Comment by HarelM** [comment]
Phone call summary - remove slide 2 about GPS tracking and simply start tracking on the first time a user opens the app (only the app, don't do it for desktop users).

**Comment by HarelM** [comment]
Initial UX, I placed a default image just to get this going - the images should change and be higher:
![image](https://user-images.githubusercontent.com/3269297/130518506-40362f6f-1316-4942-b10c-771332ea4e4f.png)
![image](https://user-images.githubusercontent.com/3269297/130518523-d7b34af0-6a26-44cb-a876-b2e15c4fcf3a.png)
![image](https://user-images.githubusercontent.com/3269297/130518542-56570df8-9cfa-4b3f-a566-a3d42b2db7dc.png)
![image](https://user-images.githubusercontent.com/3269297/130518570-fe973aa2-e6d2-4dfa-b3f1-46e78a9c31c1.png)
