### ISSUE TITLE
נקודה במפה לפי גרף גבהים

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#1469]
אינני יודע אם זה באג או לא אבל הייתי שמח שברגע שאני פותח גרף גבהים הנקודה איתה אני רוצה לטייל על המסלול הייתה נשאת כל הזמו כרגע אם אני סוטה ממנה עם העכבר ממש מעט אני לא מסוגל להזיז אותה ולראות את הגרף משתנה
![3](https://user-images.githubusercontent.com/43242549/113500261-2e6a9e80-9525-11eb-9c69-3f33a72380e6.jpg)
![4](https://user-images.githubusercontent.com/43242549/113500263-33c7e900-9525-11eb-9a96-742d008d0242.jpg)

**Comment by zstadler** [comment]
Summary of phone discussion with @onzd :

The request is to tripple or double the maximal distance of the mouse from the route where a dot is placed on the route and on the height graph. The goal is to reduce the required mouse accuracy for using this interaction.

**Comment by HarelM** [comment]
הבעיה מוכרת לי והיא נובעת מהתשתית. לצערי לא הצלחתי למצוא לזה פתרון הולם. ניתן להעביר את העכבר על גרף הגבהים ולראות את הנקודה על המסלול.

**Comment by onzd** [comment]
סבבה אני אכן משתמש כך
תודה

בתאריך יום א׳, 4 באפר' 2021, 10:34, מאת Harel M ***@***.***>:

**Comment by HarelM** [comment]
The only thing I could find in order to solve this is the following SO question:
https://stackoverflow.com/questions/51039362/popup-for-a-line-in-mapbox-gl-js-requires-padding-or-approximate-mouse-over
This would create an overhead of lines, event and complexity which I don't believe have a good ROI.
Regretfully, I believe this feature should not be implemented, sorry...
