### ISSUE TITLE
Inconsistent cloud-save thumbnails

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1514]
## What I expect to happen
The thumbnail of a cloud save should look the same before and after clicking the save button

## What really happened
The post-save thumbnail shows just one of the saved routes

## What I did that caused the issue - step by step
- Create a save with two routes, such as https://israelhiking.osm.org.il/share/WjF9KrE2aX
- Before creating or updating the save, the thumbnail shows elements of both routes
   ![Before](https://user-images.githubusercontent.com/1304610/119011816-15fff780-b99e-11eb-9dbd-00af511958c6.png)
- After the save, the thumbnail shows only elements of the first route
   ![After](https://user-images.githubusercontent.com/1304610/119011525-d20cf280-b99d-11eb-965c-ca6441014000.png)

## My environment
* Operating System and version: Win 10 Pro
* Web Browser and version: Firefox 88.0.1 (64-bit)

## Things I think the developers should know, images, links etc.
The cloud-saves list seems to show both routes, but it is hard to tell with this example
![image](https://user-images.githubusercontent.com/1304610/119012218-80b13300-b99e-11eb-9342-2ad1d4b96d14.png)

**Comment by HarelM** [comment]
I'm unable to reproduce this with my chrome browser (both create and update are showing the right results).
I have checked the code in the server side and it always create the image from all the routes.
Here's what I believe caused this:
The image you see after you save (the "partial" image") is an image the browser cached, which I don't think I have control over.
While there are probably ways to solve this, I believe this is an edge case which does not worth the effort.
If you can reproduce it on chrome for a newly created cloud save (i.e. not firefox as less than 2% use firefox and not on an update as very few users update their cloud saves) I'll be interested in solving this, otherwise I don't think it's worth the effort...

**Comment by zstadler** [comment]
I agree. It's not worth the effort.
