### ISSUE TITLE
Search for Nature Reserves, National Parks, and Forests

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#153]
Following the important inclusion of trails in search - #132,
I'd like to suggest adding Nature Reserves, National Parks, and Forests to the search.

**Comment by HarelM** [comment]
Can you find something that is not searchable from the above? and you can find it using Nominatim or overpass relation search?

**Comment by zstadler** [comment]
1. If you search for "שמורת טבע", you currently get 5 results while there are more than a hundred Nature Reserves. Searching for "שמורת טבע מצוק הצינים" yields nothing. It seems like Nominatim does not handle names for boundary=protected_area. For some reason, the several Nature Reserves that have multipolygon relations are also not found.
[This overpass-turbo search](http://overpass-turbo.eu/s/fdN) currently shows there are 408 ways and 22 relations with "שמורת טבע" in their name.

2. Searching for "גן לאומי" shows 1 node, 1 way and 2 relations out of [90 ways, 3 relations](http://overpass-turbo.eu/s/fdO) and [6 nodes](http://overpass-turbo.eu/s/fdP)

3. Search for "יער' shows nothing. Yet there are [4316 ways, 284 relations](http://overpass-turbo.eu/s/fdR) and [90 nodes](http://overpass-turbo.eu/s/fdQ).

Points to consider: 
A. Using overpass-turbo to search on ways could be slow and result in large data sets, such as 4000 forest ways

B. Rendering the boundaries of Nature Reserves, National Parks, and Forests needs to take into consideration the nature of mulipolygons. For example, searching for
"גן לאומי סביב חומות ירושלים העתיקה"
shows 2 results. One for the inner boundary - the wall itself, and another for the outer boundary. Both results are probably from Nominatim, not from Overpass-Turbo.

**Comment by HarelM** [comment]
Current issue is with mulipolygons, I think the current OSM to geojson converter is ignoring them, I'll take another look at the code.
Current implementation is as follow: Get first 5 results from nominatim which should return ways and nodes, get relations from overpass - as many as there is.
You can look at the load time, it takes about 5-10 secs to get the relations, which is too much already so I'm not planning on adding more to the overpass search - since it searches the entire country.
We can think of a way to create a local database on the server to hold names for search but it's not a minor task.
If you have a linux server somewhere maybe we can setup a local nominatim server on it with all the relevant info including relations, ways and nodes, although I haven't fully study it...

**Comment by zstadler** [comment]
I now see why there are only 5 nature reserve results. Personally, I think 5 is too few. I would also like to see an indication or a button to show more.

I don't understand why IHM does not find "שמורת טבע מצוק הצינים" while the [nominatim.openstreetmap.org finds it](https://nominatim.openstreetmap.org/search.php?q=%D7%A9%D7%9E%D7%95%D7%A8%D7%AA+%D7%98%D7%91%D7%A2+%D7%9E%D7%A6%D7%95%D7%A7+%D7%94%D7%A6%D7%99%D7%A0%D7%99%D7%9D&polygon=1&viewbox=)

On the other hand, [nominatim.openstreetmap.org ](https://nominatim.openstreetmap.org/search.php?q=%D7%92%D7%9F+%D7%9C%D7%90%D7%95%D7%9E%D7%99+%D7%A1%D7%91%D7%99%D7%91+%D7%97%D7%95%D7%9E%D7%95%D7%AA+%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D+%D7%94%D7%A2%D7%AA%D7%99%D7%A7%D7%94&polygon=1&viewbox=) finds only the inner way of "גן לאומי סביב חומות ירושלים העתיקה" while IHM finds the two of them. I've opened issue twain47/Nominatim#414 for that.

As for a local DB, we already update the Israel pbf on a bi-/daily basis. It should be easy to extract any data we need out of it in practically any format we want.

**Comment by zstadler** [comment]
http://wiki.openstreetmap.org/wiki/Osm2pgsql may be a good start. It is also the basis for Nominatim

**Comment by HarelM** [comment]
Was implemented as part of #132.

**Comment by zstadler** [comment]
IHM still does not find "שמורת טבע מצוק הצינים":

![2016-03-29 09_28_38-israel hiking map](https://cloud.githubusercontent.com/assets/1304610/14099901/152da404-f592-11e5-9b62-2c55840aeb18.png)

It is also unclear how do 8 of the 10 search results relate to the search term.

**Comment by HarelM** [comment]
This is partially due to bad mapping and incorrect search order:
The reservation is a node and not an area or relation, so it's not voted up. the spring is not in the initial list you sent.
See the following file that sets sort order:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/GeoJsonFeatureHelper.cs.
Let's focus the search issues in issue #132, I don't see it as a special case, just poor luck...

**Comment by zstadler** [comment]
I don't see this as a matter of luck or prioritization. It is simply a bug. 

The "שמורת טבע מצוק הצינים" Nature reserve name appears on a [relation 6076947](http://www.openstreetmap.org/relation/6076947) and the two ways that belong to it. As I wrote above, the nomatim search above finds all 3.

I didn't understand the comment about "the spring"...

**Comment by HarelM** [comment]
Ignore the comment about the spring.
There are two bugs here: 
1. Conversion from OSM to GeoJson had a bug, now fixed.
2. The multipolygon you created is invalid as you did not declare the two related ways as outer role.
see [here](http://wiki.openstreetmap.org/wiki/Relation:multipolygon) section "Two disjunct outer rings".
