### ISSUE TITLE
Zoom in on height profile sections

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1540]
As a user of the app for bicycle navigation I most often ride with the height profile open.
This allows me to anticipate the upcoming ascents and descents.
The strategy works well for short routes (up to ~30km) but fails at long ones.
In long routes the local height variations are masked by the longer trends.
I would like to zoom in to the local height profile.

I suggest that resizing the height profiles (by pinching in and out) would zoom in on the local section.
Zooming in should affect the **x axis only**, and within the new x limits the profile should behave as it does now i.e. **use the max height and min height within the new x limits to set the y axis**.
The profile should remain as it is until the user zooms out.

![image](https://user-images.githubusercontent.com/689201/122751005-e5122b80-d297-11eb-8263-fd61e03d88bd.png)

related to issue #629

**Comment by HarelM** [comment]
Seems like the library that should facilitate for this is not working well, I don't understand why.
See issue here: https://github.com/d3/d3-zoom/issues/32
Proposed solution after re-thinking it - something similar to this:
https://www.d3-graph-gallery.com/graph/line_brushZoom.html
Reasoning:
Both are basically doing the same - concentrating on part of the chart.
So instead of just highlighting and zooming in two different ways the above example does it using a unified experience.
The only thing that is missing in the example above is a "reset zoom" button.
Also there might be a need to show the statistics on the desktop version below the chart instead of the current UX since desktop has more real-estate...

As a side note, there's a d3 module for selecting a part of the chart:
https://github.com/d3/d3-brush
Which might allow simplifying the current code since it does basically what I implemented...

**Comment by valleyofdawn** [comment]
Sorry for the delayed response.
Dragging and double-tapping instead of pinching in and out would be a good solution for me personally.
I am afraid though that it is non-intuitive and that people would get stuck in the zoomed-in state without knowing how to zoom out.
If implemented it should replace the current solution for getting stats for part of the route (which currently darkens the selected section).
Please not that the example you provided at:
https://www.d3-graph-gallery.com/graph/line_brushZoom.html
zooms in the X axis but doesn't rescale the Y axis, making it only a partial solution for us.

**Comment by HarelM** [comment]
Well, you can't pitch-zoom on the desktop, so making two different gestures is less ideal in terms of learning the platform once. We can use the scroll on desktop but I think it's even less intuitive.
Double tap to reset is just bad UX. I plan to add reset button on the chart or next to it when zoomed in to reset.
Maintaining two different gestures for mobile and desktop is probably ideal but the ROI is too small. The chart it self is already very complicated and adding more complexity is not advised.

**Comment by Tsurha** [comment]
<div dir="rtl">

הצורך שגיא מתאר לגמרי קיים באופניים. גם מחשבי האופניים השונים מממשים אותו בצורות שונות.  כיוון שלא הבנתי את כל פרטי הדיון. נוכל לשוחח טלפונית בהמשך היום.  

המיקוד שלי הוא לא תוך כדי רכיבה מסיבות של סוללה. חייב להשאיר את הטלפון בכיס לגמרי טעון, למקרי חירום עם הקבוצה. אני משתמש בעיקר ככלי תכנון במסך גדול. אבל גם בתכנון יש לגמרי משמעות לדעת אם תפרתי קטעי שיפוע מוגזמים. ככה שהזום יעזור. 

אולי דיברתם על זה או שזה ממומש כבר אבל צריך גם:
*  בגרף להציג נקודת אני כאן כרגע. גם בזום וגם בריסט
* כשעושים זום לגרף להציג על המפה את המקטע שהגרף מציג.

**Comment by HarelM** [comment]
יש נקודה שמראה את המיקום הנוכחי כבר היום.
השאלה פה היא לא על הצורך אלא על האיפיון.
אני ממליץ לטובת היכרות עם היכולות להתקין את האפליקציה ולצאת למכולת השכונתית ברגל - כך תוכל לראות מה ממומש בזמן עקיבה, הקלטה וכו'.
על מנת לקיים דיון פרודוקטיבי יש להכיר את כל אופני השימוש בגרף הגבהים, כולל דרך האפליקציה.
