### ISSUE TITLE
Auto-Routing outside Israel

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#155]
Please consider out-sourced routing outside the boundaries of Israel.

**Comment by HarelM** [comment]
Note that our main focus is to provide our map with our site and not just have users come to our site in order to do stuff with maps that are not ours, therefore this feature is considered low in our priorities list. I do see the added value of users that will get used to using our site and use it more which eventually will make the site and the map better.

**Comment by HarelM** [comment]
I don't see a good reason to implement it now with all the routing profiles we have. Also, routing logic is complicated enough without adding edge cases where the routing is outside Israel.
If you need routing outside israel, use another site like openstreetmap, brouter etc, these sites have a routing engine for the entire world just for this.
