### ISSUE TITLE
Problem in Height graph when sharing trail by link

### ISSUE THREAD

**Issue by ErezNahoum** [IsraelHikingMap/Site#1554]
## What I expect to happen

Design a rout, send a link to friend, when he open the link the rout displayed on the map with Height graph
## What really happened

Design a route, send a link to friend, when he open the link the route
 displayed on the map with corrupts Height graph.
(when opening the file with IHM web the Height graph is OK)

[מוצא צובה עין רפא עין נקופה בור עזיז חלילים מקלף.txt](https://github.com/IsraelHikingMap/Site/files/6839343/default.txt)

## What I did that caused the issue - step by step
Design a route, send a link to friend,

## My environment
* Operating System and version:
* Web Browser and version:
Chrome
## Things I think the developers should know, images, links etc.

Link:
https://israelhiking.osm.org.il/share/Kg9BDTiW7y

Attached gpx (change to txt)

**Comment by zstadler** [comment]
Thanks @ErezNahoum for the feature request.

Please
- Add a screen shot of how opening this link looks for you
- Explain what you would like to change in this screenshot

**Comment by ErezNahoum** [comment]
![Using link](https://user-images.githubusercontent.com/51607381/126134301-1b73b8ee-3672-448f-a20c-39fda299ebd8.JPG)
![Using file](https://user-images.githubusercontent.com/51607381/126134440-f570e6b0-942c-4594-a046-9d422c0d7396.JPG)

**Comment by zstadler** [comment]
## What I did that caused the issue - step by step

1. Download [this file](https://github.com/IsraelHikingMap/Site/files/6839343/default.txt).
2. Rename it to `default.gpx`.
3. Open the file in the app/site.
4. Check the height graph and see that it looks smooth.
5. Create a share for the map.
6. Open the share.
7. Check that the height graph has elevation drops.
8. Export a GPS file from the shared route.
9. Open the exported GPX file in the app/site.
10. Check the height graph and see that it looks smooth.

### Things I think the developers should know, images, links etc.

The GPX file has several `trkpt`s without elevation data

```
      <trkpt lat="31.77447642884747" lon="35.1482057703983"></trkpt>
      <trkpt lat="31.774559185046602" lon="35.14230832284101"></trkpt>
      <trkpt lat="31.778275360719334" lon="35.1346787392234"></trkpt>
      <trkpt lat="31.779523523445356" lon="35.129888952186306"></trkpt>
      <trkpt lat="31.779523523445356" lon="35.129888952186306"></trkpt>
      <trkpt lat="31.78306208611814" lon="35.12332572372999"></trkpt>
      <trkpt lat="31.78335948221992" lon="35.122651780787834"></trkpt>
      <trkpt lat="31.783593943590148" lon="35.12223074780485"></trkpt>
      <trkpt lat="31.783580000000004" lon="35.122220000000006"></trkpt>
      <trkpt lat="31.78423917052577" lon="35.115775931431564"></trkpt>
      <trkpt lat="31.7842427326312" lon="35.11579736953589"></trkpt>
      <trkpt lat="31.784116250903715" lon="35.11460993711947"></trkpt>
      <trkpt lat="31.784569356400894" lon="35.11348367435385"></trkpt>
      <trkpt lat="31.806872010077047" lon="35.1491371834972"></trkpt>
      <trkpt lat="31.806305247378425" lon="35.156149252831305"></trkpt>
```

**Comment by HarelM** [comment]
@zstadler thanks for the reproduction!
Can you share the link to the problematic cloud save? (or check the following in it)
If I open the cloud save in the first comment I get that some elevation values are `null` which indicate the issue is probably in the UI.
See the following data of the cloud save: https://israelhiking.osm.org.il/api/urls/Kg9BDTiW7y

**Comment by HarelM** [comment]
Probably related to the following line of code as `isNaN(null)` is `false` which is probably what's causing this... https://github.com/IsraelHikingMap/Site/blob/9fd1c3bcb0917fee789588a3f07779afd1b4a4cd/IsraelHiking.Web/src/application/services/route-statistics.service.ts#L67
I'll test it out locally to see if changing this condition will solve the issue...
I need to see that if I change this it won't affect the ability to calculate a route length even if it doesn't have height value that can happen when trying to plan a route offline (straight lines)...

**Comment by ErezNahoum** [comment]
Hi,

**Comment by zstadler** [comment]
Hello Erez,

We are still investigating this report.

As far as we currently know, the problems starts when a GPX is imported to the site or app and some points in the GPX do not have an elevation. At the end of the import, the height graph looks smooth. This is probably because the points without elevation are ignored. When the route is saved and shared, the points without elevation are no longer ignored and they show on the height graph.

As far as we know all of the points in a route planned on IHM have valid heights. Please let us know if you have created this route personally by planning it in IHM, or it came from a different source.

**Comment by ErezNahoum** [comment]
Hi,

Thanks for your replay
I planed it in IHM.

**Comment by zstadler** [comment]
@ErezNahoum,

Could you please record a video showing how you plan a route in IHM and end-up with the strange height graph?
**I'll be very interested to understand how you planned in in IHM without any import.**

Here are some interesting aspects of the route that may indicate it is based on an imported recording and not planned from scratch on IHM:

1. On the west of Zova, between the two pink arrows, there is a good looking route where the IHM map has no path and the route has no "straight line routing" points.
  ![image](https://user-images.githubusercontent.com/1304610/126194721-7b41f4ea-270c-48af-b412-dc9dc3c10bca.png)

2. At the approximate location of the red arrow above, you could see this when zooming-in:
  ![image](https://user-images.githubusercontent.com/1304610/126194932-631f032d-05f7-4f95-b6b3-3de6dc35dfe0.png)
  - The route has a small "z" shape, about 2 meters in length, which is typical for GPS recording
  - The turn of the route does not follow the exact location of the junction

**Comment by ErezNahoum** [comment]
Hi,

Yes, you right the trail is combination of three Strava records that I cut
peaces from them and connect the peaces with bicycle or straight line.

**Comment by zstadler** [comment]
Thanks for the clarification. 

I don't use Strava much, so please forgive my ignorance.

- Did you create these Strava records?
- If yes, how did you record them?
- If no, do you know who recorded them?

**Comment by HarelM** [comment]
This is probably the same as #1543
FYI @ronhl

**Comment by ErezNahoum** [comment]
Hi,

Please find the records that I use (pieces of them) to create the trail.
The sources is Strava:
Strava can record activity using smart-phone or import from activity from
sport-watch (such as Garmin)
I'm not sure how the attached trails were recorded.

Best regards,
Erez

**Comment by zstadler** [comment]
@ErezNahoum,

Any mail attachments are lost when replying to GitHub.

Please create a zip file for the tracks, open https://github.com/IsraelHikingMap/Site/issues/1554 and add the zip file to a new comment.

**Comment by ErezNahoum** [comment]
[gpx.zip](https://github.com/IsraelHikingMap/Site/files/6853204/gpx.zip)
@zstadler 
Hi,
Please find attached  the records (gpx files) that I use (pieces of them) to create the trail. (rar file)

**Comment by zstadler** [comment]
Thanks @ErezNahoum !

We are making progress towards the source of the missing elevation. However, all of the point in the GPX files you've sent do have elevation data.

The missing points in the original issue are located in the section covered by `2.gpx`:

![image](https://user-images.githubusercontent.com/1304610/126444191-5f1c3a46-2bba-41e1-be21-e16f2617eba6.png)

As far as I can tell, `2.gpx` is not the same as the gpx file you imported for planning the route. 

This is the most eastern point in the planned route that has no elevation:

![image](https://user-images.githubusercontent.com/1304610/126444623-7b2a571a-0225-4c76-9ea7-e9099e787571.png)

It looks like a u-turn after taking a wrong turn in the junction that does not happen in `2.gpx`:

![image](https://user-images.githubusercontent.com/1304610/126444720-943ed3e1-0279-4396-95c2-15a608856f86.png)

Does this u-turn remind you of any ride you've recorded?
Could you try and find similar GPX file/s you may have used instead of `2.gpx`?
Perhaps they'll help  us figure-out the source of the missing elevation.

Note: It looks like several of the points without elevation coincide with pauses in the ride, much like the above u-turn. For example:
![image](https://user-images.githubusercontent.com/1304610/126447458-9df96d26-a3cf-4737-a9a6-a24d5efb1d33.png) ![image](https://user-images.githubusercontent.com/1304610/126447053-1ede71a6-279c-4956-ab19-8da5bb623f73.png) ![image](https://user-images.githubusercontent.com/1304610/126447134-892ac321-df5d-4a6c-87e3-a381df5956e6.png) ![image](https://user-images.githubusercontent.com/1304610/126447278-56b08a4b-e3f6-4ca1-96c2-d7eba19d1112.png)

**Comment by ErezNahoum** [comment]
[elev drop.docx](https://github.com/IsraelHikingMap/Site/files/6854219/elev.drop.docx)
Hi,

Please find attached word document that show the steps to create the problem, base on 2.gpx.  The problem is due to U-turn that created due to cutting point and continue routing from that point.

**Comment by zstadler** [comment]
Thanks @ErezNahoum for reproducing the creation of the empty elevation points!
