### ISSUE TITLE
Missing ability to unify two POIs of the same place

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1572]
## What I expect to happen
Either:
* To see one train station where one exists 
* To have an ability to unify them into one with the best info from both
* To have an ability delete one

## What really happened
Two POIs show
![image](https://user-images.githubusercontent.com/49042192/129523260-cfd34805-397a-4a61-b498-274ecb286481.png)

Only one appears in OSM and it can't be deleted as it has a wikidata tag. 
![OSM](https://user-images.githubusercontent.com/49042192/129524208-1e622d5a-2542-4071-b551-bfa84d9d291c.png)

**Comment by HarelM** [comment]
Please, please, please add a link when opening an issue...

**Comment by HarelM** [comment]
In order to merge two points there are two ways:
My favorite:
1. Open the wikipedia POI (one that does not have a link to OSM website below)
2. Click on the title to go to the wikipedia page and copy the address
3. Click on the OSM POI
4. Click edit (pencil button)
5. Add another line of address
6. Save
7. Wait an hour and you'll see the link in the OSM POI and the wikipedia link in OSM editor
Second way (more complex but can also work for non wikipedia POIs such as iNature):
Go to OSM editor and add a tag either `alt_name` or `name:en#` with the name of the POI that you would like to merge.

In any case, this is implemented.
