### ISSUE TITLE
Enhance "Report an issue" in a browser

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1585]
## What I expect to happen
When using "Menu -> Report an issue" in a browser, I would like the developers to receive a report with as much information possible as when using the app.

## What really happened
Report an issue in a browser opens "New issue" page on GitHub without any log or other data.

## Things I think the developers should know, images, links etc.
See #1584 as an extreme example for lack of information

**Comment by HarelM** [comment]
I've looked into it and I can't find a good and easy solution:
Mailto protocol doesn't support attachments.
Sending all the data in the body of the mail can lead to not sending the mail since it looks alarming.
Allowing the user to download files and then instructing him to attach the downloaded file may work, but simpler request to describe the issue in our app main works poorly already, so I have very little confidence this will work well.
The solution describes in most cases is upload the files to the server and adding a link to them in the mail itself, it's possible to implement this but it's a big effort which I don't see a good ROI - very few people actually report an issue for this to justify the complexity of uploading files to server etc.

While all solutions do not seem good to me, the current solution is even worse.
I tend to go with instructing the user to download files and attach them, if he doesn't, at least we can continue communication via mail and instruct him to send the relevant files.

@zstadler what do you think?

**Comment by HarelM** [comment]
I had another thought about this - if when clicking this button a zip file will be downloaded automatically and then a dialog will popup with explanation what needs to be done with the file that was just downloaded it could be a relatively good solution to this UX problem.

**Comment by zstadler** [comment]
In the browser, this explanation could be added to current text and used as the body in the `mailto:` URI.

BTW, [the RFC](https://datatracker.ietf.org/doc/html/rfc6068#section-5) says:
> Also note that line breaks in the body of a message MUST be encoded with "%0D%0A".

**Comment by HarelM** [comment]
The following is the final dialog.
It download a file just before the dialog opens.
Clicking the button opens up a mail client depending on OS etc, which I'm not sure is configured for all users and that's why the instructions are a bit vague:
![image](https://user-images.githubusercontent.com/3269297/135714149-d5faab73-5070-401d-8266-0984ed917098.png)
Text can always be changed via Zanata :-)
I'm fine with the current one.
