### ISSUE TITLE
Add an ability to reset the permanent storage

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1595]
## What I expect to happen
As a support person, I would like to be able to give simple directions to a user that will reset the permanent storage in the app or the browser.

## What really happened
- The storage can be erase on Android and in the browser, using non-trivial instructions. I have no idea if and how this can be done on iOS.
- In some circumstances, which we do not fully understand, uninstalling and re-installing the application would not erase the permanent storage. This further complicates the support process.

## Things I think the developers should know, images, links etc.
One option to implement this feature is by adding a (red?) button in the advanced setup. It is accessible on one hand, yet it is not complicating any of the frequent user activities.

It would be good for the button not only erase the existing data, but also download the latest data from the site.

**Comment by HarelM** [comment]
I think I implemented the relevant functionality - it basically restores the initial state, no extra deleting or anything as all the information is stored in the state (I hope...).
After implementation I though it might be good to allow this for site users as well, as they can benefit from it too.
The problem is that site users do not have the configuration menu since they can't configure anything there. Also it might be good for non authenticated users as well.
I though I can put it in the about menu, but I'm not sure anymore.
Yes, the button will be red and it will also ask for confirmation, just to be on the safe side.
The following is the configuration menu only having this button, not very appealing, but it's OK:
![image](https://user-images.githubusercontent.com/3269297/135694022-bbafbbdf-381b-403a-a85b-a5cfc2fc64b4.png)

I can also move the configuration menu to be a part of the main menu instead of being part of the user menu, but that will make the main menu even bigger when expanded. I don't know...
Probably worth a phone call...
