### ISSUE TITLE
Unable to update a POI when website is too long

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1596]
## What I expect to happen
That adding a description and picture will update via IHM and show
I tried it here: https://israelhiking.osm.org.il/poi/OSM/relation_13082537?language=he

## What really happened
I wasted time a few times until I decided to write here

## What I did that caused the issue - step by step

Added a picture and text 9:14 AM
![Uploaded route description](https://user-images.githubusercontent.com/49042192/132096149-0bcd7395-2bf0-4e7e-8a5a-8735ff1cd7dd.PNG)

Received green message that its saved. Felt good about my contribution.
![Received msg to wait](https://user-images.githubusercontent.com/49042192/132096171-ce6cdd09-beb7-440c-8824-d3b138572060.png)

Checked at 16:30 and :-(
![image](https://user-images.githubusercontent.com/49042192/132096234-4d3d9c0c-b4d9-4b19-ba16-ce13d63bfb1a.png)

## My environment
Win10+chrome

## Things I think the developers should know, images, links etc.
Peace and love

**Comment by HarelM** [comment]
Thanks for reporting!
Can you attach the image so I can test it with a real image when trying to reproduce?

**Comment by Tsurha** [comment]
Just a JPG. Maybe too big?

![20200704_111152](https://user-images.githubusercontent.com/49042192/132102621-f42dce80-6903-40ba-ae51-d4d595c4ac48.jpg)

**Comment by HarelM** [comment]
The picture get resized when opening in the client. But I'll check nevertheless...

**Comment by Tsurha** [comment]
Github changed the name of the file. Shouldn't matter but Im not an expert with VooDoo...

BTW this specific cycling path should be circular and end where it starts, by cycling back on the same middle section.  I had no idea how to represent it in the OSM relation so it shows normally via IHM

**Comment by HarelM** [comment]
The server is getting an error from wikimedia commons when trying to upload the image there.
I'm not sure what the root cause of this and when this issue started.
I've updated the description of the route with no problem, but when adding an image the entire operation is canceled.
I'll investigate further later o, but currently there's an issue. Please avoid uploading images for the time being until this issue is resolved.
Thanks a lot for taking the time to report this! It's extremely important for us to hear about issues.

**Comment by HarelM** [comment]
I couldn't figure out what went wrong - seems like a communication issue between the server and wikimedia.
I restarted the service a few times and at the end it managed to load and seems to finish initialization correctly.
@Tsurha I have uploaded an image to the route while debugging on my environment, if you have another image it could be a good test to see that the issue is resolved.
I'm not sure I can learn much from this issue, I have added logs to be able to catch this next time, I hope...

**Comment by Tsurha** [comment]
So we suspect the long Hebrew link may have caused the issue. This is the correct page for that route:

https://www.ramat-hanadiv.org.il/%D7%9C%D7%92%D7%9C%D7%95%D7%AA-%D7%90%D7%AA-%D7%94%D7%9E%D7%A7%D7%95%D7%9D/%D7%A4%D7%90%D7%A8%D7%A7-%D7%94%D7%98%D7%91%D7%A2/%D7%A9%D7%91%D7%99%D7%9C%D7%99-%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%99%D7%9D/%D7%9E%D7%A1%D7%9C%D7%95%D7%9C%D7%99-%D7%A8%D7%9B%D7%99%D7%91%D7%AA-%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%99%D7%9D/%D7%A9%D7%91%D7%99%D7%9C-%D7%90%D7%95%D7%A4%D7%A0%D7%99%D7%99%D7%9D-%D7%94%D7%97%D7%95%D7%A8%D7%A9-%D7%91%D7%A8%D7%9E%D7%AA-%D7%94%D7%A0%D7%93%D7%99%D7%91-%D7%94%D7%A9%D7%91%D7%99%D7%9C-%D7%94/
