### ISSUE TITLE
Modify website to use map's `pbf` file

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1656]
## Feature
Use the map's `.pbf` file for the daily and hourly updates of the website.

Related to https://github.com/IsraelHikingMap/Docker/issues/21.

## Things I think the developers should know, images, links etc.
The file is available at `http://nginx/IHM`.

**Comment by HarelM** [comment]
@zstadler can you suggest a way to have an up-to-date OSM pbf file locally for the debug environment without installing all kind of command line tools globally?
Is it possible to wrap the expose and update make file code in some sort of docker container for both debug env and production?

**Comment by HarelM** [comment]
In debug environment the easiest way is simply to download a OSM pbf file from geofabrik (I usually don't need mid day updates in 99.9% of the time).
Since the site is using a http client to get the pbf file the debug environment will simply point to geofabrik, no extra configuration is needed to support this.
The rest of the code changes are basically the removal of "dead" code.
