### ISSUE TITLE
CarPlay Support for iOS app

### ISSUE THREAD

**Issue by nightmechanic** [IsraelHikingMap/Site#1657]
## Feature

Request for CarPlay support

## Some links:

Main page:
https://developer.apple.com/carplay/

probably a good starting point:
https://developer.apple.com/documentation/carplay/integrating_carplay_with_your_navigation_app

(And you need to request the navigation entitlement for the app to start developing:
https://developer.apple.com/documentation/carplay/requesting_the_carplay_entitlements)

last but not least - the programming guide:
https://developer.apple.com/carplay/documentation/CarPlay-App-Programming-Guide.pdf

Step by step example (? - not sure how this works on the cordova framework ):
https://adapptor.com.au/blog/enhance-existing-apps-with-carplay

**Comment by HarelM** [comment]
Thanks for the extra info! Unfortunately, due to the high complexity (basically re-implement a lot of the UI using the carplay interface) and low expected usage (iPhone users are only 10% of the users and even less will have carplay) I don't think this is worth the effort... :-(
Since you said that you don't think you'll have the time for this I'll close this issue...
If anyone in the future find this and would like to take the time to implement this I'll be happy to re-open :-)
