### ISSUE TITLE
Split out image creation service

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#1658]
## Infra
Instead of relaying on problematic .net libraries that create bugs like #1644 it might be better to use command-line tools or other libraries that are battle tested.
In the past this was a problem due to complicated environment setup, this is no longer the case with docker.
We should explore existing services such as gpx2pngservice and maybe what osm is using for  their image creation instead of using our own.
In any case, we should split the image creation code out of this main repo.
Code can be seen here for reference:
https://github.com/openstreetmap/openstreetmap-website/pull/2204/files

**Comment by HarelM** [comment]
Hi @mmd-osm,
I saw that you implemented something similar in the OSM website.
I was hoping to wrap up some of the logic of the animated gif creation into a docker container and allow it to run as a micro-service.
Can you give me some pointer on where I can look in order to make it happen?
Referencing the relevant osm website issue: https://github.com/openstreetmap/openstreetmap-website/issues/2132

**Comment by mmd-osm** [comment]
I'm not exactly sure I fully understand your requirements. The code you're referring to on the OSM website depends on external C language libraries to generate animated gifs. It has been integrated using FFI (foreign function interface), and it all runs on Ruby on Rails. I don't think that's a very good starting point for building your own microservice, as it's anything from lightweight and has way too many dependencies. 

Initially I ported some existing code in https://github.com/openstreetmap/gpx-import to Rails, because we wanted to get rid of running the image generation as separate binary. Maybe that old gpx-import repository would be a better starting point for a microservice, though it needs some further work for sure. 

GIF animation image was taken from: ihttps://github.com/openstreetmap/gpx-import/blob/master/src/image.c#L48

**Comment by HarelM** [comment]
@mmd-osm thanks for the info! Very helpful.
I looked at the c code and the ruby code which seems to do very similar things - create n (10) frames and highlight a different part of the route every frame using different width with libgd.
Since the code is fairly simply I can write it in any language I'm comfortable with and expose it as a micro service I guess.
I currently have a code that generates color images with background tiles etc which I'm thinking of either retiring or improving.
Thanks!!

**Comment by HarelM** [comment]
I've created the following repo in order to split the logic into a different micro service where I can decide how to proceed.
https://github.com/IsraelHikingMap/ImageCreatorWebAPI
