### ISSUE TITLE
Cannot delete a duplicate image

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1665]
## What I expect to happen
Be able to delete a duplicate image using the POI editing capabilities

## What really happened
The duplication cannot be removed

## What I did that caused the issue - step by step
- Open [מאגר מסילת ציון](https://israelhiking.osm.org.il/poi/OSM/way_85639210?language=he) way
- Click the OSM icon
  - Verify that the way contains the two identical `image*` tags
- Edit the POI
- Delete the second image
- Confirm
- Refresh the OSM page for the way
  - The way was not edited and the identical `image*` tags remain

## My environment
* Operating System and version: Windows 11 Pro
* Web Browser and version: Firefox 95.0 (64-bit)

## Things I think the developers should know, images, links etc.
FYI:
- The duplicate image was originally uploaded from IHM in [changeset 112645915](https://www.openstreetmap.org/changeset/112645915).
- The node was deleted and the `image*` tags were copied to the above way in [changeset 114889239](https://www.openstreetmap.org/changeset/114889239).

**Comment by HarelM** [comment]
FYI: the images were copied incorrectly.
The original node had two distinct images.
See here:
https://www.openstreetmap.org/node/9179849217/history
I still need to understand why the deletion fails, but the code that adds images and updates images uses distict to make sure images are not duplicated.

**Comment by zstadler** [comment]
It's my mistake during the copy. I'll fix it after this issue is closed

**Comment by HarelM** [comment]
To my surprise the code responsible for this bug is in the client side:
https://github.com/IsraelHikingMap/Site/blob/d2ec8c44b4d3182318f02fb0e1fdf5f47178a5e9/IsraelHiking.Web/src/application/services/poi.service.ts#L736
This code basically tried to understand what has changed between the original POI and the updated POI.
It looks for images missing in one list compared to images that exist in the other list to know what was added and what was removed. Since the both images has the same url it fails to understand that the image was removed.
This code is complicated enough without adding edge cases that can't happen during regular usage of the site/app.
Moreover, editing any other field in the POI (mainly the description field I guess) will trigger and update in the server which will remove the duplicated image.
I'm leaning towards closing this issue.

**Comment by zstadler** [comment]
I'm fine with closing this issue without implementing it.
