### ISSUE TITLE
Avoid showing author and date for Wikipedia POIs

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1712]
## Feature
While OSM-only POI mo longer have they last author and last-modified date, Wikipedia POIS have them. When a Wikipedia POI is merged with an OSM POI it has the Wikipedia author name and last modified date

## What I expect to happen
Avoid showing showing author and last-modified date for Wikipedia POIs, regardless if they are merged with other POI types

## Things I think the developers should know, images, links etc.
Examples:
* [Pure Wikipedia POI](https://israelhiking.osm.org.il/poi/Wikipedia/he_598515)
* [Merged Wikipedia and OSM POI](https://israelhiking.osm.org.il/poi/OSM/way_280719696)

**Comment by HarelM** [comment]
I'm still hoping this will be added back at some point, although I'm pretty sure it won't.
Due to this hope I'll keep the backend code intact and only remove it from the UI so it won't be shown but in theory will be calculated etc so if one day it will be added back there will be only a need to change the UI.
