### ISSUE TITLE
 display gps accuracy as a number

### ISSUE THREAD

**Issue by Shemesh** [IsraelHikingMap/Site#1733]
## Feature request
please display the gps accuracy as a number.

currently i have no way to know what is the accuracy, can be only guessed based upon the blue circle size around the arrow.

**Comment by HarelM** [comment]
I don't see how this will help most users...
Can you define a problem statement instead of a solution?
If you need to know the exact details related to the GPS you can use a GPS app.
The exact bearing is also not visible in a number for the same reason.
Burdening the user with too many details and numbers is not a great UX...

**Comment by Shemesh** [comment]
use case:
using ISM to save coordinates for later exploration.
i want to know the coordinates taken are as accurate as possible.

and general speaking - i dont see the point of recording data when gps is low accuracy.

**Comment by HarelM** [comment]
We have found the blue circle good enough indication for that - a balance between too much information and too little.
