### ISSUE TITLE
Recover from failure to open IndexedDB

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1785]
## What I expect to happen
If the site fails to init because of a failure to open IndexDB, it would automatically recover from the failure

## What really happened

1. Some users receives this error message:
![image](https://user-images.githubusercontent.com/1304610/200865243-21e5750e-abfd-4137-8881-044ace02745b.png)
1. Support sends instructions to delete the IndexDB from the command prompt.

## What I did that caused the issue - step by step
To create this error artificially:
1. Exit the browser
2. Open Command Prompt window
4. Run
   ```
   cd "%USERPROFILE%\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\leveldb"
   del MANIFEST-*
   ```
5. open the site in the browser

## My environment
* Operating System and version: Win 11
* Web Browser and version: Crome

#### A suggested new behavior is:

1. Exceptions while opening the IndexedDB during the initialization are captured and handled
1. The user is notified with a message like
   > The local copy of your Israel Hiking data is corrupt.
   > Please click "OK" to download a fresh copy.
1. When the user clicks "OK", the IndexedDB is deleted, perhaps using one of the suggestions in [this stackoverflow page](https://stackoverflow.com/questions/15861630/how-can-i-remove-a-whole-indexeddb-database-from-javascript)
1. The original page/address is reloaded

#### Removing Chrome's IHM IndexedDB
If needed, Chrome's IHM IndexedDB can also be deleted from the command prompt:
```
cd "%USERPROFILE%\AppData\Local\Google\Chrome\User Data\Default\IndexedD"
rmdir /q/s https_israelhiking.osm.org.il_0.indexeddb.leveldb
rmdir /q/s https_israelhiking.osm.org.il_0.indexeddb.blob
```

**Comment by zstadler** [comment]
I found another way to recover from this corruption - using the development tools. The interesting thing is that the Chrome Development Tools are Open Source, including the [storage view ](https://github.com/ChromeDevTools/devtools-frontend/blob/main/front_end/panels/application/StorageView.ts). This gives hope that the manual process below can be programmed.

1. F12 -> Application -> Storage -> Clear site data
![image](https://user-images.githubusercontent.com/1304610/201108539-839ef0a9-deeb-449b-9536-e39627d4ba26.png)
2. Click OK for the "Ooopppss..." error message
3. Reload the site
4. Clear site data again
5. Reload the site again

**Comment by zstadler** [comment]
When the IndexedDB is corrupted in the above manner, the development tools are also unable to open the IndexedDB and it shows as if there is no data and no databases. 

The Storage page before the first "Clear site data" looks like this:

![image](https://user-images.githubusercontent.com/1304610/201194222-e88c42f3-837e-4f1c-b57a-266daa433df9.png)

**Comment by HarelM** [comment]
I was able to reproduce this behavior once.
1. I deleted the indexdb files
2. I opened the site to get the error message
3. Clicked OK
4. I ran the following code in the console: `indexedDB.deleteDatabase("State");` It returned some warning in the console
5.  I ran the same command again `indexedDB.deleteDatabase("State");` And it passed. 
6. I refreshed the page and it seems to work without the "ooops" message, 

The problem is now I don't see the indexdb database being saved in the same location.
I'm using a mac, so the location in the mac is:
`/Users/my-user/Library/Application\ Support/Google/Chrome/Default/IndexedDB/https_israelhiking...`

@zstadler  Please let me know if you can reproduce the above steps and recreate the bug afterwards, i.e. create the bug, fix it using the above javascript code that runs in the console and then recreate the bug again.

**Comment by HarelM** [comment]
We agreed that for now, we are not planning of fixing this due to the complexity of the fix (if it exists) and the amount of users that suffers from this issue.
It seems like it's a problem with a corrupted indexDB which we don't have a good way to control or recover from within the javascript code...
