### ISSUE TITLE
Stop recording gracefully when recording is interrupted

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1792]
## What I expect to happen
When the application starts and finds that a previous recording did not complete properly, the suggestion to the user would be to start a new recording.

## What really happened
Currently, the suggestion to the user is to continue the previous recording. This would create a "jump" in the recording

**Comment by HarelM** [comment]
I've looked into the code and I can see a few problems with this idea - when starting a recording the app assumes it already has a position, otherwise it doesn't allow to start a recording.
If the app starts and the user turns off the location or the location takes too much time to get a fix there might be a "race considtion" here and this can cause some issues.
My suggestion is simpler - if the app starts and the previous recoding didn't finish, simply finish the recording and notify the user about it.
Then the user can choose to start a new recording or not simply by pressing the record button.
What do you think?

**Comment by zstadler** [comment]
I'm OK with that.

Suggested Hebrew message:
> ההקלטה האחרונה לא הסתיימה בהצלחה. התחילו בבקשה הקלטה חדשה אם תרצו.

Suggested English message:
> Last recording did not end well. Please start a new recording if you wish.

**Comment by HarelM** [comment]
I've changed the wording a bit. Nothing dramatic.
