### ISSUE TITLE
Clicking map names

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#18]
Should select the map. Not just the eye icon.

**Comment by HarelM** [comment]
A label is a label and a button is a button, I don't agree with you.

**Comment by valleyofdawn** [comment]
My fingers are large. Maybe extend the button to include the whole name, no need for the eye icon at basic mode at all.

**Comment by zstadler** [comment]
Despite the fact that I use the new designfor weeks now, I find myself again and again clicking on the map name rather than the visibility icon. I agree with @valleyofdawn that clicking on the names is more natural.

Perhaps we we could use a "sunken" background shape for visible layers base, overlay, and routes, and optionally also remove the "in/visible" icons!?

**Comment by HarelM** [comment]
The sunken design was my initial design, but @valleyofdawn said it's not clear enough.
I'll sleep on it...

**Comment by zstadler** [comment]
Perhaps use some eye-catching background color

**Comment by HarelM** [comment]
I think that now with the colors and and the fact that when you select the route the markers appear it's obvious which route is begin edited. the main reason I don't want to make the labels a button is because I can't easily control the button width and so it will create and unorganized look. I know it's silly but still...
