### ISSUE TITLE
Old links not working

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1826]
### What happened?

I have old links of shares and them not working.
https://israelhiking.osm.org.il/#!/?s=KIe7BYs5cf

### What steps will reproduce the bug?

Open old link
https://israelhiking.osm.org.il/#!/?s=KIe7BYs5cf

### What I expect to happen

Redirect to new link
https://israelhiking.osm.org.il/share/KIe7BYs5cf

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

**Comment by HarelM** [comment]
There was a time when these links were redirected in order to allow people who are using them to insert the link and get the new supported one (if you had an old link and wanted to replace it with the new one in your site for example).
These are very old links (we did the switch in 2018) and we decided not to support them to reduce code complexity.
Sorry to disappoint, but relaying on something that was written and unmaintained since 2018 is not great.
People who are using these old links can easily change them and make them work again, we have notified sites that were using these links heavily back then when we did the switch.

**Comment by amiad** [comment]
You can add redirect rule to the Nginx server without touch the code.

**Comment by HarelM** [comment]
I still don't see a use case that's worth investing time to solve...

**Comment by amiad** [comment]
I have list of dozens of old links. I can do search and replace but I'm probably not the only one. Other people post links in blogs and facebook.

Why not create a redirection and continue to support them?

**Comment by zstadler** [comment]
> You can add redirect rule to the Nginx server without touch the code.

Everything after the `#` character is handled at the client side. Therefore, the server side does not receive the share id and cannot handle it. The only way to handle the old links is by adding code at the client side.

**Comment by HarelM** [comment]
Sorry to disappoint, but this can be easily fixed manually or using a script. there was also a time when the site converted these links. Now it's too late. If you are using links that are that old there are chances that the map is inaccurate and you'll end up not where you wanted to be.
Sites and link owners need to maintain their links if they want to make sure they work.
