### ISSUE TITLE
Discussion: How to ease route planning when it has to continue on a path already used

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1910]
### What is the problem this feature will solve?

When planning a route that has to go on a path it already used, currently we need to create two routes and join them. This is a cumbersome way.
Below is our phone call summary.

### What is the feature you are proposing to solve the problem?

Introduce a mode where clicking on a route does not add a dot in the middle, but continues from the end.
This could either be:

1) Always be in this mode and so always continue from the end. 
Adding dots in the middle will be done by dragging the route sideways and dragging it back. This functionality is already supported.  
A scissors tool will have to be introduced for splitting routes.  This tool can eliminate the current long tap/right click menu
Its a clean behavior change. 

2) A toggle between the current "add dots" mode and the new "always continue" mode. Its a safer solution as functionality is only added. But its another complication for the user.
UI for this method has its challenges. If its an icon on the main screen, what could it look like? It can be explained in words in the routes menu.  For example:
![image](https://github.com/IsraelHikingMap/Site/assets/49042192/befbd2bf-23a9-4f96-82c6-f435e965702b)

### What alternatives have you considered or tried?

The current solution works.  I just do not like it in this area.

### Additional information

Another point is color.  When a route does go back and forth on the same path, should it have 2 colors or keep it the way it currently is.

**Comment by HarelM** [comment]
A few minor corrections:
There's no long click/right click in the app, the menu opens up when you click on a route point while editing.
You can also do a route that overlap itself by clicking next to an exiting route and dragging the added point to the route, you don't have to combine routes.
This is a side note obviously, the discussion here is about how to improve the current short comings of the current approach.

**Comment by Tsurha** [comment]
Thanks for the clarifications.

### Option 1 - "always continue"
To elaborate, the behavior is:
- If while editing the user clicks on a place without a point, a new point is added to the end.  This is both if that place is outside the current route (excising behavior) and if that place is on the current route (new behavior).  
- If while editing the user clicks on a place that already has a dot, the menu opens up (excising behavior, see picture). A new scissors tool is not needed (earlier I thought it was needed).
- Adding points in the middle will be done by dragging the route sideways and dragging it back. This functionality is already supported.  But is adding points in the middle necessary at all?

![image](https://github.com/IsraelHikingMap/Site/assets/49042192/f2f6fa5b-58f8-4de1-8113-4ecb02a68a6a)

### Option 2 - toggle
2) As discussed, in option 2 toggling between "add points" mode and a new "always continue" mode could be with an icon in the editing icon column.  We just did not know how will it look like.  If this is chosen, will have to carefully design two A+B icons that explain it. At least a tool tip on it can add wording. 
![scissors](https://github.com/IsraelHikingMap/Site/assets/49042192/821b8e5c-49a7-4a5c-bd8a-de0b6c57d44a)


Note that with one color for a route, the user will not be able to distinguish between points on the route on one direction from points on the opposite direction.  Two colors will be preferable here. If so, it has to be defined more.

**Comment by HarelM** [comment]
As explained on the phone, when editing a recorded route (not a planned one) dragging a middle point can change the route dramatically (consider a place that doesn't have a way on the map and was recorded, moving it will completely move the route to a different place).
In that case, there might be a need to be able to cut the recording in a specific place, and for that a middle point is needed.

**Comment by Tsurha** [comment]
I've edited my previous comment per yours, since it is challenging for option 1.  

Lets consider option 2 with two different modes.  We did not know what could their icons look like.  Here is one possibility / idea:

![AB](https://github.com/IsraelHikingMap/Site/assets/49042192/82818286-fb54-4a94-ae65-b8e1e873f0e6)

**Comment by HarelM** [comment]
Any chance you can update the initial comment and remove the second one
I just feel there's a lot of duplicate info there, and it's hard to understand what is the last proposal in general.

Regarding your last post about an icon, it's easy to understand what it means given this context, and if the images are presented side-by-side, but if you click on the image and it toggles from one state to the other it's harder to really grasp the difference, and without this context it's even harder.
I would recommend, as an interesting experiment, to post the image only and ask in the facebook group what do people think this means.
I'll be surprised if more than 30% will get it right :-).
If we add a button to the top editing menu, a scissors icon that you can toggle on and off (with the green frame) is a lot more intuitive I believe.

**Comment by Tsurha** [comment]
I just created a route back and forth with your idea of points near by, and dragging them to the route. It works well and seems like the whole discussion here is not worth the effort.

**Comment by HarelM** [comment]
Interesting turn of events 😀 I'll keep this open nevertheless for now and see how I feel about it. Maybe involve our new UX people too to take this into consideration.

**Comment by zstadler** [comment]
Having two modes, a.k.a. the toggle options, is complicating of the UX. This is a move in a directions that we've avoided going for as long and as much as we could. I would not support it for the problem described here.

This leaves us with considering the best UX for the "click" and "click and drag" operations somewhere on the existing route.

IMO, a "click and drag" somewhere on the existing route could only mean what it does now: create a new intermediate point at the location where the drag ended. This should remain also when considering any form of "always add to the end" UX.

There are options under discussion for the "click" (without a drag) somewhere on the existing route.
   A. Create a new intermediate point and do not do any re-routing, as is today
   B. Create a new end point and a route to it.

The current UX (option A) is used as a preparation step for a few user scenarios, including:
   - Mark a place for splitting a trace into two traces
   - Mark a place to keep unedited when editing a recording

If Option B is used, the way to add an intermediate point would be to use "click and drag" back and forth. Since "click and drag" re-calculates the route, this option will make editing of recordings practically impossible.

Similarly, "click and drag" can also be used to mimic "Option B" when option A is used. As @HarelM suggested: click anywhere near the intended location of the new end point and drag it to the desired location.

Without trying to estimate the importance of the three user scenarios discussed here, Option A is supported by two user scenarios (splitting a route and editing a recording) and Option B is supported by one (route twice on same segment). The later has a reasonable workaround if Option A is used. However, the editing a recording user scenario has no reasonable workaround if Option B is used

**Comment by HarelM** [comment]
It's worth noting that on the go map has similar behavior - click is always adding a point at the end of a route and dragging is to create a middle segment with routing.
It doesn't seems to have an option to open a GPX file though, so the part about cutting a recording is probably not relevant.
https://onthegomap.com/#/create
