### ISSUE TITLE
Privat POI: cannot add website link

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1931]
### What happened?

When trying to add a website link to a private POI, the field cannot be edited

### What steps will reproduce the bug?

1. Create a private POI
2. Select "Website link" from the menu
3. A new field is added, but text cannot be entered there

### What I expect to happen

The field for the website link should be as wide as possible and it should be possible to add and edit its contents

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

### Additional information

![image](https://github.com/IsraelHikingMap/Site/assets/1304610/e2760955-1b34-4b9c-a63c-b22c0a84a705)

**Comment by HarelM** [comment]
Thanks for noticing!
I've also found a way to improve the input field across the app, so that when you focus on an input field the placeholder moves up and becomes small, this is how it used to be in the past, but broke when upgrading to angular 15.
Also I found a far better way for place the delete button - which is also considered more accessible.
![image](https://github.com/IsraelHikingMap/Site/assets/3269297/5e3cbacc-1465-4356-9571-12d2bf1255e9)
