### ISSUE TITLE
"Got lost warnings" are produced too close

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1942]
### What happened?

When "Got lost warnings" is enabled, the warnings are produced when the distance from the route is less than 10 meters rather than more than 50 meters.

Thank you, Ido Eliash, for reporting this bug!

### What steps will reproduce the bug?

1. Choose a nearby X  junction
2. Create a trail going straight through the junction
3. Activate the GPS and optionally record the trace
4. Walk to the junction then turn and walk slowly walk away from the junction
5. Notice when a "Got lost" warning is heard

### What I expect to happen

The "Got lost" warning should be heard when the distance exceeds 50 meters

### Platform

- [X] Israel Hiking Map app
- [ ] Israel Hiking Map site in a browser

### OS Name and Version

Android 12, App version 9.18.98

### Browser Name and Version

N/A

### Additional information

[Here is a share](https://israelhiking.osm.org.il/share/bPkRsUEwsY) created while doing a similar experiment 3 times:

![image](https://github.com/IsraelHikingMap/Site/assets/1304610/fd076f5a-514b-4765-8e4f-4951ea7fc8d5)

**Comment by HarelM** [comment]
Relevant previous issues: #929 #1473
Phone call conversation summary:
The algorithm can be improved by remembering the previous location and to which part of the route it was "close" to in order to better understand if there's a need to sound the notification.
This information is hard to maintain and can cause a lot of edge cases and bugs that the risk in implementing it is not worth it for this feature, from my point of view.
The feature itself isn't great in general since it only works when the app is in the front and the screen is on.

Having said that, the algorithm now takes into consideration use cases that less interesting than the current problem - if there are two routes that crosses one another, and you are near their junction, the current route shouldn't change.
Most users do not have more than one route.

The proposed solution, is to try and use the heading as described in #1473, but if there is no route found, reduce the criteria back to 50 meters and ignore the heading so that there won't be a notification under 50 meters.

**Comment by HarelM** [comment]
The above suggestion basically will remove notification in case you are traveling in the wrong direction.
This means that if you are following this route and take the wrong turn in the X junction not notification will be sound.
I can't think of a solution that will take into consideration all these use cases honestly without being unmaintainable.
![image](https://github.com/IsraelHikingMap/Site/assets/3269297/26a11f21-0ca0-488b-96d9-d76fe880af32)

**Comment by HarelM** [comment]
Phone call conversation summary:
Wrong direction notification is less important than route proximity.
The suggestion above is accepted.
