### ISSUE TITLE
Misalignment when clicking layer definitions buttons

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1974]
### What happened?

I want to open the definitions of a layer, and the definitions of the layer below is opened.

In careful examination it shows that although the cursor is placed on layer definitions button of the upper layer, the button of the lower button shows the gray background of the "hover" :

![image](https://github.com/IsraelHikingMap/Site/assets/1304610/07641a9d-9e71-4407-8b08-f1f30dec1280)

In the above example, although the click was done on the "זיהום אור" layer, the definitions of the "זיהום אור 2012" layer will be opened.

Similar behavior is seen in the app, although the gray "hover" background is not shown.

### What steps will reproduce the bug?

1. Open the layers pane
2. Ensure there are at lease two private layers
3. Place the mouse on the layer definition button of the upper private layer
4. Move the mouse slowly down until the button no longer has a gray background, yet it is still on the upper private layer
5. Click
6. The edit dialog shows the lower private layer

### What I expect to happen

The definitions should correspond to the layer under the mouse

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

### Browser Name and Version

All

**Comment by HarelM** [comment]
This is an accessibility issue in general that we "override" incorrectly.
The area which is possible for click (touch), according to Material design should be minimally 48 pixels.
This can be seen in the following screen shot where the blue part is clickable area:
![image](https://github.com/IsraelHikingMap/Site/assets/3269297/60a4e7aa-fd9b-4528-ac55-c42a2d3f943c)
In order to have many layers in the same screen we override the height of the default button, but do not override the clickable (touch-target) area height.
Since we are planning to redesign this screen soon, hopefully, and the affect of this bug is small I don't plan to fix it now.
It also affect the layer selection in the part where the is no text.
The fix should be in the direction of accessibility and not reducing the clickable area.

**Comment by zstadler** [comment]
Thank you!
