### ISSUE TITLE
Remove duplicates between "Site" and "Map"

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#200]
I suggest we remove duplicates between the "Site" and the "Map" in the following manner:

- The site will take the legends from the same location used for ```LastModified.js``` and the map will create the legends in a predefined name - ```Tiles\legend.png``` and ```mtbTiles\legend.png```.
  - We may want to consider having a separate  ```LastModified.js``` for the Israel MTB map.
- The site will use the routing data from ```Cache\israel-and-palestine.pbf```
  - The refresh tasks for the routing cache and the search will be invoked by the map update task when a new "last update" date is published. 
  - Alternatively, the tasks can be invoked after the completion of zoom15 for the Hiking map or as soon as the pbf file is downloaded.

I'm not aware of any other duplicated.

**Comment by HarelM** [comment]
Hgt zip files are duplicated.
The legend idea sounds good.
I prefer that most of the work will be done in code that is not batch so we can have a better idea what went wrong when it did.
Another solution might be another repository called common or something.

**Comment by zstadler** [comment]
I'm fine with the server activating the scheduled tasks instead of Windows' Task Scheduler. Please let me know how to see if something went wrong.

I don't like the idea of a 3rd repository. By definition, the Map repository is a producer for the Site repository. The Map repository's code creates the tiles, and the Site repositories code is presenting them, along with its own rich set of capabilities. IMO, just as the Site code is accessing the products of the Map repository, it should access the raw inputs it needs.

**Comment by HarelM** [comment]
There is an issue with doing scheduled task as part of a website since the website might go down if nobody is using it in order to save resources.
Regardless, Windows' task scheduler is the one that activates the update and it calls the ```IsraelHiking.Updater.exe``` file which has all the logic and writes to the log when and if it fails.
The log can be found on the server in the bin folder of the site next to the updater. I think the log name is ```IsraelHikingUpdater.log``` or something close to it.
If needed, this updater can copy the hgt files.
The original reason I think I added those files was in order for this repository to remain independent of the ```Map``` repository so that if someone wants to use it with different tiles there's no problem.
Also if I want to develop the ```Site``` code I don't have to download the ```Map``` code, but that's probably just for me, but it is an argument nontheless.

When I say common repository I mean in term of Git what is called a "submodule" as far as I remember when I used it about two years ago the repository that has a submodule still have all the data you need but the it can be shared between repositories - an example that pop to mind is an infra submodule used by two project in the same company, which is somewhat similar to this case... so when you map each repository the submodule gets mapped locally without needed to do anything special, I don't know how GitHub manages this though, might be interesting to find out, wouldn't you say? :-)

**Comment by zstadler** [comment]
Since the hgt files are stored in as a single zip file for the site and as individual files for the map, there is a need to store each format in the respective repository.

**Comment by zstadler** [comment]
Legend image files have been placed in ```Site\Tiles\legend.png``` and ```Site\mtbTiles\legend.png``` and deployed to the server.

**Comment by HarelM** [comment]
Closing this issue in order to open a new one about update search and routing script/application.
