### ISSUE TITLE
Click on POI prefers routing instead of showing POIs details

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#2013]
### What happened?

אני באמצע תכנון מסלול. מצב עריכה. מעניין אותי להסתכל מה יש בPOI מסויים כדי להחליט אם לנווט לשם. בתמונה ריחפתי מעל העץ וקיבלתי תיאור בריבוע לבן - כוריזיה הדורה. כמשתמש אני שמח שהתוכנה "מבינה" שאני בעניין של ה POI. היא רואה אותי!  
אני מקליק על הPOI להבין מה בדיוק, אבל במקום לפתוח את התיאור שלו, דווקא הניווט תופס והולך לשם.

![WhatsApp Image 2024-06-29 at 20 11 56](https://github.com/IsraelHikingMap/Site/assets/49042192/24f84823-622e-486c-9639-b1e6f49c49e8)

### What steps will reproduce the bug?

כנ"ל

### What I expect to happen

בשביל להמשיך את תכנון המסלול לשם יש לי מלא אפשרויות מסביבו להקליק. מעדיף שכאשר אני בול על אייקון הPOI, ההקלקה תפתח תיאור מלא.

### Platform

- [ ] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Win 10

### Browser Name and Version

Chrome

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
Due to how this is implemented, this is not an easy fix, and I rather not break the current logic of route planning just for this feature.
While I agree it is a better UX, the risk of solving this is high.
I'll keep this issue open for when I have proper time to dive into this.

Technical note for myself:
The current logic of route planning is using the mouse down, mouse move and mouse up for all the route planning logic.
down-move-up is relevant only for dragging stuff and should not be used for click events, to allow cancelling the propagation of the click from other components in the app.
This means that there's a need to move all the click logic to a different method and only handle dragging in the current logic.
Easier said than done...

**Comment by Tsurha** [comment]
סבבה תודה

**Comment by zstadler** [comment]
I'm afraid I noticed this issue a bit late.

I believe this is a degradation in the user experience. The previous user experience allowed the user to route to the exact location of a POI in a single click/touch. The result of this request is that routing to an existing POI requires a nearby click/touch followed by dragging the route. I think such a "click and move" behavior should only be a "last resort" when no other solution is available, as is the case for closing a loop in a route.

To see a POI in the previous user experience, exit routing mode, explore the POIs, and continue routing. IMO, the previous behavior a more natural user experience in routing mode.

**Comment by HarelM** [comment]
The behavior before this fix will do two things:
1. Open the POI pane
2. Add a segment to the route

This behavior is not a good UX, I'm pretty sure we can agree on that.
The white bubble is above the relevant POI on the map, so clicking on it before this fix will add a point where you clicked with the mouse - which is not where the POI is, but above it - so that's not a good UX as well, I hope we can agree on that as well.

So after the fix when clicking the POI, it will open and not create a route segment to the "wrong" place.
If you want to route to the POI, you should click on the map where it is, below the white bubble, (the current white bubble doesn't cover the POI) so you don't need to drag move the last point.
Clicking below the white bubble behavior didn't change with this fix, so you can try it out even today.

We can discuss a change in how a click on the bubble operates while editing a route, but the fix I did is needed anyway.
I don't think the behavior of clicking on a POI should be changed based on editing mode as I think it will only cause confusion, but I don't mind talking about it.

**Comment by zstadler** [comment]
Thanks for the clarification!
I agree that clocking the white square of the POI, where a tool-tip like "כוריזיה הדורה" is shown, should not route to it.

I would to suggest that when routing, the area below the square, will snap to the the **accurate** POI location for routing - extending the route or adding an internal point according to the context. This is especially useful in lower zoom levels, such as used for 4WD routing. 

![image](https://github.com/user-attachments/assets/9c643aa3-c0b1-40af-be96-87d22a304009)
