### ISSUE TITLE
Localized search 

### ISSUE THREAD

**Issue by roiros** [IsraelHikingMap/Site#2044]
### What is the problem this feature will solve?

I have a hard time finding relevant information in my proximity.

It's mostly camping spots but also funtation, water taps and so on.

The process of removing elements from the map and then adding them back is tidious and fiddly.

### What is the feature you are proposing to solve the problem?

Localized searches results by both name and type. 
+showing the distance from current location/center of maps screen would even better it.

### What alternatives have you considered or tried?

Removing and adding elements.

Using Google maps and then coming back to the app.

**Comment by HarelM** [comment]
Thanks for taking the time to open this feature request!
Manipulating the search results to favor closer entities is not an easy task and creating advance search for types etc is also a great idea for the simple reason users won't know that it exists.
Right now there are already some advances search capabilities such as exact match using `"` and search within boundaries using `,`.
Making the search more complicated without a way to inform the users about it is basically implementing a feature for a specific user or a specific case, which is not worth the time in most cases.
Adding a distance from current location to search results might be a good middle ground, but I fear it will clutter the UI.
I'll think about it never-the-less.
If you have good examples (besides google obviously, since I can't compete with them) of apps that has a good user experience around search that is able to do what you requested I'll be happy to take a look.

**Comment by HarelM** [comment]
Related issues:
- https://github.com/IsraelHikingMap/Site/issues/1918

**Comment by roiros** [comment]
It's still an issue for me.

I want to find places without using my computer. I want to find them while I'm on a trip.

searching for `חניון לילה` brings up useless results, even when using a computer.

This is a **very** common flow for me - **exploring** nearby locations/attractions.

If you can suggest how I can get the desired functionality in less than 10 clicks using the existing app/with an alternative feature it would be great.

attached - suggestions of `חניון לילה הפיתול` while the location is Tel Aviv.

![Screenshot 2024-10-20 at 13 49 02](https://github.com/user-attachments/assets/7c162ba4-0665-4c85-a38e-4465c9298c58)

**Comment by HarelM** [comment]
I don't understand the use case or workflow to actually help.
It might be that distance-based search is one solution, but I explained both in this issue and the previous issue what problems it has and why I don't think it's a great solution in general.
I would recommend trying to define the problem better and not go and define the solution.
I still don't fully understand the problem in order to suggest a solution...

**Comment by roiros** [comment]
User flow

User looked for a hiking trail or built one.
At the end the user screen is at certain coordinates

The user looks to find a camping ground close to the hiking trail he planned in a couple of comfortable manner - using less than 10 clicks.

User searches for additional trails next to the camping ground for the next day. 
---
I don't know in what other way I can convey the issue to you.

As a paying member for 3 years, I'm have already looked for alternatives due to this specific issue.

**Comment by HarelM** [comment]
Both the "official" hiking trails we support, and the camping ground can be found and filtered using the POIs pane, and the relevant base map.
These are the main ways to find stuff around you.
When I plan a trip I do a lot of research using a lot of sites as every site has things that is better for my needs. Using the desktop in this case, or a tablet with more screen real-estate can also help. This obviously takes hundreds of clicks...  

There are ways to use custom overlays to highlight some places on the map, but this is very similar to the POIs pane usage (using overlays instead of POIs filtering), here's an example:
https://www.facebook.com/share/p/4TgHxEhABrK3RkM9/

I'm still not sure I understand what is currently missing in the existing functionality that prevents you from achieving your objective.
