### ISSUE TITLE
Do not allow overlapping layer on the same baselayer

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2087]
### What is the problem this feature will solve?

Many users remain with overlapping overlay after not noticing or ignoring the initial notice

### What is the feature you are proposing to solve the problem?

Check and display the notice on startup

### What alternatives have you considered or tried?

None

**Comment by HarelM** [comment]
I don't think this will solve the problem. We need to be more creative if we truly want to solve this.
Moreover, there are a few popups already presented when the app starts in all kinds of flows, adding it will only complicate things further...

**Comment by zstadler** [comment]
I also don't think it will solve the problem, but in the spirit of 20-80, it will improve the situation as people will be bugged by the message.

We should probably also have an answer for it in the FAQ...

**Comment by HarelM** [comment]
I don't think fixing it is easy, so it doesn't fall under the 80-20 rule from my perspective - i.e. I believe adding a message when the app starts will cause more issues than it will solve.

**Comment by HarelM** [comment]
Phone call conversation summary:
Instead of dealing with warning messages etc, we will simply not show the same overlay on the base layer.
To be more general the comparison will be done using the address of the baselayer and the overlay.
If they match, the overlay won't be presented.
This will also remove a warning that wasn't too helpful to the users.
Here's how it would look - as can be seen in the image the baselayer and overlay are "the same" so the overlay is ignored.
![image](https://github.com/user-attachments/assets/42108b97-f434-42ed-a096-65c828937e2a)
Switching to another baselayer and the overlay "comes back":
![image](https://github.com/user-attachments/assets/5192ff64-f47d-412c-9aed-cd043a6bfee9)
