### ISSUE TITLE
Simplify interface

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#217]
Print is rarely used, you get the same functionality from the browser or with ctrl-p.
We can live with "save as" alone. No need for save.
The "i" and "?" can be combined.

**Comment by HarelM** [comment]
Save as and save are not the same thing - I don't want the user to double click every time he want to save. for the same reason every desktop application have both save and save as - not planning on removing this.
Print is mainly there to signal the user he can print the map, I think it is an important button although it might not be used a lot. Also note that it might not be used by bikers because they usually do a single day ride (as far as I can understand), hikers may use this feature when they do a long trail and sleeping in tents where cellular is turned off.
info and help can be discussed in issue #219.

**Comment by valleyofdawn** [comment]
I beg to differ.
I can't imagine a person interested in a printout not trying out the
browser printing ability.
You save only once in a session. I would bring up a dialog box that asks
you what to name the route and lets you change the format and location if
you want.
I have like 20 Israelhikingmap.gpx files in my downloads folder and I can't
remember what is what.
Uniting the help features cleans up the interface even if the user
experience once he goes there is as complicated.

בתאריך 3 בספט׳ 2016 01:07 PM,‏ "Harel M" <notifications@github.com> כתב:

**Comment by HarelM** [comment]
My response got lost for some reason.
I don't plan to implement a complicated screen related to save just because a user can't change the settings of his browser.
If the content of the files was important to you, you've change the file name or change the behavior of the browser like I did.
I agree about the help but let's continue the discussion about it in issue #219.
I don't think the print button is so annoying we should remove it, for the benefit of the doubt I prefer to keep it.
I think I and most users do not trust the browser print option to print what you need unless there's a print button on screen telling me the site owner had invested time to make it work properly, that's my 2 cents.

**Comment by HarelM** [comment]
Closing along with #219. I don't see anything that can be simplified at the moment besides Help -About- Legend.
