### ISSUE TITLE
Hide the "Undo" button when not in edit mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#237]

**Comment by HarelM** [comment]
It's working for me, can you explain what's not working? Describe a scenario...?

**Comment by zstadler** [comment]
After hitting Esc route editing mode is terminated, but the undo button is still visible and misleading.

**Comment by HarelM** [comment]
This is different than not working :-) reducing severity.

**Comment by zstadler** [comment]
I've already reduced the severity from Critical to High and changed the title when I found out the problem.

I do not think it is a Medium bug.

**Comment by HarelM** [comment]
The button becomes grayed out meaning you can't undo, I'm not sure I want to completely remove it.
Disables:
![image](https://cloud.githubusercontent.com/assets/3269297/18619375/1ff63514-7e03-11e6-936d-40e7e28d706c.png)
Enabled:
![image](https://cloud.githubusercontent.com/assets/3269297/18619377/2bdd9ec6-7e03-11e6-97fa-76fb724de0fe.png)
If this is the case I'm not sure it is even qualified as bug, it's more of a styling opinion, am I missing something?

**Comment by zstadler** [comment]
IMO disabled means there is nothing to undo.
Since the Undo button is not functioning in non-edit mode, it should be hidden like the route type buttons.

**Comment by HarelM** [comment]
Well this applies to the clear button as well, which is currently doesn't even look disabled when in non editing mode.
my concern is that changing the UI might confuse the user more than a disabled button.
I'll try it out and see if it is friendly - this will require a change in the location of the buttons since I don't think the clear button should appear above the edit button, do you agree with this statement?

**Comment by zstadler** [comment]
Nice catch of the cler button. 
I agreed that the buttons need rearranging.
