### ISSUE TITLE
baselayer parameter in the site URL is ignored when url is also given

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#252]
For example, 

[```http://israelhiking.osm.org.il/#/?baselayer=Israel_MTB_Map&url=https://sites.google.com/site/marleyfile43/file/banias.gpx?attredirects=0``` ](http://israelhiking.osm.org.il/#/?baselayer=Israel_MTB_Map&url=https://sites.google.com/site/marleyfile43/file/banias.gpx?attredirects=0)

shows the track on the Israel Hiking Map, regardless of the ```baselayer``` parameter or the last map used.

[```http://israelhiking.osm.org.il/IsraelMTBmap.html/#/?url=https://sites.google.com/site/marleyfile43/file/banias.gpx?attredirects=0```](http://israelhiking.osm.org.il/IsraelMTBmap.html/#/?url=https://sites.google.com/site/marleyfile43/file/banias.gpx?attredirects=0)
should also work, but it returns a 404 error.

**Comment by HarelM** [comment]
Both are not valid links.
Mtb map index file is just for redirection.
I don't want to keep supporting basemap in url, it's bad practice when we have a proper share button.

**Comment by zstadler** [comment]
Using the ```url``` parameter is a published, valid, and an essential ingredient for enabling other sites to show user-contributed tracks on top of our maps, or to simplify the process for showing their own tracks on our maps.

The inability to select a base map when using the ```url``` parameter is discriminating the MTB map.

Some mechanism should be put in place to support the MTB map, be it the ```baselayer``` parameter or another. Moreover, this mechanism should be officially supported, if we want to be able to promote the use of the MTB map by other sites.

**Comment by HarelM** [comment]
Basically, what you are reporting here is a bug.
When I added this feature my intentions was merely to allow sharing of routes easily. the intention was not to change the layer the user had before surfing to this link.
When I added the legend I accidentally broke this statement and this is why IHM is automatcally selected.

The only reason I keep supporting baselayer in url is due to backwards compatibility with old links, but the bottom line is that keeping these link available takes a lot of time and a lot of code and I think that we should always prefer to share using the share button and not the url - this will allow us to change anything we want in the future since sharing through share button hides implementation details.

**Comment by HarelM** [comment]
If you feel strongly about the baselayer in the url you can uncomment the line in layerService.ts file which have a #252 reference. I don't think it's correct but I'm open to discussion.

**Comment by HarelM** [comment]
@zstadler - Still waiting on your input to close this issue.

**Comment by HarelM** [comment]
@zstadler your feedback is still required, I want to close this issue.

**Comment by zstadler** [comment]
I think baselayer is important and should be preserved for the long term as part of supporting the MTB map.

I have not had the time to un-comment the appropriate line.

**Comment by HarelM** [comment]
@zstadler worth testing it, I have done little to no tests...

**Comment by zstadler** [comment]
Is there a way to add automated tests for such a feature?

**Comment by HarelM** [comment]
Yes, but the automated tests will probably be done by mocking a lot, I have some tests but the layers service is still not covered by tests. Hopefully in the future...
I meant by tests some basic sanity to make sure the feature works as expected.
