### ISSUE TITLE
Correct "Israel Trail" icon in search results

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#266]
Show a hiking icon rather than a bicycle icon.

**Comment by HarelM** [comment]
Here is the reason.
The search's pre-possessing is merging way that has the same name and can be joint (has a mutual point).
It also finds all the ways that are in a relation and merges the tags of the ways to the relation.
The bug was that the merge tags function overwritten the relation's tags.
The current fix is meant to add missing tags without overwriting existing tags.
Note that the reason for that is that one on the ways has a tag called route=bicycle - which is an incorrect mapping. Never-the-less the search code should be able to overcome incorrect tagging.

**Comment by HarelM** [comment]
Will be visible after next search update tonight.

**Comment by zstadler** [comment]
Why do the copy in the first place?
I think way tags should not be copied to the relations it belongs to, just like node tags are not copied to the way(s) it belongs to.

**Comment by HarelM** [comment]
Ways that describe a place might have place tag which I would like to render as a house when searching for the relation. This is the main reason I think, but I must admit I don't remember why I did it.
The bottom line is that ways that belong to a relation do not get saved in the database and if we'll want to search for a tag that belongs to that way we won't find it - I know it's not a very good argument...

**Comment by zstadler** [comment]
I also have a hard time understanding the reason for this behavior.

I think that relations and ways are independent elements that should be found by their own tags. Ways should not be ignored if they belong to some relations, and relations should be found only by their own tags.

**Comment by HarelM** [comment]
That's a bit naive IMO - if a way has the same name as a relation it belongs to (this is the code assumption here), the user will not want to receive both items in the search results. 
He will probably want to receive the relation as it contains more data (I would in any case...).
Let take the following example:
Assuming we have a stream with multiple ways and a relation to group them together.
I would like to return the relation when searching for it but have a stream icon next to the results.
For that I need the stream tag from the way.
Since I know there are mappings error I can't assume the relation has all the required tags and thus I need to merge the tags from the ways compounding the relation.
Not sure I was any clearer, in any case, I'm still not convinced I should remove it...

**Comment by zstadler** [comment]
Let's put the stream aside as relations are not used there, or for simple roads.

Israel Trail is a good example, as someone labeled most of its segments as "Israel Trail".
IMO, this duplication should only impact the priorities of the search results. I see two potentially useful priority criteria:

1. Relations have higher priority than ways
2. Larger bounding boxes have higher priority than smaller.

I still don't see a reason for tag data copying or other manipulations.

**Comment by HarelM** [comment]
Merging tags is mostly to overcome bad mapping (I think).
A boundary of a place can be mapped by ways with the appropriate tag while the relation that compound them doesn't - thus the relevant Icon won't appear.
Merging tags is also needed when merging ways together.
You can argue about the need to merge elements as part of pre-processing but the fact is that the more you merge the better the results you get and less duplication.

**Comment by zstadler** [comment]
We agree with the need to merge members' ways in a relation in order to capture the relation's shape.

I disagree with the transfer of tags from members to the relation.
- It supports mapping errors by accepting and correcting them
- It assigns potentially incorrect tags to the relation.

It at all, relation tags are applicable to its members, not vice versa.
