### ISSUE TITLE
Allow Oruxmap users to upload and download tracks to IHM

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#275]
Quating Jose:
But if you provide an API, similar to gpsies.com or everytrail.com, tha app can upload/download tracks to your servers.

Quating Zeev:
נשמע אחלה, ההבדל היחידי, כפי שאני רואה הוא שאורוקס תמשוך מהמסלולים השמורים אצלנו באתר במקום מהשרת שלהם.  

אנחנו יכולים גם לאפשר למשתמשים להגדיר מסלולים שהם שמרו כ"מסלולים פומביים" ומצד שני לאפשר לכל אחד לחפש במסלולים הפומביים ולהעביר לאורוקס, ל offroad או לכל אפליקציה שתרצה.

**Comment by HarelM** [comment]
I still need to solve some issues before I can allow other applications to interact with our server.
The main question here in term of usability is how the interaction with the user will be - assuming the user shares a route. If he needs to go to the application and "download" it to the device it completely misses the point a bit. I think this is how Orux operates. Anyway, I'll need to solve #272 first...

**Comment by valleyofdawn** [comment]
Completely or just a bit? Anyway, it woyld save a lot of work if you could
upload them from orux. I use this function efficiently with GPSies , where
I store my routes.

**Comment by HarelM** [comment]
Sorry, corrections was not fully proofed. It's in the middle - it does let you move data without files which is very important but it's not straight forward and easy as I would like it to be.

**Comment by HarelM** [comment]
Mail to Orux:
--------------

I have started playing around with the idea of sharing routes from our site directly to the app.
I have setup an API call which will return a shared route, that can be sent in a specified format.
I would like to allow this only for registered OSM users.
Please let me know what you need in order to proceed (assuming you would like to proceed :-)).
To do some basic testing to see what the API can return you can do the following:
1. register in osm
2. surf to https://israelhiking.osm.org.il
3. click the upper right frown face to login to OSM
4. click the pencil on the right and add some points on the map.
5. click the right share icon, add description if you'd like and click the green button to share.
6. at this point you have a like that should look something like israelhiking.osm.org.il/#/s=<site id>
7. use the site id to call this api: israelhiking.osm.org.il/api/urls/<site id>?format=gpx
8. this should ask you to download the route you just created.

other formats are supported (geojson, kml, csv), I'm still not sure how to support upload to the server, but that can be done later on.

**Comment by HarelM** [comment]
Orux's response was not very helpful and he wouldn't want to allow an API to sending routes straight to the mobile device. I don't think there's much to elaborate on this topic.
