### ISSUE TITLE
Allow adding new layers from NextGIS online catalog

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#283]
NextGIS has an online catalog and API for GIS resources, including Tile services (TMS).

Our "Add Base Layer" can be significantly enhanced by allowing novice users to add layers from the catalog.

References:
- [The catalog announcement](http://nextgis.com/blog/qms-service/) 
- [The online catalog](https://qms.nextgis.com/)
- [API documentation](http://docs.nextgis.com/qms_srv_dev/doc/api.html)

Notes:
1. Currently, there is no indication for tile transparency of a given TMS service. Therefore, at this stage, I suggest the enhancement will not be available for "Add Overlay layers".
2. In the future, and depending on the offering in the catalog, we can add support for services other than TMS: WMS, WFS, and GeoJSON.

**Comment by HarelM** [comment]
Doesn't sound hard to implements.
Let's see if we can think of an easy to use and friendly UX:
one option is to allow the user to select from a drop down provided by the above service.
Another option is to "auto-complete" the address the user types to a known address.
There is a small conflict here since the name of the newly added layer is before it's address - we might need to change that order.
What do you think?
About 2 - I'm not sure how leaflet supports format that are not TMS so I'm not sure how easy this will be to add...
I'm also not sure why you defined this as a high priority enhancement, doesn't sound too useful to me...

**Comment by HarelM** [comment]
@zstadler still waiting for a UI proposition...

**Comment by HarelM** [comment]
It seems that there's too much data in the API, I don't see how to incorporate it in the current UI.
I'll add a link to the following address for users who want to find a map they can use...
I don't have another idea...
https://qms.nextgis.com/
