### ISSUE TITLE
Map's images return 404

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#291]
Maybe I'm missing something but the map's image returns 404.

For example: .../Hebrew/Tiles/13/4896/3333.png

What am I missing?

**Comment by HarelM** [comment]
Full address works:
http://israelhiking.osm.org.il/Hebrew/Tiles/13/4896/3333.png
Also secure:
https://israelhiking.osm.org.il/Hebrew/Tiles/13/4896/3333.png

Are you sure you have the right address? maybe a proxy issue?

**Comment by moshfeu** [comment]
Ohh, I'm sorry.. I meant, when I cloned the project and I run it locally.

**Comment by HarelM** [comment]
:-)
you'll need to create the map locally too in the relevant address for this to work.
What I do in order to test it locally is to create another layer and point the tiles address to the production server:
![image](https://cloud.githubusercontent.com/assets/3269297/21852835/4d1359b8-d81d-11e6-8744-542c289d545c.png)

Use the advance yellow button in the layers control.
Can I ask why are you running it locally?

**Comment by moshfeu** [comment]
The final URL should be:

    https://israelhiking.osm.org.il/Hebrew/Tiles/{z}/{x}/{y}.png

I exposed to the site some days ago and I saw that it's an open source and I want to play with it :)
I intend to use the service (I looked for something like this - especially the trip builder - it's very easy to plan a jeep trip that way) and maybe I will need to change something so I just want to make sure that I have a live project..

Thanks for the app and the help..

**Comment by HarelM** [comment]
No problem, please note that in order to be able to locally plan a trip you'll need to run the updater to create windows services etc.
Good luck!
Would love if you have any ideas worth implementing and you feel like contributing to this project :-).
Also let us know if the setup instructions are clear enough, and if you run into any issues...
