### ISSUE TITLE
Over-simplification when adding a way to OSM

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#296]
[Changeset 45338399](http://www.openstreetmap.org/changeset/45338399) was likely created from [trace 2337075](https://www.openstreetmap.org/user/Eilam/traces/2337075). 

Comparing the resulting path path with the original trace shows a significant over-simplification:

[<img width="320" alt="2017-01-23 11_19_45-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/22198145/e6f9f138-e15d-11e6-9d9c-93317b6b3016.png">
http://israelhiking.osm.org.il/#!/?s=BkoM2zzu2l
](http://israelhiking.osm.org.il/#!/?s=BkoM2zzu2l)

While the GPS recording reaches the peak, the path added to OSM is missing the peak altogether.

Notes:
1. In my opinion, it is likely that the peak is actually located at the turn of the trace: The hiker/s climbed to the peak from the south-east, turned, and descended in to the north-east. This is also consistent with the topography and the satellite imagery.
2. North of the peak, this changeset also added 2 connections between a previously-existing way and the new path.

**Comment by HarelM** [comment]
I haven't fully tried to debug it but I think the "self loop" at the top caused the path to be broken up at that point, there should have been left a trail to the peak though. 
This is not same issue as previous over simplification which was solved be reducing the tolerance.
I hope I'll have time to debug it over the weekend, I still need a good method to be able to see the results of the different parts of the algorithm, maybe I'll write a short function to spit out intermediate results to file to be able to see it over the map...

**Comment by HarelM** [comment]
Here is what I believe is a very similar behavior:
![image](https://cloud.githubusercontent.com/assets/3269297/22666695/4f19811a-ecc2-11e6-8cf0-5b7bcc56effd.png)
Image explanation:
Although hard to see this is the results of the self loops removal algorithm.
How the algorithm works:
Code can be seen here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/GpxLoopsSplitterService.cs
Pseudo code:
for each point in the line (will call it current point):
go backwards from current until the distance is greater than 30m (lets call this "prefix end point")
measure the distance between current point and the line ending with prefix end point.
if this distance is smaller than 30m means we have a self loop and the line should be broken.
This is how this looks after radial simplification since all the points are within the 30m tolerance.
![image](https://cloud.githubusercontent.com/assets/3269297/22668364/265a437a-ecc9-11e6-98ac-1efdea33c2d1.png)
Not sure how to handle this one, back to square one... :-(

**Comment by HarelM** [comment]
Will be handled as part of the improvements done for #267, the above image is no longer an issue.

**Comment by HarelM** [comment]
Results after new algorithm changes (ran on local database before this trace was added to OSM).
![image](https://cloud.githubusercontent.com/assets/3269297/23189503/c96b65f2-f89b-11e6-918e-f538f11bf0eb.png)
