### ISSUE TITLE
Backtracking not recognized

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#309]
backtracking is not recognized, resulting the following identification of a new track:
<img width="108" alt="2017-03-07 11_48_40-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/23677690/d08e91a8-0389-11e7-8962-c8eac8cb2373.png">

GPS track example - http://israelhiking.osm.org.il/#!/?s=aFXC3R9RoC

**Comment by HarelM** [comment]
@zstadler I'm not sure how to solve this one, your help would be appreciated:
The reason is as follows:
This is a classic T case.
It is first bloken to "_ L" lines in the first part of the algorithm.
The next part of the algorithm tried to prolong the "_" and the "L" according to original GPX.
the prolong starts from the end of the "L" and combine it to the upper road in the picture (so far so good).
Then it tries to prolong the start of the L along the gpx line and finds the end of the "_" and merge them.
The solution to this might be to try and prolong the end of each L and after that only to try and prolong the start of each L.

But the following case is what kept me awake for a few nights:
Before prolonging:
![image](https://cloud.githubusercontent.com/assets/3269297/23817145/97617d06-05f9-11e7-9fba-d34149a0092e.png)
After:
![image](https://cloud.githubusercontent.com/assets/3269297/23817133/821db716-05f9-11e7-80c5-da3803161c18.png)
The code for prolonging a line just adds another point at the end of a segment to keep the algorithm simple, but it follows the GPX trace until it find a line to prolong to.
Not sure I made myself clear enough, a phone call might help...
