### ISSUE TITLE
Can't Save track on iPhone 

### ISSUE THREAD

**Issue by hesher** [IsraelHikingMap/Site#311]
When opening a track from a link on an iPhone you can't save it to the device and export it to other applications

**Comment by HarelM** [comment]
Is it possible from other sites? I can imagine this is an iPhone limitation, not sure there's something I can do, I'll look into it nevertheless.

**Comment by hesher** [comment]
Of course it's possible from other sites. It's just sending a file to the browser. Probably something in the headers of the response.

**Comment by hesher** [comment]
For example, gpsies: http://m.gpsies.com/map.do?fileId=wbaixdkpluwctevu

**Comment by HarelM** [comment]
Unfortunately, I think I won't be able to support this.
The following is an issue with the framework I'm using:
https://github.com/eligrey/FileSaver.js/issues/12
The way gpsies work is different from the way IHM works and I believe this gap can't be fixed by me, it need to be fixed by Apple.
There's also a comment in the main page about interactions which also creates an issue.
https://github.com/eligrey/FileSaver.js
I'll see if there's a workaround I can introduce that might solve this, but I'm skeptic...
In any case you can share your work and download it using a PC, later on you can send this file using your e-mail or something (I know this is less than ideal).
We are working on ways to send the route directly to some mobile apps but it will take some time for this to be ready.

**Comment by hesher** [comment]
Okay. Thanks for trying!

**Comment by HarelM** [comment]
@hesher I don't have an iPhone, I can test it on my iPad once I'll get it to upgrade to latest version.
In the linked issue the problem seems to be resolved by updating to latest Safari,
Can you confirm this is now solved? if so, please close this issue.

**Comment by hesher** [comment]
Works!
Also, I gotta say. The app became super snappy lately. Great job.

**Comment by hesher** [comment]
I just noticed it saves the file but it doesn't know which file type (because the response doesn't have a file name)?

I'll check the response on a desktop to see which header it's looking for as file name.

**Comment by CinnamonRage** [comment]
Is gpsies code different from IsraelHikingMap? I notice I can download from gpsies on iPhone but when I copy the code from here (IsraelHikingMap) I still get a file with "unknown" as its name and "data" as it's file type.

**Comment by HarelM** [comment]
Yes, the gpsies site is not a SPA, and files are downloaded directly from the server. In IHM the files is downloaded from the client side and depends on browser support.
Safari had poor support for this and that's what's causing the issue.
If you have an idea how to fix it I'd love to know...

**Comment by CinnamonRage** [comment]
@HarelM Not found anything yet, unfortunately. I have a [post](https://forums.developer.apple.com/thread/91631) on Apple's Safari developer forum but not hopeful of a response. I also submitted a bug to Apple's bugreport.apple.com site but they required a sysdiagnostics dump even though it won't tell them anything more than all the links I sent to them from FileSaver.js demo page and issues pages.

**Comment by HarelM** [comment]
Well, I can't say I'm surprised. This is by no means a new issue. I hope they'll find the time to fix it...
