### ISSUE TITLE
Printout (both PDF and printer) is blurry

### ISSUE THREAD

**Issue by roniyaniv** [IsraelHikingMap/Site#324]
Attached example of printout I got.

[Israel Hiking Map.pdf](https://github.com/IsraelHikingMap/Site/files/847679/Israel.Hiking.Map.pdf)

AmudAnan, for contrast, has quite sharp printouts.

**Comment by HarelM** [comment]
I don't think it's blurry, looks quite good to me, but I might be used to it.
The quality of the map is defined by the quality of the tiles.
We are planning to migrate to vector format which might improve the quality in the following issue:
https://github.com/IsraelHikingMap/Map/issues/93
But I can't promise anything.
Since this is an open source project with no budget and no funding I don't see how we'll be able to make it better as it requires more servers to create deeper zoom layers.
You can follow the instructions on the map project and try and create a local map which might have better quality if this is something you truly need.
Sorry I don't have a better solution :-/

**Comment by HarelM** [comment]
No follow-up, closing...
