### ISSUE TITLE
Feature suggestion: allow splitting and merging routes

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#326]
When you click a WPT, in addition to the coordinates and delete button, add a split button.
This will  result in the current route being split into two, differently colored ones.
This would allow shortening routes, splitting long routes to several lags, and maybe, in later updates. uniting routes.

**Comment by HarelM** [comment]
While splitting is fairly simple uniting isn't. The problem with allowing just splitting is that you won't be able to undo since undo is saved for each route and not for the entire application (which might be confusing, but this is the current implementation).
So once you split a route you won't be able to unite it back which is not a great UX.
Implementing both split and unite is hard and I'm not sure we want to go to a full editor mode like OSM (which is great but not very intuitive and easy for users)...

**Comment by valleyofdawn** [comment]
I think splitting is useful in its own right. Maybe you can add it and
manage the undo issue later.

**Comment by mk4th** [comment]
+1 for split and unite options.

If you want to keep simplicity and to be more design platform than editing platform, you can add it under "Advanced" toolbar for the times it needed.

**Comment by HarelM** [comment]
@mk4th please see my comments above about uniting, as I said, splitting is fairly simple.
If you can suggest a UX that will keep things simple but also support these features I'll be happy to implement it. I don't have a good idea right now.
Also keep in mind that using the right click or double click is not intuitive any more and should be avoided - this limitation comes from the "mobile first" approach, which I tend to agree with.

**Comment by HarelM** [comment]
Here's a suggestion, let me know if you think this might be useful and intuitive:
Splitting two routes can be done by clicking on a point on a route and click on a scissors icon in the point's context menu which will create two routes - Not sure what undo will do in this case, but let's assume it will not remove a route.
When two routes have a starting and ending point on the same location, the context menu will allow to unite them. This should only work for start an end point of different routes.
This means that a user should be able to reverse a route more easily.
Adding the reverse to the start and end point of a route might help?
Thought are welcome!

**Comment by valleyofdawn** [comment]
This sounds excellent. We should think on what to do when the merged routes have opposite directions and how close should be 2 points to be considered one location. So you can click either one of the two end points to unite them?

**Comment by HarelM** [comment]
That's what I said about bringing the reverse route feature to the start and end point context menu - If you can reverse the route from the end/start point you can decide which route to reverse in order to merge.
My main concern is that the user won't know how to enable it in case it's not enabled due to wrong direction...
In any case, we might want to change the unite threshold according to zoom or we can use an arbitrary distance such as 30m. This won't change the UX much...

**Comment by valleyofdawn** [comment]
OK, that would work.  I wouldn't disable the merger if the directions are opposite though. 
Do it arbitrarily and let the user reverse course retroactively If they need to.

**Comment by HarelM** [comment]
Sounds good, I'll do it after I finish the migration to angular 4. I hope I'll be able to finish it this week.

**Comment by HarelM** [comment]
Coming soon :-)
![image](https://user-images.githubusercontent.com/3269297/28179465-b5d4b500-680a-11e7-860a-abaf3314164f.png)

**Comment by valleyofdawn** [comment]
Good job!
Undo following union of the tracks deletes them both.
I understand reversing this step is hard. Instead, disable the undo button. The user can manually split the tracks, butter then losing all your work.

**Comment by HarelM** [comment]
Can you specify a scenario that both are delete? I only see that the merged part gets deleted.
Disabling undo is not an option, the common solution used in other places will be to make undo globally instead of per route like it is today. Again it has its up and downs.

**Comment by HarelM** [comment]
I think the height graph is now broken :-/

**Comment by valleyofdawn** [comment]
https://photos.app.goo.gl/48gXJjPImdeoFy3C2

**Comment by valleyofdawn** [comment]
I see you have it disabled for the split operation.
I always assumed the undo was global. I imagine few people would edit a new track, then go back to an old track and expect they can undo their last actions there.

**Comment by HarelM** [comment]
Yes, I can't remember why I decided to implement it the way I did, probably worth changing it now since we have operations that are "cross-routes".
Chart broken was a bad search and replace due to test site modifications, solved on the service, I now see that there are issues with chart refresh after merge, I'll fix it.

**Comment by HarelM** [comment]
Closing this in favor of #402
