### ISSUE TITLE
Can't delete shared track

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#332]
Trash can icon non-responsive. Chrome on Windows.

**Comment by HarelM** [comment]
Thanks, I'll fix it tonight.
The issue is both with delete and update (although the UI said otherwise).
Helpful articles:
http://stackoverflow.com/questions/39801670/http-put-in-angular2-to-net-core-web-api-gives-http-401-error-from-the-prefligh
http://www.ryadel.com/en/error-405-methods-not-allowed-asp-net-core-put-delete-requests/

**Comment by HarelM** [comment]
Same issue as before:
See #262.
Go to IIS manager, modules and remove WebDAVModule.
Can be also done using web.config:
```xml
<webserver>
...
  <modules>
    <remove name="WebDAVModule" />
  </modules>
```
