### ISSUE TITLE
Manage route properties

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#35]
It would also be nice to be able to rename routes - the first one is always "Route 0" while following ones can be named.
Maybe just attach one button to each route which would open a dialog box that would allow you to:
1) show/hide
2) change color (maybe also width and transparency)
3) rename
4) delete

**Comment by HarelM** [comment]
Yes, I Agree, I was thinking about it as well. Route length should also be there and maybe the height graph. I'm still thinking how to design it user interface wise - as a tooltip like the info or should it open from the layer controller like a "carot" similar to google calendar? Should the routing type be inside it as well? you are welcome to share your thoughts as I'm still pondering about it.

**Comment by HarelM** [comment]
![image](https://cloud.githubusercontent.com/assets/3269297/9136042/f15857f6-3d1b-11e5-81d2-e407f5c41245.png)

Initial thought.

**Comment by HarelM** [comment]
Since the left side of this window is pretty static an would not be used a lot by the user, a better place maybe in the layers control - instead of the delete button so that when the user clicks on it a dialog will popup like adding a new route.
Leaving the graph and length to get updated while the user users the map.
