### ISSUE TITLE
Reduce downtime during DB updates

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#350]
Required for completing IsraelHikingMap/Map#111

**Comment by HarelM** [comment]
@zstadler I have tested and saw that it's working as expected.
I would like you to update the script that updates the database to use the following line (this is currently what is written in `UpdateDB.bat` and since it reflects the new API I prefer not to keep this file as a contract:
```
curl -F "file=@%1;filename=israel-and-palestine-latest.osm.pbf" http://israelhiking.osm.org.il/api/update/
```
This assumes curl is installed on the server (probably can be done with wget if you prefer, haven't tested it).
filename doesn't really matter.

This will only work when executing on the server for security reasons.

**Comment by zstadler** [comment]
@HarelM,

I'd rather minimize the changes to the Map repository as a result of changes in the Site repository.

The fact that the internal implementation of the Site DB update was changed without a need to change the inter-repository interface is an indication of the interface's usefulness in decoupling the implementation details between the two repositories.

**Comment by HarelM** [comment]
I'd rather not keep an interface between two systems that is local file systems location dependent.
The fact that there was not a need to change the interface is just an indication that I tried to maintain the current interface.
The new interface is what I tend to keep in the the future unlike what I see is a temporary one which was 
no more than a patch, IMHO.
I don't see how changing one line of code is the Map repository to migrate to a new interface is problematic...

**Comment by zstadler** [comment]
If I understand correctly, for security reasons the update can only be done from within the server.
I do not see the issue of referring to the file system of the shared server.

**Comment by HarelM** [comment]
You understand correctly.
Leaving philosophical arguments aside (As I see their flaws now), would you be willing to change the interface?

**Comment by HarelM** [comment]
@zstadler I want to close this issue but I haven't seen a db update call in the last 24 hours, is that possible?

**Comment by zstadler** [comment]
Yes. This is the case, as a result of long update runs in Hebrew and English.

**Comment by HarelM** [comment]
Finally done :-) Great work @zstadler!
