### ISSUE TITLE
hashbang issues

### ISSUE THREAD

**Issue by SwiftFast** [IsraelHikingMap/Site#352]
When I open one of these links, then close it and open the other, the map sometimes zooms to the location that was just closed, and not to where it's supposed to be.

http://israelhiking.osm.org.il/#!/18/32.6855/35.0791

http://israelhiking.osm.org.il/#!/17/32.6831/35.0871

Firefox 45 ESR.

Moved from IsraelHikingMap/Map#138

**Comment by SwiftFast** [comment]
The issue could be more general: Sometimes when I open the map, I see the place I've last been into, and not the place in the hashbang.

**Comment by HarelM** [comment]
I'm in the middle of the migration to Angular 4 (#349), unfortunately I can't complete it due to a serious bug in the angular framework. 
The bug here is probably due to race condition.
I'll keep it open until I finish the migration to make sure it doesn't happen after the upgrade.
Thanks for reporting!

**Comment by HarelM** [comment]
We also probably need to support old links that do not have the "!" after the "#" - this is a bug that was introduced as part of the migration to angular 1.6.x.

**Comment by HarelM** [comment]
@SwiftFast Can you please check if you are able to reproduce the issue with the new site? if you can't please close this issue.

**Comment by SwiftFast** [comment]
I can no longer reproduce this, and the new site seems immediately reactive to manually changing the coordinates or the zoom level.
