### ISSUE TITLE
NetTopologySuite.IO.Converters - Converters not exist 

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#353]
> CS0234	The type or namespace name 'Converters' does not exist in the namespace 'NetTopologySuite.IO' (are you missing an assembly reference?)	IsraelHiking.DataAccess	**\Site\IsraelHiking.DataAccess\ElasticSearch\ElasticSearchGateway.cs	10	Active

It happened after I installed the vs 2017 and upgraded the project if it's matter.
I tried to re-install the package but it's the same. 
The version is 1.14.0 (It was 1.15... and not worked as well).

Any advice?

Thanks!

**Comment by HarelM** [comment]
I have checked-in a lot of changes yesterday.
Have you followed the installation instruction to install the local NuGet packages before trying to compile?
I'm working with VS 2017 and I don't think you can compile it now with VS 2015.
If the setup instructions are relevant and good enough please close this issue, if you, see if you can update them and send a pull request.

**Comment by moshfeu** [comment]
OK, I missed the new documents. After I re-cloned it and followed the docs it's all working fine.
A question: In the appsettings.json file there is a property called: `listingDictionary`. Without touching anything the value is `d:\\`. I changed it to `c:\\` because I have no d drive in my comp. My question is what it is for? The local files?
Another point is to adding a task in gulp that transpile the typescript into javascript. I did it by just saving a .ts file, but maybe it should be part of the process.

**Comment by HarelM** [comment]
Both points are valid.
The directory listing can be `c:\` no reason not to change it - when surfing to http://israelhiking.osm.org.il/hebrew/tiles/ you can see the directory listing, this settings is to allow testing it locally when developing.
Having said that, I think a `d` drive is important when you want to delete all files from your computer and you don't know which are import and which are not. I keep all the files that I need on `d` so if I need to format my PC I know which files to keep. But that is unrelated to this discussion.
Typescript files are transpiled when saving, I have opened some bugs to visual studio since it's a problem there and not with my code.
Having said that, angular-cli removes this need completely, but as I said I still can't migrate to Angular 4 so it's kinda in the middle, not sure what to do with it as I'm stuck... any ideas are welcome.
