### ISSUE TITLE
Opening the User Data dialog takes 20 seconds or more

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#375]
Probably due to the large number of recordings I have.

Please let me know how how can I help (profiling, etc.)

**Comment by HarelM** [comment]
Can you try and run a profiling session on your browser?
Press F12 to open developer tools and go to performance.
The following is a screenshot of Chrome.
![image](https://user-images.githubusercontent.com/3269297/27560309-655adab4-5acc-11e7-9db0-522a98966085.png)
Another options is for you to login with your OSM user in the browser on the server and I'll remote connect and try to run profiling there...
Let me know which you decide.

**Comment by HarelM** [comment]
Thanks for the help! I'm able to confirm that the issue is due to large number of object (how many do you have there it total??).
When filtering the view a bit close and open are working OK.
Which means that I need to add client side pagination in order to support this amount of items.
I'm sorry for the inconvenience, I hope I'll be able to fix this soon.

**Comment by HarelM** [comment]
You have around 500 traces!! this is a lot... In any case, I added pagination, I think it's a lot better now...

**Comment by zstadler** [comment]
Thanks!

Yes, I have been mapping for a while...
