### ISSUE TITLE
Enable deletion and hiding of all POI's

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#38]
I could not find a way to delete or hide all POI's.

When POIs are loaded from a file that includes dozens of POI's, it is not practical to delete or hide them one-by-one.

**Comment by HarelM** [comment]
I'm not sure I understand, but I think you can choose the markers in the layers control, then click the clear button on the left side...?

**Comment by valleyofdawn** [comment]
How about shift-dragging to select multiple POIs, or even route vertices, then hit delete?

**Comment by zstadler** [comment]
Indeed there is a way to delete all POIs. I think it is not very accessible.

What do you think of adding a trash-can icon next to "Markers" in
"Advanced" mode?

**Comment by HarelM** [comment]
Markers is a special layer, I can't let the user delete it because there is only one markers layer and if the user deletes it I should ask him what kind of layer he wants every time he creates a new route, which I think is even less friendly.
I don't want to get into selection using a mouse drag since mouse drag is saved for moving the map.
I don't have a good solution, I know it is not accessible... :-/

**Comment by zstadler** [comment]
The proposal was for a trash-bin on the Markers layer that will delete all
layer contents, not to delete the layer itself...

**Comment by HarelM** [comment]
I don't want to place two buttons in different places with the same functionality, it feels wrong...
