### ISSUE TITLE
When posting to FB the IHM layer is shown rather than the current one

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#388]
e.g. here:
https://www.facebook.com/groups/lost.geographers/permalink/1400940166692324/
Should show the Sat image.

**Comment by valleyofdawn** [comment]
Seem like only when a route is not included.

**Comment by HarelM** [comment]
I'm guessing you mean the screenshot, right?
I can't use google earth as a background since it does not use the slippery tiles format.
@valleyofdawn Can you verify this is the case and that it's not relevant to empty route?
If so, please close this issue as I can't use the google layer to produce screenshots.
P.S. you can also check how an image will look without posting on facebook by using the following API:
https://israelhiking.osm.org.il/api/images/*share-id*.
The following in your example:
https://israelhiking.osm.org.il/api/images/Oudi7jRXU1

**Comment by valleyofdawn** [comment]
Google earth indeed.
