### ISSUE TITLE
Issues with missing routes algorithm

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#395]
See attached file for some examples - one is failing while the other gives mediocre results.
[MissingPartsBadExamples.zip](https://github.com/IsraelHikingMap/Site/files/1134902/MissingPartsBadExamples.zip)

**Comment by zstadler** [comment]
These are two separate issues.

The failure on `Yaron-error.gpx` is a result of a malformed file. The file also fails to load on the site for the following two reasons:
1. The `<gpx ... >` statement is missing a critical XML namespace declaration: `xmlns="http://www.topografix.com/GPX/1/1"`
2. The file contains an orphan `<rte/>` entry at its end.

Hopefully, this is a result of some manual editing of the file and not bad file creation by Trailze.

Even after fixing the above issues, the current OSM DB is inadequate for testing both [`Matan-BadResults`](http://israelhiking.osm.org.il/#!/?s=LAVEUVEthj) and [`Yaron-error`](http://israelhiking.osm.org.il/#!/?s=BjCkpXpbIR) examples because the entire length of the examples is already mapped. It would be useful to capture the date where the issue was observed and obtain the appropriate OSM DB snapshot.

**Comment by HarelM** [comment]
I see you have a local version that you can debug with :-) :-) :-)
The original mail was sent at 19/04, you should have it too.
I believe there are version of the pbf inside the IHM.org.il backup folders on the server that might help.

**Comment by zstadler** [comment]
I've used the site and a text editor to analyze the examples of this issue, not a local version :-)

**Comment by HarelM** [comment]
Asked the person who sent me the file, he didn't manually edit it. If you have trailze you can check but I suspect they create or used to create a bad XML file...
Which leaves only the algorithm simplification issue, which is probably related to tolerances, which will be hard to solve...

**Comment by HarelM** [comment]
Closing this for now as I don't plan to reproduce this, let's see if someone else encounter an issue with this.
This feature currently is almost not in use, unfortunately...
