### ISSUE TITLE
Can't save track on in chrome on android

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#398]
![image](https://user-images.githubusercontent.com/689201/28204554-1f5cc1b2-6887-11e7-8356-4ff14e04332b.png)
![image](https://user-images.githubusercontent.com/689201/28204561-27b3e34a-6887-11e7-9860-dc43d6fe96c4.png)

**Comment by HarelM** [comment]
Apparently the file is being saved to the file system and is a valid file, for some reason the OS thinks there's a problem with the download, I'm not sure how to solve this...

**Comment by valleyofdawn** [comment]
So you got this too? I think its a major bug. Where can we find people who might know?

**Comment by HarelM** [comment]
I get this too, yes. I have no clue how to solve this. See the linked issue to the framework I'm using to save files in the browser...

**Comment by valleyofdawn** [comment]
Should we ask for an android specialist on facebook? where do coders go for advice?

**Comment by HarelM** [comment]
Mainly Github and stack-overflow. The main problem here is that I can't pinpoint who's to blame - the browser, my code, file-saver's code, android OS.
This needs some attention and a simpler reproduction scenario and it might take long to do so. Since I kinda feel I can't solve this on my own (meaning it's not a bug in my code) I don't have a lot of drive to dig into it...

**Comment by HarelM** [comment]
Seems like this issue has a workaround here:
https://github.com/eligrey/FileSaver.js/issues/330
Reading there implies that this affects only android 7...? I really don't want to take the horrible code written there unless I absolutely have to...

**Comment by HarelM** [comment]
Solved, currently published to test site.
