### ISSUE TITLE
Add the option to add POIs layers 

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#404]
The user could add a layer just like Wikipedia and Nakeb. Of course you will publish the JSON schema that the URL should return.

**Comment by HarelM** [comment]
I don't think we should define a new format, there are too many already out there.
A possible solution would be this leaflet-plugin:
https://www.npmjs.com/package/leaflet-plugins
https://github.com/shramov/leaflet-plugins
The name is a bit too general, but what can you do...
Which allows to open files and use them as vector layers.
The problem here is that the user would probably want to save these layers for future uses which might be a bit tricky now that we store the layers on the server, but if the file is hosted somewhere else it should be easier...

**Comment by HarelM** [comment]
One can create a GPX file with all the relevant data and open it in the site - if the GPX file has images links they will be displayed. I think this issue is now covered with current functionality.

**Comment by moshfeu** [comment]
Sounds great!
