### ISSUE TITLE
Simplify Wikipadia API usage

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#415]
Currently, Wikipedia API is used at two levels. The [top-level query](https://github.com/IsraelHikingMap/Site/blob/2160fae531ad70a152e8c8d011a38dcecfcfba95/IsraelHiking.Web/sources/application/services/layers/wiki-markers.layer.ts#L53) is looking for articles within a radius, and the [second-level query](https://github.com/IsraelHikingMap/Site/blob/c736fb2edad18fc097d7dcad31d57cb0193f66c6/IsraelHiking.Web/sources/application/components/markerpopup/wiki-marker-popup.component.ts#L58) is extracting information about an individual article.

According to [stackoverflow](https://stackoverflow.com/questions/24529853/how-to-get-more-info-within-only-one-geosearch-call-via-wikipedia-api), the two levels can be combined into a single API call.

Can this approach simplify the client code?

**Comment by HarelM** [comment]
I'm aware of this possibility, Since most of the time a user will not open most of the markers I wanted to make the initial call faster and remove data that is not needed.
I also believe this optimization applies to the concept of POI in general, not just Wiki and thus used in Nakeb as well and I have created the relevant framework to support this.

**Comment by zstadler** [comment]
Sounds right
