### ISSUE TITLE
Allow direct import of shared planned tracks from the IHM site to the OruxMaps app

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#422]
**Aim**: to simplify the transfer of planned tracks to the popular app.
**Requirements**: providing an API that would allow searching tracks based on username, current location, text in the track name and possibly the type of activity.
Better translation of the current interface (shown) to Hebrew.
**Example**: the API provided by the GPSies site for the same purpose ([link](https://www.gpsies.com/api/GPSiesAPI_en.pdf)).
**Questions**: should we ask users to designate some tracks as non-searchable?
Should we allow users to only search for their own tracks?
The "activity type" field is very useful when you are looking for somebody else's tracks, should we include it in the share options?
![gpsies import](https://user-images.githubusercontent.com/689201/29742568-4308779e-8a8a-11e7-987d-ef85814a230e.jpg)

**Comment by HarelM** [comment]
A user can share a route, open it on my mobile, save the file on his device and open it in Orux - I think this is the simplest way.
Since there isn't a way to send Orux the track and the user needs to search for it in a screen that is very not user friendly I have decided not to implement this feature, sorry.
