### ISSUE TITLE
Simplify aggregate POI symbol

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#432]
Too visually loaded IMO.
My suggestion is below to set it apart from the Wikipedia ones, and simple circles if the  Wikipedia POIs are incorporated into the general POIs.
I like the shaded ones better than the semi-transparent. 
![presentation1](https://user-images.githubusercontent.com/689201/30117703-a9b9781a-9329-11e7-848f-4bdba67e3391.jpg)

**Comment by HarelM** [comment]
Need a designer.

**Comment by HarelM** [comment]
I like the circles and their border, creating the star you suggested will be very hard as all the components now do not require an image - the circle is just a "rounded rectangle" which is fully supported in all browsers....
I can remove the star if you think it will make this layer less visually loaded (keep the W only for wikipedia), but I don't think this is the root cause of your complaint, correct me if I'm wrong.
![image](https://user-images.githubusercontent.com/3269297/31316330-d447710e-ac33-11e7-9d35-33ee402aa162.png)

**Comment by zstadler** [comment]
I also feel good with the current representation. It is also good that we use the same graphical language as other sites that aggregate POI icons using leaflet.

**Comment by HarelM** [comment]
I don't see a good reason to keep this open, there are many places a designer can improve, this is just one of them...
