### ISSUE TITLE
Using right-clicking in the PC version of the site for a context-dependent menue

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#437]
It's time to reconsider.
Using the right mouse button (on top of the standard method) would make it snappier for high-volume users.
This would allow easily adding a public POI for instance, reverse course, change route attributes, etc.
Recently the iD editor also reverted to right-click use, as do Google maps, Bing maps and Mapa.
We need to consider our power users, not just noobs. 
This should come on top of the regular way, not instead of it.
It seems like most users plan their trips on a PC, but similar functionality can be achieved with a long press on a mobile device.

**Comment by HarelM** [comment]
If you want to me reconsider, you'll need better arguments.
OSM editor is extremely hard to use - I reticently found myself scratching my head in order to split or merge a route - and I'm no OSM junior - this is just bad user experience. 
Right click context menu it not intuitive and most of our site users will not use them.
40% of our users use the site from a mobile device - right click on mobile is discouraged.
Currently most of the context menus are accessible from left click.
The only case you have here is for adding a new POI by right clicking the map - this argument is not strong enough, sorry.
The user experience I hope for POI is loading a route that you recorded and converting points to POIs - this case is almost as easy as right click.
The case of adding a POI "out of the blue" without any data to support it should be an edge case and for that you can have 3 clicks instead of 2 clicks. again a very weak argument.

**Comment by valleyofdawn** [comment]
For instance.
To change the color of a track you need now to needs to:
1) Open the layers window
2) turn on advanced features
3) locate the track and press settings

These all require getting to know the interface, and clicking through distinct areas of the screen, whereas right clicking would make it immediate.

**Comment by valleyofdawn** [comment]
Here's a demo from Google my maps. 
[demo.zip](https://github.com/IsraelHikingMap/Site/files/1284832/demo.zip)

**Comment by HarelM** [comment]
Let's remove google maps from the discussion here - they have a completely different application for mobile devices which allows them split the user experience between the two platform, we don't have their resources.
I can add a button to open advanced configuration from the start and end marker of a track - this will not require right click, I'm not sure this option is that important to add it to that context but it's possible if needed.
I think changing route color, weight etc is for advanced users who probably have the layers pane open most of the time and advance setting on, so again - about one click, still no need for right click...
I prefer to add keyboard shortcuts for advanced users, much like `Crtl+F`, `Crtl+Z`, `Crtl+O`, and `Crtl+S`, that exists today.

**Comment by valleyofdawn** [comment]
Changing the track color is a fun and sometimes necessary thing even a starting user can enjoy. The problem is that it is not necessarily associated with the start and end of the track and the user has no reason to look for it there. As long as we don't remove any options from the mobile site, adding another access to them through right clicking only on the PC site won't hurt. 
Same thing with the public POI, the user won't necessarily think of adding a private one and then converting it. If right clicking is an abomination in your book, maybe long pressing or double clicking on an empty spot would be OK?

**Comment by HarelM** [comment]
Let it go man... Double click and long press had the same unintuitive value as right click.

**Comment by zstadler** [comment]
We already provide limited functionality on mobile, which is fine with me.
There need not be an equivalent for right click on mobile, just like the edit button is not available there.

**Comment by HarelM** [comment]
Which edit button?

**Comment by zstadler** [comment]
The "Edit in OSM" button

**Comment by HarelM** [comment]
That's because their site doesn't support mobile.
In any case, I haven't found a good reason to introduce right click from the arguments above.

**Comment by zstadler** [comment]
Let's agree that "There can be a right-click on the desktop" before jumping to the "there is nothing useful to do with a right-click" conclusion.

P.S., iD is available on the mobile, even on a smartphone:

![screenshot_20170909-003406](https://user-images.githubusercontent.com/1304610/30232270-98f31606-94f7-11e7-84e4-745c43e766a7.png)

P.P.S.,
Even if it was not available on mobile, or if it is not very useful on mobile, it would only show that some tasks and behaviors and not fit for mobile. I also believe users do not expect them.

**Comment by HarelM** [comment]
This argument is leading no where.
iD is a bad example as the UX is not intuitive, I don't want our site not to be intuitive.
Right click requires the user to "guess" the he need to right click.
Most web interfaces today do not support right click for a good reason.
When there's an element on the screen and you click it - it's intuitive.
I'm not planning on maintaining code for 3% of the users because you think right clicking can reduce some clicks.

**Comment by zstadler** [comment]
This is not about iD, it is about our site and the availability of right-click on the desktop.

Right-click is used on Bing maps
![image](https://user-images.githubusercontent.com/1304610/30233041-bf8dd6a8-94fb-11e7-9599-c8ad118894e6.png)

on Google Maps
![image](https://user-images.githubusercontent.com/1304610/30233050-ce5562d2-94fb-11e7-9d69-62c802199b2d.png)

on OpenStreetMap browser
![image](https://user-images.githubusercontent.com/1304610/30233063-dee12fa0-94fb-11e7-8b3c-7e880f135a36.png)

on Mapquest
![image](https://user-images.githubusercontent.com/1304610/30233078-f3b834fa-94fb-11e7-8ce2-ae8ae68d5dbe.png)

It is difficult to find an online map that does not use right-click on the desktop.

**Comment by HarelM** [comment]
As asked before, please specify why we need it and not why other decided to use it.
Please also remember that I'm the only one who currently maintains the site.
Since my time is limited and I need to maintain both mobile and desktop site (which is not the case for some of the examples provided above as they have another app for mobile) I prefer to keep the code base the same as possible.
Also please remember the mobile first approach which dictates that an interface that will be intuitive and easy to use on mobile device will have the same effect on desktop client.
