### ISSUE TITLE
Simplify and automate translation flow

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#441]
The [current translation flow](https://github.com/IsraelHikingMap/Site/wiki/Adding-New-Text-and-Updating-the-Translations#uploading-texts-for-translation-to-zanata) is complex, manual and therefore, error prone.

Ideally, the developer will be able to invoke 2 autonomous tasks:
* Extract the appropriate content and push to the Zanata server.
* Pull translated content from the Zanata server and integrate into the project.

⁠⁠⁠The [Zanata Command line client (CLI)](http://docs.zanata.org/en/release/client/) may be useful for this purpose.

**Comment by HarelM** [comment]
The following is probably a better fit to how the project works and needs less environment setup (work on npm directly which means no extra setup for the developer):
https://www.npmjs.com/package/zanata-js

The following might also be relevant for this issue in order to remove gulp tasks completely:
https://github.com/ngx-translate/core
It can also reduce the need to convert the .po to json which might reduce complexity too.

Having said that, Zanata needs credentials that can't be saved in git which might prove annoying...

**Comment by HarelM** [comment]
Just a delight now.
Translation is automatically uploaded to Zanata, browser is opened with two tabs with only the relevant missing translations.
Download is also automatically and compilation as well when user finishes the translation and clicks on the relevant task.
I'll update the translation wiki.
