### ISSUE TITLE
OSM POI types to include 

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#454]
Let us add POI types we'd like to add and remove based on our preferences and those of the users for the next release.
I think we should decide on the max number of types per category, not to overwhelm the user.
Is 5 good? This is what we have under "water"

I am missing peak, gate and drinking water.
Under history I'm missing historical site, things like military posts from 1948, battle sites, historical buildings etc.
Under natural we can have a geological POI

**Comment by valleyofdawn** [comment]
It seems like we need to think of nameless POIs. Trees are useful for planning jeep trips, taps useful for planing bike trips, but both usually don't have names. Do we include them?
Gates likewise?

**Comment by HarelM** [comment]
They are mapped out, I don't think they need to be a POI.
I think naming is a good filter for non interesting POIs.

**Comment by valleyofdawn** [comment]
I tend to agree. So you say we should remove the trees too?
On the plus side:
a) when planning a desert bike or walking trip, it would be useful to light up all the water sources, so that you can plan it moving from one to the next.
b) Including this taps would encourage mapping them.

**Comment by zstadler** [comment]
I think some map features are worth adding to the map, but should not be a POI in the full sense of the word.

For example, gates and trees. We would like to see them on the map, but I see little value in searching for them. 

Where is a need to add such features to the map, but this is a different issue and a different flow.

**Comment by HarelM** [comment]
Trees with names are valid POIs, IMO.

**Comment by valleyofdawn** [comment]
Why so? Few have names, and those that do just specify the species, instead of using the correct tag.

**Comment by YGMZ** [comment]
As of now most of the POIs are just entities already seen on the map.
When looking into them, they do not give any more info then seen on the map, or indication/feeling that they are really of interest.
See Adulam region, in which every ruin/arch. site/cistern (which is already indcated on the map) is also a POI.

I suggest the following:
option (1): create a tag in OSM indicating the entity as POI (or IHM POI some thing like IHM_POI = yes...), option (2): define filter for POI as an entity with a description (rather than name as of now)

Note: option (1) requires the user to define (when creating a point) if it is a POI or just a point added to map (can be done using "radio button"...)

**Comment by HarelM** [comment]
While the fact is that there is little data in the newly created system does not mean I want to filter out the fact that the data is missing - instead I want users to feel the need to add data.
See my comments here: #512

Regarding you proposal - OSM tag should be discussed in the OSM forum (But I don't think we should litter OSM with tags related to this project).

While this might seem annoying the bottom line is that I want users to add data otherwise the information will not improve and the data will not be added...

**Comment by zstadler** [comment]
In POI edit mode clicking on a map location of a ruin/arch. site/spring/... enables the user to upload information to the appropriate OSM element.

In light if this recent change, I suggest we will consider showing POIs only when there is either a name, a description, or a picture.

On the other hand I'd like to see in the future the ability to add anonymous items to the map without requiring a name, a description, or a picture. Element types to consider are barriers, water-wells, springs, etc.

**Comment by HarelM** [comment]
@zstadler This is the current state, I'm not sure I understand your suggestions (not the future one).
@YGMZ suggests to hide POI without a description or an image - POI which only have a name.

**Comment by zstadler** [comment]
IMO,
* All of the above is not for immediate action. 
* Issue #512 is the appropriate place to discuss representation and editing experience of POIs with no description or image.

**Comment by HarelM** [comment]
Issue #512 has been recently resolved.
I feel the current cover of POIs types along with the merging algorithm is producing nice results.
i.e. I don't think there are missing POIs and I don't think there are too many.
I vote to close this issue and reopen it or open a different one in case there's an actual need.

**Comment by HarelM** [comment]
After reading the comments again, I still don't understand what are the requirements if I'm to implement this.
In light of changes that were made in the site it might be that this thread is somewhat out-dated (for example showing which POI has data, the ability to add image to private POIs etc.)
Since we introduced the POI layers half a year has passed and I think we are at the position of reviewing this issue.
I suggest using the following template to define new requirements:
**As a user I would like to ___ so that I would be able to ___** (of course more explanations are welcome).
This will clearly define what is missing in terms of user-experience.

**Comment by valleyofdawn** [comment]
I agree with HarelM that it's time to reconsider.
Our users are signaling us that they want to introduce gates through our POI interface and not the OSM editor.
One example of several:
![image](https://user-images.githubusercontent.com/689201/57073041-815bcb80-6ce8-11e9-854d-8cba403d81d2.png)

1) As a user I would like to have a barrier POI category so that I would be able to add open, closed, and closed to motor vehicles gates
2) As a user I would also like to have a drinking water option under the water category. I would like to be able to light it up separately from the water POI category.
3) I would also like to have a road danger category, with imppasable, dangerous and passable values, this won't show up on the map itself. 
4) I would like not to have a default category, but be forced to choose one myself before saving, so that I won't be tempted to add it as a tourist attraction because I'm lazy or a novice, or not that bright.

**Comment by HarelM** [comment]
It will be better to discuss this in one of our meetings as I believe POIs which do not have description, title and image (or that setting it would be awkward) should be handled differently than "interesting" POIs (the POIs which currently exist).

**Comment by valleyofdawn** [comment]
Sure, it deserves serious discussion. 
Bare in mind that many viewpoints ruins and trees do not have those and can be added.
I agree that "useful" POIs differ from "interesting" ones, but I think it's better to handle them with the same interface to keep UX simpler.
