### ISSUE TITLE
tags: "image" vs "wikimedia_commons"

### ISSUE THREAD

**Issue by SwiftFast** [IsraelHikingMap/Site#477]
I noticed IHM is now adding image tags. Most (or all?) of them lead to Wikimedia Commons. How about promoting the [wikimedia_commons](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons) tag instead, and only falling back to [image](https://wiki.openstreetmap.org/wiki/Key:image) when the image is hosted somewhere else?

The Wikimedia tag has several advantages:
- Human readable
- Allows linking to both categories and individual images
- Machine readable. Commons assets have categories and sub categories, etc. Can be used to show related media, even if it links to an individual image.
- No spam, and a reliable host.

**Comment by HarelM** [comment]
I don't follow...
`image` tag is what I need in order to present an image in the site.
I don't want to do all kind of wiki data parsing out of the wikimedia_common tag in order to get an image URL.
Having said that, I don't mind adding another wikimedia_common when the image is uploaded to wikimedia but at the time of updating osm element I don't have the context of wikimedia, which is a poor excuse but still...
In any case, it's a lot of effort with what I see as very little value.
If you want to help out and send a pull request you are more than welcome, otherwise I don't think it will be implemented soon.

**Comment by zstadler** [comment]
From an OSM tagging perspective, the `wikimedia_commons` tag is a draft with [3,682 uses](https://taginfo.openstreetmap.org/keys/wikimedia_commons) while the `image` tag is proposed with [79, 239 uses](https://taginfo.openstreetmap.org/keys/image)

**Comment by SwiftFast** [comment]
Thanks for the feedback. I've changed my mind regarding this.

>I don't want to do all kind of wiki data parsing out of the wikimedia_common tag in order to get an image URL.

Well, if it's a file, the only processing involved is prefixing the wikimedia url.
`wikimedia_commons=File:Bicycle_crossing,_Poland,_Krak%C3%B3w,_Josepha_Conrada.JPG` becomes `https://commons.wikimedia.org/wiki/File:Bicycle_crossing,_Poland,_Krak%C3%B3w,_Josepha_Conrada.JPG`

But if it's a category, some more work needs to be done. And even then you wouldn't know which image to pick as the default.

>From an OSM tagging perspective, the wikimedia_commons tag is a draft with 3,682 uses while the image tag is proposed with 79, 239 uses

... and a large chunk of the 3682 are from SwiftFast_bot. I'm considering removing the ones introduced by the bot, because it seems redundant in combination with Wikidata. (You can reach the same images through wikidata querying).
