### ISSUE TITLE
Support multiple images for POI

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#483]
Currently one can only upload/update a single image for a POI which is not sufficient in some cases.

**Comment by HarelM** [comment]
The following is the proposed UX - subtle with "<" and ">" buttons.
When "advance editing" a POI:
![image](https://user-images.githubusercontent.com/3269297/31274847-6f43e1b2-aa9d-11e7-9e2a-9115feb33e50.png)
When magnifying image thumbnail on POI popup - this screen will support swipe left and right, I hope I'll be able to animate the transition of the images, but I can't promise - also thinking of using the tab control for that purpose (which will provide thumbnails)
![image](https://user-images.githubusercontent.com/3269297/31274917-c2cbeb04-aa9d-11e7-8d7a-91942ffca7af.png)

**Comment by HarelM** [comment]
I decided to use the tabs control to support thumbnails and animation.
I also added swipe support for touch devices.
The following is an example on images I locally edited to see how it looks:
![image](https://user-images.githubusercontent.com/3269297/31301383-17630f3a-ab02-11e7-9a82-27bd15c04ae0.png)

**Comment by zstadler** [comment]
- When clicking on a POI there is no indication that there are multiple images available:

  <img width="277" alt="2017-10-14 00_12_53-israel hiking map" src="https://user-images.githubusercontent.com/1304610/31566825-01869c5e-b075-11e7-99c0-5ffd21290445.png">

  https://israelhiking.osm.org.il/#!/18/31.6568/34.9369

- The tabs create too much empty space when there are several images:

  ![image](https://user-images.githubusercontent.com/1304610/31566933-89400af4-b075-11e7-842c-010fc6523340.png)

**Comment by HarelM** [comment]
It is very hard to see what's in the thumbnail this is why I decided not allow the ability to switch images in thumbnails - if you are interested in seeing the images click on them.
Since this the large images is the angular material design of tabs and it is identical to other places I'm not planning on touching it - if you want it changed please assign it to yourself.

**Comment by zstadler** [comment]
### 1. Switching between thumbnails
It is not that hard to see the thumbnail in the first screenshot. For example, this is how a thumbnail of another image would look in the same dialog:

![image](https://user-images.githubusercontent.com/1304610/31576519-39c70fd2-b105-11e7-8576-606452b801d7.png)

The difference between the pictures in the two screenshots is clearly seen. You may not want to see a full-size image of the ruin, but you may want to see the full-size image of a mosaic.

### 2. Tab view cleanup
In order to create this tab structure:

![image](https://user-images.githubusercontent.com/1304610/31576638-8e174e2e-b107-11e7-943e-5e14fda84e6e.png)

The following style changes can be used:
- `mat-tab-labels`: `display: table; width: 100%;` instead of the current definition.
- `mat-tab-label`: change `display: table-cell; padding: 0 0;` and remove `min-width: 160px;`

Unfortunately, I would not know where to apply these changes in the code.

**Comment by HarelM** [comment]
I do not want to add more buttons to the POI popup - there are too many already.
I'll alter the css to condense the images.
