### ISSUE TITLE
Add tooltips with complete search result text

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#489]
When search finds multiple results in different locations, it is difficult to know what's the difference between them. for example:

![image](https://user-images.githubusercontent.com/1304610/30863315-62e31ec2-a2d9-11e7-909d-a2516621407f.png)

It would be nice if the full text of each search result will be visible, as a tooltip, when the mouse hovers it.

I know this is inapplicable to mobile devices, but IMHO this is does not justify making a better UX for the desktop.

**Comment by HarelM** [comment]
Sounds like a good idea, I hope the framework can support this.

**Comment by HarelM** [comment]
I had another idea to simply break the text into two lines when there's long text, but I failed with the css... :-/ Also the text can be better aligned after the icon.
Something like this, but a better styled:
![image](https://user-images.githubusercontent.com/3269297/30887149-c631534c-a322-11e7-9689-ddf16d24978f.png)

**Comment by moshfeu** [comment]
The solution to break the lines is also not that great because sometimes it breaks to 3 lines and that's looks not that good.

![image](https://user-images.githubusercontent.com/3723951/32014375-930f220e-b9c6-11e7-8826-0a82b1fbb58d.png)

Maybe, we should do it wider (for example 350px)

![image](https://user-images.githubusercontent.com/3723951/32018942-37308474-b9d4-11e7-8c7f-bb214fc0f71f.png)

**Comment by HarelM** [comment]
This still users 2 lines which I think is the right approach.
When I experimented with width I think 350 was too wide for mobile devices...

**Comment by moshfeu** [comment]
I think the combination of wider and break line will be good for desktop. For mobile, we can set the width for the maximum width we can. In the future, we can think about better approach.

**Comment by HarelM** [comment]
I agree.
