### ISSUE TITLE
Detele key and enter key when editing a route

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#49]
Delete - delete active route (as long as you can undo)
Enter - Start editing of active route

**Comment by HarelM** [comment]
I'm closing this since I don't feel key shortcuts are needed here, especially these two which are not so intuitive.
There are many I added and the only one **I** use is the ```esc``` button.
e.g.: ```Ctrl+F``` for search. ```Ctrl+S``` for save, ```Ctrl+O``` for open (in some browsers).
Most of the usage is with the mouse anyway so I don't think users are going to the keyboard a lot while using the site.
