### ISSUE TITLE
Allow POI sharing

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#513]
## Feature

The URL will looks something like: 

https://israelhiking.osm.org.il/#!/17/32.4577/35.4980?p=1234/תל רחוב

The benefits:

- Easy sharing a place.
- Will resolve the issue: https://github.com/IsraelHikingMap/Site/issues/488 (if I understand the issue correctly).
- The places could be indexed by Google and will displayed on the search result. (Need to check if sitemap.xml could help)

**Comment by HarelM** [comment]
The main problem here is not the usage of a URL but the creation of it.
Issue #488 is probably one of the least used features of the site due to the fact that it assumes the user creates the URL manually - which most users don't.
There are two options to address this:
1. Whenever a POI is opened change the URL, Which I don't like much (lots of bugs there as this is a problematic area in the code) - same goes for search - this is the preferred options in terms of UX. having said that, the simple share option covers that partially and thus I'm not thrilled in adding another type of share (besides copying the URL of the address bar).
2. Cover this as part of #361 for advanced users/embedded mode.

In any case, google currently doesn't search the "hash" part as far as I know and the site is SPA so google doesn't handle well with this. I don't think this is a criteria right now, maybe in the future.

**Comment by moshfeu** [comment]
1. Change the url when user clicks on a POI is not needed, I think. Just add a share button in the tooltip. When user will click on it the url will copy to the clipboard or common share options will displayed. The problem with current share is that for a specific POI will have multiple urls.
2. I think that Google index hash urls just like he did in עמוד ענן:

https://www.google.co.il/search?q=site%3Aamudanan.co.il

Or offroad (which is spa but without hash)

https://www.google.co.il/search?q=site%3Aoff-road.io

Another point, maybe it will be better to not use hash but html5 routing in angular.

**Comment by HarelM** [comment]
Are you familiar with a way to automatically redirect urls from hash to html5 mode?
I'm hoping to migrate out of this old style but I don't want old links to stop working...
In any case, a share button on a POI might be a useful.

**Comment by moshfeu** [comment]
I know that in AngularJS it worked automatically. In Angular2 now. We are using Angular4 so I'm not sure. (I didn't touch the project for a while and now I can't make it works) There is approach like this: 
https://stackoverflow.com/a/41662473/863110
Let me know if I can help with anything..

**Comment by HarelM** [comment]
Well, there isn't any usage of routing in this project this is probably why it doesn't work.
The only class that handles routing is `HashService.ts` and it does so by appending things to the addressbar.
The problem I had with the hash was with the server as I didn't know how to configure it to ignore routing of the client side, I can probably make it work now since I now better understand how things work.
In any case feel free to implement this feature or any other feature you'd like. Any help will be appreciated :-) especially stuff that require CSS, for example #489

**Comment by HarelM** [comment]
Beta site has this implemented (although the link points to the original site and not the beta, but adding the `beta` to the address solves this).
for example:
https://israelhiking.osm.org.il/beta/#!/?p=OSM__node_2209019954
Need to think if we want to keep the POI in the address bar or not and if to change the address bar when opening a POI - I'm tending towards not doing it for now since the user has a button and doesn't need to concern himself with the address bar.
Need to think if and how to support this with iFrame.
Regardless, 
 - [ ] Need to support open graph for Facebook on the server side.

I've implemented WhatsApp support for web WhatsApp for desktop usage while working on this feature.

**Comment by moshfeu** [comment]
Great! Thanks!

**Comment by HarelM** [comment]
To summarize the phone conversation with @zstadler: using the above link can be problematic since osm entities can be deleted or other poi from 3rd party vendors can be merge and so the above concept of using the poi id might really in invalid URLs.
On the other hand, the concept of POI sharing might be for short term sharing so this might not be an issue, and using a different id might break the kiss principle.
We haven't established an alternative solution though.

**Comment by HarelM** [comment]
Sharing of POI will be possible after #653 will be published.
Another thing to do here is to change wikipedia and iNature identifier to use the title and not the id to conform with OSM usage.
Crawling should be available and should show the title, description and first image if exists according to relevant language.

**Comment by HarelM** [comment]
iNature and wikipedia titles in hebrew create awful url when copying, also the database doesn't like id with Hebrew characters.
Since this was the last thing left to do this issue can be closed...
