### ISSUE TITLE
Routes between two points aren't always the shortest way

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#533]
## What I expect to happen
When editing a route, the path created between two waypoints should be the shortest one available for the current mode (pedestrian, cycling, 4x4)

## What really happened
The site sometimes chooses a tortuous path between two waypoints. 
example https://israelhiking.osm.org.il/#!/?s=y5IHYWobaZ

**Comment by HarelM** [comment]
Unfortunately this is a wrong assumption.
The bike profile we are using was designed by graphhopper and takes into consideration elevation as well.
In the linked case it's easy to see that only the bike profile is taking the long way around in order to avoid the going directly uphill.
Other profiles and the opposite direction does not suffer from this issue.

I don't see a bug here, feel free to open it if you do not agree.
