### ISSUE TITLE
Loading the user-related info takes 5 minutes (literally)

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#549]
Bug
What I expect to happen:
The whole site should load in seconds

What really happened:
The interface and map loads in seconds, the user info and custom layers take many minutes to load.
What I did that caused the issue - step by step
Logged out of the OSM user. logged in again.
My environment:
Windows 10
Chrome
relatively slow connection

**Comment by HarelM** [comment]
The fact that the interface and and map loads in seconds is probably due to the fact that the browser caches the client side code so it doesn't fetch it from the server on every load, this is not possible for other data.
I have just ran it on my account and it took around 3 seconds.
You can see here:
![image](https://user-images.githubusercontent.com/3269297/32518608-c9f3051e-c412-11e7-8ba6-0bd1a7b4a197.png)
Please follow these steps:
1. Press F12 to open debug tools in tour browser.
2. Go to network tab
3. Log out of osm.
4. Press the trash can or circle with slash to clear network history.
5. log in to OSM and look for calls to `api/something` and send a print screen here so I can understand what causes the delay in your case.

**Comment by oriori** [comment]
I have a similar problem over the past few days/week. Windows 10, Chrome. Following your instructions, it seems the api/urls is culprit. 
![image](https://user-images.githubusercontent.com/8708384/32542583-c1332a62-c47b-11e7-81f3-b0aec399ef1f.png)

**Comment by HarelM** [comment]
How many shared routes do you have?
Can you expand the size column? I can't see what's the size in the screen shot, starts with 8... If it's 8 Mb it might explain the delay.
Maybe server paging is needed to reduce the load time...

**Comment by valleyofdawn** [comment]
It's similar in my case. My shared tracks are around 50, didn't change much lately.
![image](https://user-images.githubusercontent.com/689201/32546210-309a452c-c4e3-11e7-8d13-b64c22dad256.png)

**Comment by oriori** [comment]
Yes, it's 8 MB. I have 33 shared tracks right now.

**Comment by HarelM** [comment]
I'll reduce the content of the response and remove the actual route, the route will be fetched only when needed (lazy loading).
