### ISSUE TITLE
Save as with max number of points

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#550]
Feature

## What I expect to happen
A checkbox/another text field in the save as window (currently list box). Pressing it will use the algorithm from GPS babel to simplify a route to a user specified number of points before saving it.
Alternatively this can be implemented regardless of saving the route. A simplify button on the route properties window will simplify (after asking the user for the number of points) the displayed route rather than the downloaded one.

**Comment by HarelM** [comment]
Please elaborate why would one need such feature?
As a general rule, I don't like asking users questions they will have a hard time answering.
A simplification slider is probably a better approach.
See also issues #351, #331.

**Comment by oriori** [comment]
Most navigation devices have a limit on the number of points a route can have. Mine is limited to 1000 points. Older devices are limited to 500 points, newer to 2000-10000. Some devices handle it automatically but the simplified result is inferior to the D-P algorithm. Other devices just take the first n points or don't handle it at all.
Personally, I use a GPS Babel to simplify each route I use to less than 1000 points before I upload it to my Suunto watch. 
I imagine this as an advanced option not immediately available on the main screen (so a button in the route properties window will probably be better).

**Comment by HarelM** [comment]
My initial instinct is to discard this issue as vendors of such devices should provide the necessary software/application to overcome those issues.
If your vendor is not doing its job, open a bug/feature request there. This is what I do when things don't work for me.
Since you can do it in other sites and as far as I can understand this is not a common user scenario I tend to say that a wiki page with relevant instructions should do in this case instead of adding this feature to the code. Advanced route options already have some feature that probably are not needed and I don't want to complicate it further...
If you have an idea that will solve this issue as well as the two issues linked above with a simple UI I'd love to discuss it.

**Comment by HarelM** [comment]
I don't see a good reason to implement this - there are other editing tools for GPX file which you can use if your device has limitation, I don't think this should be a concern for all users.
