### ISSUE TITLE
A POI is not shown on the screen

### ISSUE THREAD

**Issue by afishler** [IsraelHikingMap/Site#583]
## What I expect to happen
To see a POI with description and images like I added in the editing phase 

## What really happened
No clickable POI appears

## What I did that caused the issue - step by step
I added a POI by going into "edit point" mode, marking it on the map, Adding a name and description.
I used the "upload" button. Got a popup to add details again (which I did) and added my photo as well. I cannot see the POI (unless it takes many hours to get it to appear)
![2017-12-28_1545_001](https://user-images.githubusercontent.com/29601283/34413266-e154d566-ebea-11e7-8421-b66be08e470b.png)

Example is in the lower part of נחל עמוד עליון
## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Thanks for your report!
the POI is there now...
I think there's a problem with updating the POI layer after you add a POI. The POI creation seems to be OK - I usually turn the layer off and then on to get the updated POIs, I'll check it never-the-less. 
![image](https://user-images.githubusercontent.com/3269297/34450213-52e0b638-ed0c-11e7-9f4a-8f0da642d361.png)
I think it's worth mentioning that currently there's are two nodes at the same location:
![image](https://user-images.githubusercontent.com/3269297/34450244-d7ecb0ca-ed0c-11e7-9c6f-d62a99e3009f.png)
Which is considered a bad mapping:
https://www.openstreetmap.org/edit?node=5308146821#map=20/32.91375/35.48377

As a side note, currently tabs are not considered an interesting POI as in most cases it's either that you have water there or you don't which in this case the map itself should be sufficient.

Having said that, it's always better to have some description and images so I think you should make yourself familiar with the OSM editing interface since this is considered an advanced editing mode, IMHO.

As an exercise, I would try and move all the tags from the tourist attraction to the drinking water node and delete the tourist attraction. If after doing so (it should be updated within 5 minutes in IHM) this POI stops appearing write here and I'll see why not.

**Comment by afishler** [comment]
Thanks for the exercise. Think I did it ok.
The problem initially was that I did not see the POI since the POI layer was off. I had to turn it on.
This is why it probably appeared twice since I added it again after not seeing. Believe it is ok now.

**Comment by HarelM** [comment]
Thanks for taking the time!
Please note that you have removed the point but did not copied all the tags, for example the image tag.
You can see the previous points tags:
https://www.openstreetmap.org/node/5308146821/history
There are also videos in the Facebook group that shows how to edit with OSM.
You can copy the image tag to see the image in IHM site.
If you need extra info let me know.

**Comment by HarelM** [comment]
@afishler any change you can add the missing tags?

**Comment by afishler** [comment]
mmmmm....did not get to it :) hopefully will do

**Comment by HarelM** [comment]
I have added the missing tags...

**Comment by afishler** [comment]
I don't see this point as a POI on the map at all? Should I now? I just see the tap icon but what about the other tags you mentioned? The image for example....is there a way to see it?

**Comment by HarelM** [comment]
I'll check why it doesn't appear, maybe because it's a tap... I'll check...

**Comment by HarelM** [comment]
Seems like an issue with how public POIs are filtered - currently public POIs that are not part of any category are not presented, which is wrong as POI with images should be presented...
This is a serious bug.
Will be fixed in the next few days.

**Comment by HarelM** [comment]
Currently, we have decided not to show these kind of POIs.
I'll add the ability to snap to these kinds of points and get all their data but they won't be a part of the public POI layer currently.
