### ISSUE TITLE
Big difference between measured and planned route length

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#589]
## What I expect to happen
Measured GPS and calculated route should yield results that are close enough

## What really happened
I've seen some routes I made which has a significant difference between measured and planned routes

## What I did that caused the issue - step by step
This is a place holder, I'll add data later

## My environment
Measuring using Orux on Galaxy 6.

## Thing I think the developers should know, images, links etc.
This needs an investigation, it might not be a bug.

**Comment by zstadler** [comment]
A directions to consider:

- Taking elevation changes into consideration
- Recorded GPS track can contain gitter/noise/small random location jumps that could sum-up to a significant difference. 
- Potential calculation errors may be spotted by running "our" distance computing on track recorded by Oruxmaps in order to compare the results or by recding a GPS track along a known straight distance by foot and by car.

**Comment by HarelM** [comment]
@zstadler any chance you can try and find such case and attach it here?

**Comment by valleyofdawn** [comment]
In my experience the measured length varies significantly with the frequency of sampling, with shorter lags or distances yielding longer measured tracks.

**Comment by HarelM** [comment]
I have gone over some of the track I recorded with Orux and I see a difference but not a huge one. For example difference between ~8 to ~9 KM and 6 to 6.8 (~10%...)
I leaning towards closing this issue as I couldn't find a good use case to present my case.

**Comment by valleyofdawn** [comment]
I'm for closing too.
