### ISSUE TITLE
Remove marker of imported search result POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#600]
## Minor Bug

When importing a POI from the search results, and the POI layer is not visible, the search result marker is always visible behind the imported POI:
![image](https://user-images.githubusercontent.com/1304610/34944756-7bb6c642-fa09-11e7-8bc3-7ad18d342da8.png)

Needless to say that the search result marker is inaccessible. I suggest that the search result marker will be removed after the import.

**Comment by HarelM** [comment]
I've implemented a solution that only solves the following scenario:
1. search
2. select search results
3. in the popup of the search results click "+" to add to route.
Which is what I think is the common use case.
The following scenario is not not covered by this fix:
1. search
2. select search results
3. close popup
4. go to edit private POI mode
5. snap to search results
6. click to add private POI
7. issue: search POI will be kept and not removed.
Since snapping can happen both for visible search results and non visible public POIs I think this is a good enough solution.
In case you do not agree please call me so we can discuss the details.
