### ISSUE TITLE
Copy/Move POIs between routes

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#609]
This is especially needed after splitting a route. All POI are kept in the original route and I could not find a way to move or copy some of them to the new split route.

**Comment by HarelM** [comment]
Unfortunately, I don't have a good idea how to solve this.
Suggestions for relevant UX are welcome.

**Comment by zstadler** [comment]
Regarding a route split, we have no way of knowing what the user intends to do after the split. We don't even know that a given POI is relevant only to one part. In particular, a POI at the split point is very likely to be relevant to both parts. I therefore suggest both parts will contain all the POIs of the original route layer. The user can then decide to delete or retain any POI in each part.

I'll think about a UX for the general copy/move issue.

**Comment by HarelM** [comment]
@zstadler I think this issue can be closed since I think the addition to delete only POIs allows achieving this behavior - although it's very complex to achieve it, it is possible using files and selectively delete stuff. Also the fact that if you open a file with only POIs it adds them to the current route (or it needs to have only one route, I don't fully remember).
I don't think this is a day-to-day scenario so I think the current workaround is good enough.
Can this issue be closed?

**Comment by zstadler** [comment]
I may be missing something since I do not see the relevance of the "delete all POIs" to the issue. 
Let's have a f2f discussion.

**Comment by HarelM** [comment]
After a phone conversation the proposed solution is to allow a selective copy of POIs from an inactive route to the active one using the private POI dialog by adding another button.
