### ISSUE TITLE
Support joining wikipedia and OSM locations

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#616]
## Feature
Support joining wikipedia and OSM elements using the following tag by adding it to the relevant OSM elements:
https://wiki.openstreetmap.org/wiki/Key:wikipedia
When this tag is used the description and image (and title?) should be taken from wikipedia and the type and location should be taken from OSM.

## Things to consider
1. Can a user edit the point or will it be read-only like the current wikipedia marker? meaning only advance OSM users will be able to edit it.
2. How to support multiple languages? current tag is linking to one wikipedia article
3. Can we run an initial script on wikipedia data and OSM to see if we can find places that are close by and see how many places can be joint automatically or semi-automatically?
4. Should the wikipedia image appear when opening the marker like today?

@safwathalaby, @zstadler, @valleyofdawn I would appreciate your input here.

**Comment by zstadler** [comment]
My input:

> 1. Can a user edit the point or will it be read-only like the current wikipedia marker? meaning only advance OSM users will be able to edit it.
OSM users should be able edit such a POI just like any public POI. The interface should not allow changing the Wikipedia tag, just like it is not allowed today.

Moreover, The Wikipedia image and descriptions should be used only if there is no OSM image or description.

> 2. How to support multiple languages? current tag is linking to one wikipedia article
OSM supports links to multiple Wikipedia languages. See https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_languages

> 3. Can we run an initial script on wikipedia data and OSM to see if we can find places that are close by and see how many places can be joint automatically or semi-automatically?
Perhaps @safwathalaby can help with his experience in the [Automated incremental Bus Stop (GTFS) updates](https://forum.openstreetmap.org/viewtopic.php?id=60149)

> 4. Should the wikipedia image appear when opening the marker like today?
When clicking an OSM POI which has an OSM image tag, that image should be shown. Otherwise, the OSM POI has a Wikipedia tag, and the Wikipedia article has an image, the Wikipedia image should be shown. Otherwise, the "Add image" icon will be shown".

Uploading images to OSM should be allowed regardless if a Wikipedia image is used.

**Comment by HarelM** [comment]
>Moreover, The Wikipedia image and descriptions should be used only if there is no OSM image or description.

Not sure about it, although I understand your point of view, I thought that the Wikipedia content is usually richer and might be better so I though it should take precedence.
>OSM supports links to multiple Wikipedia languages. See https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_languages

According to what's there I still don't fully understand how to support multiple languages,
for example let assume the following case:
I have an OSM element with the tag: `wiki=en:Some_Title` I need to be able to pull the extract (description summary) of this point in Hebrew, how do I do it? 
Currently I can get the extract using the page title - which in not relevant to the Hebrew case as far as I understand how the API works, I'm no expert though.

>4. Should the Wikipedia image appear when opening the marker like today?

I meant the Wikipedia icon on the top left corner, sorry for not being clear enough.

**Comment by zstadler** [comment]
>>Moreover, The Wikipedia image and descriptions should be used only if there is no OSM image or description.

> Not sure about it, although I understand your point of view, I thought that the Wikipedia content is usually richer and might be better so I though it should take precedence.

IMO, the primary goal for site's use of OSM POIs is to provide short descriptions and images. This is not a replacement for Wikipedia. In any case, the POI pop-up never shows the full Wikipedia article and the site does not promote editing Wikipedia articles.
## 
>>OSM supports links to multiple Wikipedia languages. See https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_languages

>According to what's there I still don't fully understand how to support multiple languages,
for example let assume the following case:
I have an OSM element with the tag: `wiki=en:Some_Title` I need to be able to pull the extract (description summary) of this point in Hebrew, how do I do it? 
Currently I can get the extract using the page title - which in not relevant to the Hebrew case as far as I understand how the API works, I'm no expert though.

I think the `wiki*` OSM tags should be handled just like the `name*` OSM tags. For example, in Hebrew mode, if a `wiki:he` exists, it will be used, otherwise, the `wiki` tag will be used regardless of the language of the tag's contents. Just like the site and map show the `name` tag in any language if `name:he` is unavailable.
##
>>4. Should the Wikipedia image appear when opening the marker like today?

>I meant the Wikipedia icon on the top left corner, sorry for not being clear enough.

I assume you refer to this icon in cases where there is a `wikipedia*` tag in addition to one of the `name*`, `description`, or `image` tags:

![image](https://user-images.githubusercontent.com/1304610/35211822-b6885efa-ff60-11e7-97c8-fdc6a87a150b.png)

We can consider adding a button, with the Wikipedia icon. that will open the Wikipedia article in a separate browser tab. Having a Wikipedia icon like the above will be confusing to believe the information was taken from Wikipedia.

**Comment by HarelM** [comment]
> I think the wiki* OSM tags should be handled just like the name* OSM tags. For example, in Hebrew mode, if a wiki:he exists, it will be used, otherwise, the wiki tag will be used regardless of the language of the tag's contents. Just like the site and map show the name tag in any language if name:he is unavailable.

As far is I understand from the OSM definition this is not advised, I agree this was my initial thought on how to solve this. You can see the following issue for reference: #484

I think I agree with the other points.

**Comment by zstadler** [comment]
Indeed, the OSM wiki states that the use of `wikipedia:*` tags is ___usually___ sufficient. Yet, the talk page includes many comments supporting the use of `wikipedia:*` tags. The suggested approach in the OSM wiki requires the reader to open the article in a given language, scroll the sidebar to the "languages" (or "অন্যান্য ভাষাসমূহ"...) section, and click the link to the desired language. 

Until we find an algorithmic way to perform the equivalent of the above, hopefully not by scraping Wikipedia articles, I believe there is no alternative to making use of `wikipedia:he` and `wikipedia:en` tags, if they exist.

**Comment by HarelM** [comment]
According to the valid links in overpass turbo it seems that they support both:
![image](https://user-images.githubusercontent.com/3269297/35487718-86465a9a-0487-11e8-9ef4-c234069810ca.png)
I'll focus my effort on make the `wikipedia:language=...` work.

**Comment by zstadler** [comment]
> According to the valid links in overpass ...

Overpass just shows the existing tags. It has no notion of validity. The above is the same tag list as in
https://www.openstreetmap.org/node/278473497

**Comment by HarelM** [comment]
The blue links above are pointing to the right wikipedia page - which means overpass decided to support both notations, and so we are not the only ones who thinks this is the right approach.
This is just a method to build a stronger case...

**Comment by HarelM** [comment]
I wanted to know which tag is used more and saw that `wikipedia=...` is much more popular.
So I decided to support reading from it in order to join POIs.
Having said that, writing to OSM tags should be with the relevant user interface language.
This turns out to be really cool since wikipedia articles now have a representation on the map - regional councils, settlements etc :-)
This means that this feature can't be released without implementing #591.
![image](https://user-images.githubusercontent.com/3269297/35488651-643497f2-0494-11e8-80bd-58eb3ba08df4.png)
Here's an example of the results of the joining:
![image](https://user-images.githubusercontent.com/3269297/35488695-2c590128-0495-11e8-9020-171b6da40942.png)
