### ISSUE TITLE
Routing to give preference to trail relations

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#621]
## What I expect to happen
Routing to give preference to trail relations - marked trails or MTB trails, according to the selected routing mode.

## What really happened
Routing takes shortcut opportunities off marked trails, even when the savings is insignificant.

## What I did that caused the issue - step by step
[See this routing example:](https://israelhiking.osm.org.il/#!/?s=6L0f0Hs8FE)

![image](https://user-images.githubusercontent.com/1304610/35192568-c613af6e-fe9d-11e7-8af0-11aee82008af.png)

## Thing I think the developers should know, images, links etc.
- This requires creating 3 new GraphHopper profiles, inherited from the existing hiking, biking, and off-roading profiles.
- This effort can be combined with the  "A specific MTB trail isn't recognized as such" issue https://github.com/IsraelHikingMap/Site/issues/584

**Comment by HarelM** [comment]
I think it's worth combining all the related issue that involves routing to a single issue and manage all the requirements there (can be this issue) as I think an update to GH version should include all relevant fixes we now think should be there.
Also I have suggested the following to GH team and I think they approved the idea but didn't have time to implement it:
A FlagEncouder that is defined by a config file instead of by code - this way you can change the profiles without changing the code and you can create multiple profiles, each in a single config file.
It can make the development process longer now but I think we'll benefit greatly from it.
In any case, it's your issue and thus your call.

**Comment by HarelM** [comment]
Found it:
https://github.com/graphhopper/graphhopper/issues/193

**Comment by zstadler** [comment]
In addition, the new 4wd profile should prefer off-roading.

For example, given this search
![image](https://user-images.githubusercontent.com/1304610/35339956-9980ee32-012a-11e8-88eb-3b6fb7c9de84.png)

the resulting 4wd route is
https://israelhiking.osm.org.il/#!/?s=LV6R18j7Dt
![lv6r18j7dt](https://user-images.githubusercontent.com/1304610/35341671-e4c7b138-012e-11e8-9237-812fc3e6adb2.png)

while the desired off-road route should be
https://israelhiking.osm.org.il/#!/?s=eKRCUhswDE
![ekrcuhswde](https://user-images.githubusercontent.com/1304610/35341858-56958e20-012f-11e8-9c4b-7c719e41ac85.png)

**Comment by HarelM** [comment]
I was browsing through OsmSharp issues as a new version was released recently and stumbled upon this library https://github.com/itinero/routing.
Digging through the examples and documentation it seems that this library can accept a Lua script as routing profiles - which I think can be greatly beneficial to us. it is also written in .Net core and uses OsmSharp (like the site does) which makes things a lot easier, I think.
It can still be used though API and the developer from OsmSharp is more open to suggestions unlike what we currently have with GraphHopper.
It might prove beneficial to switch to it.

**Comment by zstadler** [comment]
@HarelM Can you add a link to the documentation and examples of the Lua scripts?

**Comment by HarelM** [comment]
I have opened an issue to ask that :-)
https://github.com/itinero/routing/issues/152

**Comment by zstadler** [comment]
@HarelM Please create a separate issue for the proposal to replace the routing software.

**Comment by HarelM** [comment]
Closing in favor of #640
