### ISSUE TITLE
UX improvements to Base-maps and overlays

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#631]
## Feature

I recently followed a novice user.
He couldn't figure out why he couldn't see a change when clicking on the hiking overlay when the hiking basemap was on.
I suggest putting"מפות בסיס" and "שכבות שקופות" as titles to those sections. When moving to advanced mode, add just a "+" sign to those.

**Comment by valleyofdawn** [comment]
Isn't it too wide on a big screen?
Also. can the small stats window be incorporated inside, so the bottom strip beyond the height profile is not wasted? Opening the height window would feel like expanding the small stats window.
![image](https://user-images.githubusercontent.com/689201/35502478-d991242e-04e5-11e8-9d34-f658045f3de2.png)

**Comment by HarelM** [comment]
>Isn't it too wide on a big screen?

Wrong issue?

For this issue I'll see if I can present a toast with a warning to the user or disable this option, this is a common mistake that new users make.

**Comment by valleyofdawn** [comment]
Yep, wrong issue.
I think it would be better to make it self evident rather than use a toast.

**Comment by HarelM** [comment]
Not sure what you mean by "self evident" - disabling a button does not tell the user how to solve the issue of a disabled button.
I don't have another idea besides a warning/error toast and button disabling.
Feel free to suggest other mechanism.

**Comment by valleyofdawn** [comment]
I was referring to the toast.  I think a headategoty title line would solve it easily, as I originally suggested.

**Comment by HarelM** [comment]
headategoty?
I don't think a relevant title would solve this - users often don't read and just skip to the relevant button.
A toast indication is much more noticeable when you do something that is unadvised.

**Comment by valleyofdawn** [comment]
Header. We have it anyway in the advanced mode.

**Comment by HarelM** [comment]
I don't like how it looks, sorry.
If you want to suggest a better looking composition, be my guest...
![image](https://user-images.githubusercontent.com/3269297/36935853-a3703be8-1f05-11e8-9e5e-b4d41abdc38f.png)
I'll add the warning toast regardless...

**Comment by valleyofdawn** [comment]
How about this:

![image](https://user-images.githubusercontent.com/689201/36974419-4d8686ee-207f-11e8-8898-196f852d335d.png)

**Comment by HarelM** [comment]
The question here is what is the default collapse behavior for each section.
Since less than 0.1% of the users has more than 3 layers I don't think there is a need to be able to collapse the layers - this will create a complex UI for no reason.
The default for POI are collapsed and so this will create an uneven UI in the case above.
I'd be happy if you send some more ideas...

**Comment by HarelM** [comment]
To summarize all the requirements for base-layers and overlays, according to #656 and phone conversation with @zstadler on the phone:
1. Add Headers.
2. Allow Collapse.
3. Allow sorting.

I'll keep this issue open although it has an extremely low priority since most users do not need this.

**Comment by valleyofdawn** [comment]
There are also only 3 types of public routes and you added a collapse button.  I think adding them for consistency makes sense. Also I think the overlays make more sense next to the maps.
Even beginner users when opening a complex route like [this ](https://israelhiking.osm.org.il/#!/?s=uB1v6NnfCT)on their mobile would appreciate mores space.

**Comment by HarelM** [comment]
>There are also only 3 types of public routes and you added a collapse button.

True, this is because I want most user not to know this is expandable and just show/hide the entire layer - the collapsed is the default while "advance" users can expand and see more options.

> I think adding them for consistency makes sense

I don't understand how this will make it consistent - you can't hide all baselayer and collapsing them is counter productive in most cases.

>Also I think the overlays make more sense next to the maps.

No objection here.

> Even beginner users when opening a complex route like this on their mobile would appreciate mores space.

I don't expect beginner users to fully interact with the layers sidebar, especially not on mobile devices - maybe open it and change the base layer at best.

Please try and remember one of the core rules when talking about UX: "You are not your user".
![image](https://user-images.githubusercontent.com/3269297/36988120-a81f1ee6-20a6-11e8-9969-d73c80e9ca47.png)

**Comment by zstadler** [comment]
I must have missed the quick discussion on the "Base layer and overlay are overlapping" toast.

IMO, it would be better to simply avoid showing the Hiking or MTB overlays if the corresponding base-map is used. The state of the overlay will remain "visible" so once a different base layer is used, the overlay will be shown.

**Comment by HarelM** [comment]
>IMO, it would be better to simply avoid showing the Hiking or MTB overlays...

This is very complex and I don't think it's worth the effort.

**Comment by zstadler** [comment]
I understand the conflict identification is already there. So the handling of the conflict is complex?
Would it be simpler if the overlay will not remain "visible"?
Would you accept a PR for this?

**Comment by HarelM** [comment]
Here's how this is going to look with the new UI (using angular material accordion):
This means that every group is collapsible, the default is that routes and POI only are collapsed by default.
Collapse state is saved between sessions.
I'm not going to implement any different solution to the toast since I believe this is the best UX solution.
Not planning to solve sorting of overlays and base layers since it requires a round trip to the server and I don't think it has significant value to most users so I don't think it's worth the effort.
![image](https://user-images.githubusercontent.com/3269297/43044384-6dc19e58-8dad-11e8-9aea-cb5001e27fec.png)
I've also changed the color of the primary theme to be green.
Will be publishing to beta site shortly.

**Comment by valleyofdawn** [comment]
Excellent!
If you could change the tabulation so that the headers are not shifted to the left of the item lists it would look even better.

**Comment by valleyofdawn** [comment]
Also מפות בסיס not שכבות בסיס

**Comment by HarelM** [comment]
I've unified all icons sizes to be the same for every group:
![image](https://user-images.githubusercontent.com/3269297/43045989-32d7cd94-8dcb-11e8-8bf2-ffde3f24a56f.png)

**Comment by valleyofdawn** [comment]
> I must have missed the quick discussion on the "Base layer and overlay are overlapping" toast.
> 
> IMO, it would be better to simply avoid showing the Hiking or MTB overlays if the corresponding base-map is used. The state of the overlay will remain "visible" so once a different base layer is used, the overlay will be shown.

It seems like the toast in not doing its job and many users keep turning on the "overlapping overlay" without noticing and than getting ugly map results. I can provide several examples if you are interested.
I suggest 3 measures instead
1 ) Actively preventing showing an overlay if its the same as the basemap
2) Graying-out the overlay, so users won't try to turn it on
3) Assigning related names to the basemap and overlay: e.g. 'Israel Hiking Map' vs. 'transparent Israel Hiking Map', so users understand why it's grayed out.

**Comment by HarelM** [comment]
This discussion is very long and the title of this issue does not match your last comment.
Please open a different issue and reference this one instead of reopening this one.
