### ISSUE TITLE
No Image svg Wikipedia POI in chrome

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#636]
יער צרעה
Dead link for the image.
The rest seems good.
https://israelhiking.osm.org.il/#!/17/31.7781/34.9780

**Comment by zstadler** [comment]
Please reload the site. It look OK here:

<image width="67%" src="https://user-images.githubusercontent.com/1304610/35860430-ac82171e-0b4c-11e8-9869-974d646cfcb2.png"/>

As for the presented image, see issue #625

**Comment by valleyofdawn** [comment]
Not for me (after reload) are you using Chrome?
Same problem on mobile and PC chrome.

**Comment by valleyofdawn** [comment]
Nor the built-in mobile browser.

**Comment by zstadler** [comment]
Apparently, Chrome browsers are unable to show the svg file.

**Comment by valleyofdawn** [comment]
Maybe we should reconsider issue #625

**Comment by HarelM** [comment]
Let talk about issue #625 in the relevant thread and not here...
svg images from Wikipedia can be presented using a png suffix which can be fixed in the client side logic.
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/HaShfela.svg/300px-HaShfela.svg.png
In this function:
https://github.com/IsraelHikingMap/Site/blob/6535c6995c1a8d1b525d8fd6aa5a283b6d727f6d/IsraelHiking.Web/sources/application/services/resources.service.ts#L886

**Comment by valleyofdawn** [comment]
The same browsers do show it in the Wikipedia article itself.

**Comment by HarelM** [comment]
Wikipidia is not using the svg as image source, as explained above.
