### ISSUE TITLE
Route import is always done in hiking mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#654]
## What I expect to happen
When importing a route file, the route mode should be set according to the current route mode, unless the route already has route modes for its segments.

## What really happened
The import is always done in hiking mode.

## What I did that caused the issue - step by step
1. Select 4WD routing mode
2. [Open the dolev-zanoach.twl](https://israelhiking.osm.org.il/#!/?url=http://www.jeepolog.com/UserFiles/TWL/dolev-zanoach.twl) 4WD route  from jeepolog.com
3. Delete the route point near "חורבת חנות"
    ![image](https://user-images.githubusercontent.com/1304610/36943959-43e98490-1f9b-11e8-86fb-3c0d37746ac1.png)
4. The resulting route uses "Hiking" mode
    ![image](https://user-images.githubusercontent.com/1304610/36945133-f3fb673e-1fb1-11e8-93ef-34d98e4f3998.png)

## My environment
* Operating System and version: any
* Web Browser and version: any

**Comment by HarelM** [comment]
Unfortunately, the default is set when loading the route at the server side while the current routing mode is stored only in the client side.
I think that moving the routing mode to the server is an overkill for this feature and I tend to think that fixing the response in the client side is very error prone.
Since the user is already editing the route, I tend to think that moving the next route-point is a decent workaround...

**Comment by zstadler** [comment]
The current behavior is unexpected and annoying, if you are not a hiker.
On the other hand, passing the client's routing mode to the server, as part of the existing API call, is a local change that does not have negative side-effects.

**Comment by HarelM** [comment]
I have ran very few tests on this fix, it will require more testing once published.
