### ISSUE TITLE
Add collapse button (^) to base map and overlay list

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#656]
Feature
 
My map list is long, when using the mobile site it requires scrolling and clashes with the IHM logo.
Would work better if it had a collapse arrow like the ones next to the public routes and POIs.
It wouldn't take up space, nor add complexity.
It would make the interface more uniform.

**Comment by HarelM** [comment]
Only you and about 50 users out of 20K has this problem - I don't think this should be a concern for everyone...
> It wouldn't take up space, nor add complexity.

It would - more button is more complexity by definition.
> It would make the interface more uniform.

Actually it won't - currently collapsible layers has the options to hide the entire layer, this is not the case for base layers, it is the case for overlays but I don't think there is a requirement to see or hide all overlays since in most cases you use 1-2 overlays and not all of them.

But we are talking in two threads about the same concern.
Closing this in favor of #631.
