### ISSUE TITLE
IHM POI update interface removed a tag from a way

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#678]
## What I expect to happen
IHM POI update interface should not be able to modify ways, and remove the stream tag in particular.

## What really happened
In [changeset 57886978](https://www.openstreetmap.org/changeset/57886978), IHM POI interface removed the `stream` tag from [Peres stream](https://www.openstreetmap.org/way/181440262)

> ![image](https://user-images.githubusercontent.com/1304610/38727071-a6e60972-3f14-11e8-997c-e52915204743.png)

## What I did that caused the issue - step by step
Unknown

## My environment
* Operating System and version: Unknown
* Web Browser and version: Unknown

## Thing I think the developers should know, images, links etc.
See [OSM History Viewer: Changeset 57886978](http://osmhv.openstreetmap.de/changeset.jsp?id=57886978)
> ![image](https://user-images.githubusercontent.com/1304610/38726647-6b7705d6-3f13-11e8-8010-819f3904871c.png)

The tagging was manually restored in [changeset 58058343](https://www.openstreetmap.org/changeset/58058343)

**Comment by HarelM** [comment]
Good catch. this is a severe bug.
The reason for it is that search-icon is sent to the server instead of empty icon so the updater think he needs to remove the stream tag since he thinks the icon was changed.
I assume the following as to what caused this:
1. User searched for נחל פרס and chose the results for the search
2. Clicked the edit button in order to place the wikipedia link
3. There's no way to add a URL to ways so he added it in the description.
4. clicked save.

I'll see if I can fix both issues here - incorrect remove tag and add the ability to add link to ways.

**Comment by HarelM** [comment]
Also when looking into this bug I have found the following issue that will be resolved too:
![image](https://user-images.githubusercontent.com/3269297/38736611-4795fa38-3f35-11e8-8e96-ba5a6510c592.png)
