### ISSUE TITLE
TWL files are downloaded empty

### ISSUE THREAD

**Issue by hagai-lvi** [IsraelHikingMap/Site#689]
## What I expect to happen
When I download a TWL, I expect it to work

## What really happened
I get a file with 0 bytes, that I can't open

## What I did that caused the issue - step by step
1. Create a route
2. Click save as
3. select twl

## My environment
* Operating System and version: macOS 10.13.1
* Web Browser and version: Google chrome Version 65.0.3325.181 (Official Build) (64-bit)

## Thing I think the developers should know, images, links etc.

Link to the route I couldn't download:
https://israelhiking.osm.org.il/#!/?s=oxIsxvfVVj

I've also tried with a simple route with 2 points

I have originally saw the bug in a discussion in jeepolog.com:
http://www.jeepolog.com/forums/showthread.php/107954-%D7%94%D7%9E%D7%A8%D7%AA-%D7%A7%D7%91%D7%A6%D7%99%D7%9D?p=789862#post789862

**Comment by HarelM** [comment]
As a rule, I wouldn't recommend trying to convert to twl. it's a very old format that doesn't support most of what exists today.
Having said that, we are using GPSBabel to covert data from one type to the other.
The way GPSBabel works is that it will convert TWL to way points and the other way around.
So in order to create a TWL file you need to create way points (markers) and not use the regular route planning.
See here:
https://www.gpsbabel.org/htmldoc-development/fmt_naviguide.html

I'm not sure this is a bug, but rather a limitation of the TWL format.

**Comment by hagai-lvi** [comment]
Thanks Harel
any chance it didn't always work like this? for some reason I remember myself downloading a twl that I made from a route, and not waypoints, but maybe I'm wrong.

Either way, maybe it is worth considering telling it to the user when he is trying to download a twl, **if there is a route and not only waypoints**, or better, to convert (somehow) a route to waypoints?

Today as a user, I have no way to understand what you've just told me from the map...

**Comment by HarelM** [comment]
I don't think it ever worked differently, but I agree the user experience is not ideal.
To be honest, I'm not sure why anyone would still use this format. I tend to think it will be better just to remove it from the save-as list and allow only to open this type of file.
I'll keep it open until we decide what to do with this.
Thanks for reporting the issue!

**Comment by zstadler** [comment]
@hagai-lvi, 
Thanks for the report. It definitely worked in the past.

As far as I understand, the site generates gpx files containing tracks and waypoints while GPSBabel can only convert gpx routes to Naviguide (twl) files. Since the input gpx file does not contain any route, the output twl file is empty. Luckily, gpsbabel is able to transform the track into a route given the `-x transform,rte=trk` parameter.

@HarelM,
I could not locate the gpsbabel invocation code in the repository, so I was unable to test the proposed fix.

**Comment by HarelM** [comment]
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.DataAccess/GpsBabelGateway.cs
https://github.com/IsraelHikingMap/Site/blob/bc905c824e962081a60a0127b732ea69b9407618/IsraelHiking.API/Services/DataContainerConverterService.cs#L138

**Comment by HarelM** [comment]
I agree the interface may need to change, but you can also use the flag just after the format. i.e in:
https://github.com/IsraelHikingMap/Site/blob/2ecd2322e3304cd35c541e2cbecf9bc499ea9c22/IsraelHiking.API/Converters/ConverterFlows/IConverterFlowItem.cs#L43

`TWL_BABEL_FORMAT =  "naviguide -x transform,rte=trk"
It's a hack, but doesn't require interface change and it currently only applies to twl.
