### ISSUE TITLE
Private point of interest (POI)

### ISSUE THREAD

**Issue by MenasheKorot** [IsraelHikingMap/Site#753]
## Bug/Feature
I suggest that a POI be a uniform mechanism for public POI and for private.
Each POI will have the same characteristics (as public POIs)
Two CheckBox fields are needed to add, One - will receive the value "private point" and the other "public point".
The person who creates the POI can decide whether he wants to see it in his private database.
It will also be necessary to add a field where the details of who created the POI So that whoever created the POI will find all his POIs even if he has not marked them as private.

**Comment by HarelM** [comment]
> It will also be necessary to add a field where the details of who created the POI So that whoever created the POI will find all his POIs even if he has not marked them as private.

Not sure what you mean by that.
There is a feature request that will be implemented soon about contribution author: #730 

The concept of converting between private POI and public POI is adequate in my perspective - a user should actively decide to add a public POI, it shouldn't be a mere checkbox or radio button in order to reduce clutter or irrelevant public POIs, the fact that it's a bit complex makes the content better, in my opinion. Much like the fact that no every blog post becomes a Wikipedia article.

**Comment by MenasheKorot** [comment]
At Amud Anan I can find all the public points of interest I have uploaded to the site.
In any public POI, the person who created the POI marked as "Source" and you can see the username.
In this way I can locate my points of interest without having to mark them as private.
There are points that I mark as private because I know they have no value in the eyes of others and if I make them public it only bothers.

**Comment by HarelM** [comment]
As I said, there is an issue that will be implemented soon regarding contributor name: #730.
You can use OSM API and other OSM tools to see which points you have added or updated and there are a lot of tool that do different things around OSM editing history, I'm not planning on creating another tool for it unless I see a big value to the user, which currently I don't see.
It will be better to define the requirement in term of behavior and not functionality.
for example: As a user I would like to see all the past edits I made so that I can see that I didn't make a mistake in one of them.
