### ISSUE TITLE
Duplicate Wikipedia item

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#760]
## What I expect to happen
One link to one Wikipedia item in the POI panel

## What really happened
The POI for [רוג'ום אל הירי](https://israelhiking.osm.org.il/poi/OSM/node_697073194?language=he) has two links to the same Wikipedia item.

![image](https://user-images.githubusercontent.com/1304610/42703886-8f5982d4-86d6-11e8-9f67-604604630b97.png)

1. With an underscore [גלגל_רפאים](https://he.wikipedia.org/wiki/%D7%92%D7%9C%D7%92%D7%9C_%D7%A8%D7%A4%D7%90%D7%99%D7%9D)
2. With a space [גלגל רפאים](https://he.wikipedia.org/wiki/%D7%92%D7%9C%D7%92%D7%9C%20%D7%A8%D7%A4%D7%90%D7%99%D7%9D)

**Comment by HarelM** [comment]
This is due to incorrect mapping as far as I understand.
Wikipedia tag should be "גלגל רפאים" and not "גלגל_רפאים".
The site takes care of it automatically if you paste the address from the address bar of a Wikipadia page to the website field in IHM site.
It also adds `wikipedia:he` tag to better support multi language.
