### ISSUE TITLE
Downsizing routes to 10k nodes

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#763]
Feature
Add the ability to down-size routes to 10,000 nodes.
This is important for long events attended by people using Garmin devices.
The algorithm should preserve max fidelity, especially at turns.
To not complicate the interface further "simplified GPX" can be an option in the save as dialogue.

## Short Facebook discussion:
https://m.facebook.com/groups/235478759861499?view=permalink&id=1731990543543639

**Comment by HarelM** [comment]
The facebook link is unavailable for me...
I'm tired of fixing issue for Gramin users.
They should contact Garmin support and ask them to fix it.
This has gone too far... sorry...

**Comment by valleyofdawn** [comment]
Simplifying routes is also useful for other users as long routes are a drag to work with. They take long to open and manipulate.

**Comment by HarelM** [comment]
Please elaborate a use case where this is practical - how does one would use this feature.
Better if you define it with the following template:
"As a IHM user I would like to ... so that I'll be able to ..."
Adding another option to the save-as dropdown requires a very good reason since there are already too many options there which are cryptic...

**Comment by zstadler** [comment]
Another option is to re-label the "save-as" options according to their use-cases.

For example, if Garmin users need to use "GPX version 1.1 (GPX)" , then that label can be renamed to "GPX for Garmin". Using this save option would whatever is needed and possible in order to support Garmin users, potentially also the simplification to less than 10000 points

**Comment by valleyofdawn** [comment]
Indeed all the labels for the different GPXs have become confusing.
I dealt twice with files for multiple day rides that consisted of spliced plans and GPS recordings. They took long to open and got stuck when manipulated.
Once I published them people asked for me to cut them into manageable pieces - likely experiencing similar problems.
I saved it, ran it through the simplification process at GPSies and imported and published it again.
I would like to be able to do it in house, but I wouldn't like the interface to be more complicated than it already is.

**Comment by HarelM** [comment]
I'm not sure it's worth bringing in this in house - it might be better to keep GPS manipulation in sites that are dedicated for it or create a separate page to allow this functionality.
Regarding the labels - GPX version 1.1 (just an example) is probably not only for Garmin, labeling it as so would create a misleading label.
As I said, Garmin should create a software that is capable of doing things in order to make a file work on their devices, much like camera manufactures create software to facilitate backing up pictures that were taking using a camera - this is the industry standard - to create a software to backup a piece of hardware, if Garmin users have an issue they should contact Garmin, not us.

**Comment by valleyofdawn** [comment]
How about including a "simplify" button in the advanced route properties, then?
There is such a filter in GPSbabel, so it might be fairly simple.
https://www.gpsbabel.org/htmldoc-development/filter_simplify.html
