### ISSUE TITLE
Improve route properties dialogue

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#772]
## Feature
1) preview: It would be useful to include a preview of the route appearance in the properties dialogue.
Right now the color changes the "color" title (even though it's already selected in the palette)
The opacity changes the "opacity" title, making it invisible at its extreme,
The thickness slider changes nothing, and you don't know what it would look like until you save.
2) Change the sliders to be green like the rest.
3) Km marks instead of (rarely used) all dots shown.
4) Cleanup of unnecessary elements
![format design](https://user-images.githubusercontent.com/689201/43091382-a3566ee4-8eb2-11e8-9054-17375c40bd22.png)

**Comment by HarelM** [comment]
Thanks for the great ideas!
scroller issue is open for a while, see if you can add a comment there to make them fix it: https://github.com/angular/material2/issues/6959
star (*) is a known form notation to indicate a required field - not planning on changing it.
I have removed hint label for the name.
I think the preview is an overkill, just click OK and see how it looks (you'll need to do it anyway to see how it looks on the map).
I have removed the color label and switched to round buttons.
Not planning on removing a feature a user asked for - all dots shown.
Not planning on moving the km markers button - I think it is in the right place next to the height graph as they share the same concept of looking on the route statistics.
Changed sliders to green.
I don't see a reason to change the opacity behavior since I think it's OK, not great but not annoying.
After changes:
![image](https://user-images.githubusercontent.com/3269297/43106300-c09baea0-8ee0-11e8-8bee-af00d60d703a.png)
