### ISSUE TITLE
Simplify basic mode

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#797]
## Feature
I suspect that first time users find the interface, especially in the website, too complicated. This may overwhelm them and deter them from using the site.
I suggest moving the expert/novice switch to the top level. 
Having it in novice mode would hide the following elements, which are not strictly essential for the site to function:
1) print
2) save as
3) edit OSM map
4) add layer
5) add private route
6) unite, and reverse route
7) cut route
8) show POI/WPT coordinates
9) upload POI

**Comment by valleyofdawn** [comment]
If I can try to explain without a mock-up. Take the existing  "Toggle advanced settings" element from the top of the layers/maps/routes window and put it instead on the top page. Above the zoom controls. Have it control elements throughout the site/app.
I would suggest a functional test for what is to be omitted in novice mode: any button that according to Google Analytics is used less than 1% of the time.

**Comment by HarelM** [comment]
> I would suggest a functional test for what is to be omitted in novice mode: any button that according to Google Analytics is used less than 1% of the time.

This is not a great way to pick which buttons are important as you may want to emphasize certain buttons according to business needs - for example - upload private POI to OSM.

I need a mock-up or a phone call since I don't understand exactly what you describe, there's no way around it, describing UI/UX changes in code is open to interpretations most of the time...

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/45160758-e6f7c680-b1f2-11e8-9a9a-9d5eb69e1f02.png)
![image](https://user-images.githubusercontent.com/689201/45160775-ed863e00-b1f2-11e8-8d31-553f4cc6e8a5.png)

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/45160875-30481600-b1f3-11e8-9e6b-e8f874c87c5c.png)
![image](https://user-images.githubusercontent.com/689201/45160882-376f2400-b1f3-11e8-8108-42895051b16d.png)

**Comment by HarelM** [comment]
I think that this UX doesn't reduce clutter and complexity much and the toggle button is not intuitive.
I don't see a good reason to do it.
An oruxmaps buttons configuration screen would be more helpful but extremely complex so I really don't see a reason to go that way.
A video tutorial would probably be a better explanation instead of removing a button or two...
See this issue #735.

**Comment by valleyofdawn** [comment]
Maybe
![knives](https://user-images.githubusercontent.com/689201/45170614-ef5afc00-b208-11e8-8214-60c6d3fb4f46.png)

**Comment by zstadler** [comment]
The "Advanced" toggle can also be placed in the user preferences

![45118552-75236c80-b161-11e8-86fd-5904de29c37f](https://user-images.githubusercontent.com/1304610/45204017-af3a5e80-b286-11e8-9392-ba73d61d3f40.png)

Either before or after the language preference

**Comment by valleyofdawn** [comment]
Another element what can be omitted from the simplified version is finding missing sections in a recording.

**Comment by valleyofdawn** [comment]
Maybe it's time to reconsider this since everything is being programmed from scratch anyway.

**Comment by HarelM** [comment]
I don't mind moving the advance button to the user profile dropdown except for the fact that non registered users won't be able to move to advance mode, but I'm OK with that.
I'm OK with removing the add baselayer and overlay in non-advance mode, and the edit in OSM.
Other than that, I don't agree with what you define in advance.
Also I don't think a fancy toggle button is in order here, mainly because I have no clue how to implement it... Keeping it as @zstadler suggested with a check-box.

**Comment by HarelM** [comment]
After changes, I honestly don't see a significant change... Never the less, it didn't took me long...
![image](https://user-images.githubusercontent.com/3269297/50495854-848e3480-0a34-11e9-8e58-3014908b3900.png)
![image](https://user-images.githubusercontent.com/3269297/50495857-8eb03300-0a34-11e9-9fa2-389899a2d3ab.png)

**Comment by valleyofdawn** [comment]
Thank you. I appreciate that.
Perhaps also get rid of the redundant exit button at the top level.
Also please reconsider moving the language button to the profile window.

**Comment by HarelM** [comment]
Exit button is important, not planning on removing it.
We do not agree about the language button and there's a separate issue about it.

**Comment by valleyofdawn** [comment]
Exit is important but why 2 of them, one on the top page and one in the
profile.
A general guideline I think is that if it's less than 1% of the button
presses, it should not be on the top page. This is something we could
actually check.

**Comment by valleyofdawn** [comment]
No,no. I meant the logout button.

**Comment by HarelM** [comment]
This is in order to create a unified buttons line and to emphasise this button - style considerations.
