### ISSUE TITLE
Search is not returning the exact match

### ISSUE THREAD

**Issue by Moshe81** [IsraelHikingMap/Site#834]
## Bug-Feature

When searching "הר תבור"  we get first result "בור בתור" while the exact match is 4ed in the results
## What I expect to happen
we expect that if there is an exact match it should be the first

## What really happened
it was the 4th results

## What I did that caused the issue - step by step
search for that text

## My environment
Chrom
Windows 10

* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.
https://forloop.co.uk/blog/favouring-exact-matches-in-elasticsearch
Also relevant since the title is not a single word in the documents:
https://www.elastic.co/guide/en/elasticsearch/guide/current/_multivalue_fields_2.html

**Comment by HarelM** [comment]
@Moshe81 I'm revisiting this issue now.
Seems like הר תבור is now linked with a wikipedia value and thus it is ranked higher now and appears first.
Can you find another search term that produces "bad" results so I can test a fix once I have one?

**Comment by Moshe81** [comment]
Thansk.
So I tried a few more - most of them were ok.
I found that the search מעלה יאיר  bring resoults wihtout the strings before resoults that actually contains it
![image](https://user-images.githubusercontent.com/29856634/75316785-f0557280-586e-11ea-85a5-420b0caf48d4.png)

**Comment by HarelM** [comment]
While the search can be improved, every time I dive into this I find out this is not straightforward and the complexity versus improvement is very low.
I usually am able to find what I'm looking for when it comes to outdoors locations. It might be because I know the limitations of the search and how to work around them, but I genuinely feel it's good enough. 
Therefore, with mixed feelings, I have decided to close this issue.
