### ISSUE TITLE
Open Gpx File From Drive In Site

### ISSUE THREAD

**Issue by bermaneyal** [IsraelHikingMap/Site#844]
## Feature

[movie.zip](https://github.com/IsraelHikingMap/Site/files/2446420/movie.zip)

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment]
Issue #813 describes a usage from dropbox and not only from google drive. It would be great if this extension will facilitate for this as well.

**Comment by HarelM** [comment]
Instructions related to google drive open with UI can be found here:
https://developers.google.com/drive/api/v2/enable-sdk

**Comment by HarelM** [comment]
Studying this reveals that a user needs to grant the site access to google drive before this is possible. This barrier is a killer to this feature as far as I can see.
While this is nice and all, the fact is that less and less users are using the desktop, and files are not our recommendation any more due to a lot of issues related to files.
When uploading a file to google drive and opening the file from the drive on the android device (not sure about iOS) the app is offered to open the file.
I think this is the most used use-case. In the desktop a user can simply download  the file to the computer (if the drive is not synced) and drag the file to the site, or use the open button.
Closing...
I think this is a better than the alternative of needing to allow the website permission to google drive
