### ISSUE TITLE
Error adding routes to OSM

### ISSUE THREAD

**Issue by zoharkolberg** [IsraelHikingMap/Site#848]
## Bug
i have loaded gpx file and looked for new tracks. tried to add new tracks to osm bu received error message.

## What I expect to happen
track to be loaded. i have done it few times successfully

## What really happened
error message:
![image](https://user-images.githubusercontent.com/40534379/46623209-91864080-cb35-11e8-8dfe-5eb5a05901df.png)

## What I did that caused the issue - step by step
loadede file to my recordings
clickd find un mapped routs
tried to add rout to osm

## My environment
* Operating System and version:
* Web Browser and version:

## Thing I think the developers should know, images, links etc.

[Afternoon_Ride.zip](https://github.com/IsraelHikingMap/Site/files/2456925/Afternoon_Ride.zip)

**Comment by HarelM** [comment]
Hi @zoharkolberg,
Can you please check if this was resolved? I took the afternoon file and tried to add a part from it with success.
If this fails, please add more info on what steps exactly to made so I'll be able to reproduce the issue.
It seems like there was an issue with the ways database starting from 16/10, but it seems this issue is older so I'm not sure it is related.

**Comment by HarelM** [comment]
I think you sent me the wrong file, the missing trail in the image above is not part of the recording:
![image](https://user-images.githubusercontent.com/3269297/48123623-0ce92800-e283-11e8-9c08-e87efab163ce.png)

**Comment by zoharkolberg** [comment]
בחירת קובץ הקלטה שהועלה מראש ולחיצה על צלמית זכוכית המגדלת - חפש מסלולים לא
ממופים:
[image: image.png]
מופיע מסלול שאכן לא ממופה, אני לוחץ על צלמית הכוכב..
[image: image.png]
תפריט בחירת סוג המסלול, לחיצה על צלמית ה + להוספה ל OSM
[image: image.png]
... מתקבלת ההערה המרגיזה באדום בתחתית הדף

**Comment by HarelM** [comment]
נראה שהייתה בעיה לשלוח את התמונות דרך המייל (אני מניח שהשתמשת במייל).
תוכל לערוך את ההודעה בgithub וכך אוכל לראות את התמונות?
סליחה על ההצקות, אבל אני באמת רוצה לעזור :-)

**Comment by zoharkolberg** [comment]
גיטהאב ואני לא חברים טובים.. קבל מסמך docs:
https://docs.google.com/document/d/1BHbylJNKQ2MOKnPtARlkpRtly6UVpvWUeob0u8cp4Hg/edit?usp=sharing

**Comment by HarelM** [comment]
@zoharkolberg 
אני עדיין מחכה לקובץ הנכון.
בלי קשר, אחרי שהקלטתי מסלול היום וניסיתי להעלות אותו מצאתי באג שייתכן והוא אותו אחד שאתה חווה.
ברגע שיהיה לי את הקובץ העדכני אני אוכל לבדוק את התיקון שעשיתי ולראות אם זו אותה בעיה או לא.
תיקון לשרת יעלה לצערי רק כאשר אני אסיים עם #669...

**Comment by zoharkolberg** [comment]
a

**Comment by zoharkolberg** [comment]
שלחתי...
שולח שוב.

**Comment by zoharkolberg** [comment]
שלחתי שוב.
קיבלת??

**Comment by HarelM** [comment]
לא, תוכל בבקשה להיכנס לגיטהאב ולנסות להעלות את זה פה?

**Comment by zoharkolberg** [comment]
Afternoon_Ride (1).gpx
<https://drive.google.com/file/d/0B0wi6IyuOS_aQVpaa0RhQ1k2bm10ZWhZZjRDSlQxVktUZDdN/view?usp=drive_web>

**Comment by zoharkolberg** [comment]
[Afternoon_Ride (1).gpx.tar.gz](https://github.com/IsraelHikingMap/Site/files/2592608/Afternoon_Ride.1.gpx.tar.gz)

**Comment by HarelM** [comment]
Got it, thanks! Will hopefully review the issue tonight.
In case I manage to add it, the correct type is 4x4 way with no color, right?

**Comment by HarelM** [comment]
It seems that the fix I made solved this issue as well :-).
I have added the route to OSM and will publish this fix after I finish implementing #669.
Thanks a lot for reporting this issue!
It is extremely important that if you see issues with this algorithm report is here, otherwise we'll probably won't know about it as we have very limited testing resources...
