### ISSUE TITLE
Reducing the number of route points in straight line routing

### ISSUE THREAD

**Issue by davidih** [IsraelHikingMap/Site#852]
## What I expect to happen
When using a straight line routing and saving as a single route GPX, the route points should appear only in the beginning and the end of each route segment. 

## What really happened
By now there are tens and even hundreds of route points for each segment. This creates the following problems:
- Many GPX apps have a limit on the number of route points in a route (usually 128 or 256). Track points have a much higher limit
- Cannot set an alarm in the turning point 
- The file is 20 times bigger than it should be

## What I did that caused the issue - step by step
1. Create a route using the straight lines option
2. Save as Single route GPX

## My environment
* Operating System and version:
Any

* Web Browser and version:
Any

**Comment by HarelM** [comment]
This is somewhat by design: See issue #637.
If you have a problem with a specific device that doesn't allow using a GPX file with this number of points I suggest opening a bug to the device's manufacture, or the relevant app. 
We can't continue to make patches in our software because other software do not work as expected.
If they refuse to fix their bug and we see that this is a relevant case for many users we can consider fixing it.
If you would like to take the time and suggest a solution and send a pull request we might consider adding it.

**Comment by HarelM** [comment]
No response was given. Closing.
