### ISSUE TITLE
Unable to add 2 shares to my private routes

### ISSUE THREAD

**Issue by Moshe81** [IsraelHikingMap/Site#921]
## What I expect to happen
כיום כאשר אני רוצה לראות כמה מסלולים שרכבתי בהם בעבר אני לוחץ על שם הפרופיל שלי-> השיתופים שלי-> בוחר את המסלול -> לוחץ על אייקון ה"+" למטה וההקלטה מוצגת על המפה. בשביל לראות מסלול נוסף על המפה אני חוזר על התהליך וככך רואה שני מסלולים ויכול לערוך בניהם ואף לחברם. 

## What really happened
בגירסת הבטא כפתור ה "+" התחלף באיקון של עין, וכאשר לוחצים עליו מוצג המסלול הנבחר אבל המסלול שהיה פתוח נעלם. ההתנהגות החדשה מונעת מלפתוח כמה הקלטות במקביל.
Manage
![50452729_10162042240555725_155394729972858880_n](https://user-images.githubusercontent.com/29856634/51347545-0f4cd700-1aa9-11e9-836b-781a0928911c.jpg)
![50514829_10162042231030725_310031995218427904_n](https://user-images.githubusercontent.com/29856634/51347547-0f4cd700-1aa9-11e9-954c-c18ae831a9f3.jpg)

**Comment by Moshe81** [comment]
כיום כאשר אני רוצה לראות כמה מסלולים שרכבתי בהם בעבר אני לוחץ על שם הפרופיל שלי-> השיתופים שלי-> בוחר את המסלול -> לוחץ על אייקון ה"+" למטה וההקלטה מוצגת על המפה. בשביל לראות מסלול נוסף על המפה אני חוזר על התהליך וככך רואה שני מסלולים ויכול לערוך בניהם ואף לחברם. בגירסת הבטא כפתור ה "+" התחלף באיקון של עין, וכאשר לוחצים עליו מוצג המסלול הנבחר אבל המסלול שהיה פתוח נעלם. ההתנהגות החדשה מונעת מלפתוח כמה הקלטות במקביל.
Manage
![50452729_10162042240555725_155394729972858880_n](https://user-images.githubusercontent.com/29856634/51347545-0f4cd700-1aa9-11e9-836b-781a0928911c.jpg)
![50514829_10162042231030725_310031995218427904_n](https://user-images.githubusercontent.com/29856634/51347547-0f4cd700-1aa9-11e9-954c-c18ae831a9f3.jpg)

**Comment by HarelM** [comment]
The difference comes from the fact that everything is now saved between editing sessions, so when opening a share the data should be dismissed in order to reduce routes clutter and keep how it used to work before this change.
The request to keep old functionality is still a valid request though.
I have added a button to differentiate between adding and showing:
![image](https://user-images.githubusercontent.com/3269297/51397356-b4b78780-1b49-11e9-9d9e-8edf9df7e23e.png)

**Comment by Moshe81** [comment]
Sound good.
I can still do not see the new implementation - will follow.
Thanks
Moshe
