### ISSUE TITLE
Position along route not shown in altitude profile window when hovering over route in map window

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#951]
## What I expect to happen
When hovering over the altitude profile, the position along the route is shown in the map window, and altitude and mileage info is shown in the altitude profile window. The same should also happen when hovering over the route in the map window. 

## What really happened
nothing

## What I did that caused the issue - step by step
create a route. 
expand the altitude window.
hover the route when not in edit mode.

## My environment
* Operating System and version: Win 10
* Web Browser and version: Chrome

## Thing I think the developers should know, images, links etc.
Was working fine in previous version

**Comment by HarelM** [comment]
Thanks for taking the time and opening this issue.
This was mentioned here: #669. This was removed due to implementation complexity and the fact that I don't see a strong use case where this will be needed since you can just hover the chart.
Besides the fact that this use to work can you share a use case where this is absolutely necessary?

**Comment by oriori** [comment]
It's not critical. Like many other features. It makes the UX better.
It's much easier to hover over the route when you want to get the info for a very specific point; when the route is long; when you're zoomed into a small section of the route; when you have a loop in the route and want to get the info just before and right after the loop. This examples are  just from the top of my head.
