### ISSUE TITLE
Avoid keeping saved routes between sessions

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#968]
## What I expect to happen
When opening the app or the web page after saving the route/s and closing the app/web, the saved route/s would not be shown.

This issue captures [this Facebook comment](https://www.facebook.com/groups/994960670559126/permalink/2070920699629779/?comment_id=2071624462892736&comment_tracking=%7B%22tn%22%3A%22R1%22%7D)

## What really happened
When opening a new session, the saved routes are preserved and must be removed. Several people have supported this request. 

In this scenario, there is no risk of data loss.

**Comment by HarelM** [comment]
The definition of a session and the exact moment of sharing and closing is hard to define and implement.
The main incentive for the original feature was that when using the mobile app/mobile browser and the OS closes the app/browser your data got lost.
Assuming mobile web is less interesting as a candidate since there's an app now we can separate the behavior so that when using the mobile app the routes are kept and when using desktop the routes are cleaned every time you refresh.
This won't prevent data loss on desktop web but will revert the behavior to how it used to be before the change - this is a relatively easy change.
IMO, I don't think clicking 3 buttons is that hard and people probably need to get used to the new experience.

**Comment by HarelM** [comment]
It was agreed that on the meeting we had that routes will not be stored between browser session on the desktop version.
