### ISSUE TITLE
Site restore is missing the last change

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#979]
## What I expect to happen
When the site is opened, the last state is restored

## What really happened
- The most recent change is not visible
- Pan and zoom changes are ignored

## What I did that caused the issue - step by step
We will use a second tab to emulate a restore
- Open the site in two tabs. The map should be identical in both.
- Choose the Hiking map as the base map in the first tab and then change the base map to the MTB map
- Refresh the second tab
   - The base map of the second tab is the Hiking map
- Change the base map in the first tab to ESRI and refresh the second tab
   - The base map of the second tab is the MTB map
- Add a private POI in the first tab and refresh the second tab
   - The base map of the second tab is the ESRI map, but the new POI is not shown

Similarly, changes on map position and zoom, including such changes caused by selecting search results, are not restored

## My environment
* Operating System and version: Win 10 Home
* Web Browser and version: Firefox 56.0.2 (64-bit)

**Comment by HarelM** [comment]
In order to reduce database writing, which uses a lot of resources, only once in two seconds the state is saved.
Also keeping a second browser window is not the right way to test the functionality, IMO.

Please repeat the above tests while waiting 2 seconds after each change and always open a new tab and do not refresh an already opened tab.
If this works as expected, please close this issue.

Regardless, this conflicts with #968, so I don't see a reason to handle this before #968 is solved or removed.

**Comment by zstadler** [comment]
From the console output, it looks like the issue was caused by issues with the local storage, perhaps exceeding the quota.
I've deleted all local storage using the developer's tools and there are no errors.

I'm closing this issue although I'm not sure what a regular user could do if the local storage quota is exceeded.
