### ISSUE TITLE
אי אפשר להוסיף תמונה לעין ירקעם

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#986]
## Bug
Reported by @onzd

## What I expect to happen
Be able to add an image

## What really happened
No edit button exists

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by zstadler** [comment]
In addition, selecting "עין ירקעם" in the search result opens the following side pane, but the map dos not focus on it, probably because there is no location

   ![image](https://user-images.githubusercontent.com/1304610/53695470-d2bd0c80-3dc4-11e9-8046-6ad91ef8f63f.png)

The address bar is correctly updated to https://israelhiking.osm.org.il/poi/OSM/node_2619083140

**Comment by HarelM** [comment]
Related to a fix I did for #975, the server fails to retrieve the data related to that point.
I have fixed the issue and am now running a full rebuild which didn't run in the last week apparently... :-/
